addMarkerAtLatLng(48.856614,2.352222);
addMarkerAtLatLng(16.525915,-90.189307);
addMarkerAtLatLng(41.795233,8.741819);
addMarkerAtLatLng(14.09396,-88.889278);
addMarkerAtLatLng(15.80122,-91.755234);
addMarkerAtLatLng(51.094564,-1.674561);
addMarkerAtLatLng(-6.15837269318,155.382212277);
addMarkerAtLatLng(12.62439,-87.129784);
addMarkerAtLatLng(35.960495,-83.920914);
addMarkerAtLatLng(34.693738,135.502165);
addMarkerAtLatLng(51.457935,7.014828);
addMarkerAtLatLng(39.720008,140.102564);
addMarkerAtLatLng(40.71455,-74.007124);
addMarkerAtLatLng(54.530715,-6.811011);
addMarkerAtLatLng(15.633333,-90.95);
addMarkerAtLatLng(14.93561,-91.871226);
addMarkerAtLatLng(35.664035,139.698212);
addMarkerAtLatLng(42.358518,9.164956);
addMarkerAtLatLng(43.29218,5.569336);
addMarkerAtLatLng(25.091075,121.559834);
addMarkerAtLatLng(42.567651,8.757222);
addMarkerAtLatLng(13.84222,-89.09694);
addMarkerAtLatLng(25.728985,-80.237419);
addMarkerAtLatLng(54.767773,-7.251106);
addMarkerAtLatLng(43.309635,-3.00694);
addMarkerAtLatLng(50.827162,0.292498);
addMarkerAtLatLng(17.054348,-96.712954);
addMarkerAtLatLng(40.812778,44.488333);
addMarkerAtLatLng(54.347539,-6.656108);
addMarkerAtLatLng(13.304902,-86.186265);
addMarkerAtLatLng(-5.759613,155.117992);
addMarkerAtLatLng(50.732674,7.096299);
addMarkerAtLatLng(13.835,-89.2744444);
addMarkerAtLatLng(43.04999,-76.147389);
addMarkerAtLatLng(37.961651,-2.979867);
addMarkerAtLatLng(53.635249,-6.233848);
addMarkerAtLatLng(35.776608,140.318781);
addMarkerAtLatLng(54.673252,-7.627484);
addMarkerAtLatLng(54.518634,-5.888133);
addMarkerAtLatLng(43.370873,-8.395835);
addMarkerAtLatLng(13.7166667,-89.2333333);
addMarkerAtLatLng(41.093333,45.366111);
addMarkerAtLatLng(38.8061,-123.017709);
addMarkerAtLatLng(42.880447,-8.546303);
addMarkerAtLatLng(14.2337367544,-83.5388592765);
addMarkerAtLatLng(35.787649,139.903093);
addMarkerAtLatLng(54.706718,-7.592867);
addMarkerAtLatLng(51.500152,-0.126236);
addMarkerAtLatLng(40.210278,46.809167);
addMarkerAtLatLng(54.323924,-5.703051);
addMarkerAtLatLng(13.99417,-89.55972);
addMarkerAtLatLng(53.72438,-1.861577);
addMarkerAtLatLng(48.113475,-1.675708);
addMarkerAtLatLng(54.228228,-7.114886);
addMarkerAtLatLng(15.69018,-88.620407);
addMarkerAtLatLng(35.685826,139.756684);
addMarkerAtLatLng(35.329197,25.138667);
addMarkerAtLatLng(42.252285,-71.004164);
addMarkerAtLatLng(39.703619,141.152684);
addMarkerAtLatLng(14.15937229,-90.257084269);
addMarkerAtLatLng(13.7666667,-88.2666667);
addMarkerAtLatLng(14.791907,-91.71342);
addMarkerAtLatLng(43.220496,-2.733236);
addMarkerAtLatLng(40.183333,44.516667);
addMarkerAtLatLng(-6.232373,155.650803);
addMarkerAtLatLng(14.96833,-91.779497);
addMarkerAtLatLng(34.784306,135.400947);
addMarkerAtLatLng(43.230556,-2.845833);
addMarkerAtLatLng(34.05349,-118.245319);
addMarkerAtLatLng(13.85,-88.85);
addMarkerAtLatLng(14.854715,-91.149093);
addMarkerAtLatLng(41.096667,45.081944);
addMarkerAtLatLng(54.823432,-7.468374);
addMarkerAtLatLng(43.488387,-8.222509);
addMarkerAtLatLng(12.19185,-84.101286);
addMarkerAtLatLng(13.7682,-88.129139);
addMarkerAtLatLng(13.7333333,-88.8833333);
addMarkerAtLatLng(42.26299,-71.802354);
addMarkerAtLatLng(58.709753,13.823745);
addMarkerAtLatLng(18.380782,-65.957387);
addMarkerAtLatLng(32.221553,-110.969754);
addMarkerAtLatLng(35.653983,139.902203);
addMarkerAtLatLng(54.238631,-7.170908);
addMarkerAtLatLng(58.536597,15.037332);
addMarkerAtLatLng(19.7,-100.4791667);
addMarkerAtLatLng(40.53,72.8);
addMarkerAtLatLng(43.40443,-2.950102);
addMarkerAtLatLng(43.320812,-1.984447);
addMarkerAtLatLng(40.682778,46.360556);
addMarkerAtLatLng(41.079273,-85.139351);
addMarkerAtLatLng(35.906259,139.628634);
addMarkerAtLatLng(52.229676,21.012229);
addMarkerAtLatLng(55.033471,-7.357761);
addMarkerAtLatLng(41.54862,2.107421);
addMarkerAtLatLng(13.6247222,-87.8936111);
addMarkerAtLatLng(14.630728,-90.607637);
addMarkerAtLatLng(44.031529,15.60671);
addMarkerAtLatLng(13.557072,-88.349433);
addMarkerAtLatLng(14.801211,-91.822132);
addMarkerAtLatLng(34.463331,135.74024);
addMarkerAtLatLng(36.940556,-121.789444);
addMarkerAtLatLng(54.600305,-7.298402);
addMarkerAtLatLng(54.597269,-5.930109);
addMarkerAtLatLng(54.510893,-6.042726);
addMarkerAtLatLng(38.804565,-77.043079);
addMarkerAtLatLng(13.69288,-89.199161);
addMarkerAtLatLng(52.74368,-3.885441);
addMarkerAtLatLng(18.446,-66.387554);
addMarkerAtLatLng(41.471864,2.082139);
addMarkerAtLatLng(13.5166667,-88.3833333);
addMarkerAtLatLng(33.749074,-117.873943);
addMarkerAtLatLng(37.977978,-122.031073);
addMarkerAtLatLng(43.001304,-1.891916);
addMarkerAtLatLng(43.3282,-3.031509);
addMarkerAtLatLng(43.256963,-2.923441);
addMarkerAtLatLng(13.864829,-88.7494);
addMarkerAtLatLng(54.577389,-6.677339);
addMarkerAtLatLng(14.736569,-90.890018);
addMarkerAtLatLng(15.029167,-91.329444);
addMarkerAtLatLng(52.069858,4.291111);
addMarkerAtLatLng(43.175789,-2.27985);
addMarkerAtLatLng(42.433655,-8.648121);
addMarkerAtLatLng(14.169305,-88.923956);
addMarkerAtLatLng(54.351993,18.646611);
addMarkerAtLatLng(13.64121,-88.785423);
addMarkerAtLatLng(13.4833333,-88.4666667);
addMarkerAtLatLng(52.505803,13.331741);
addMarkerAtLatLng(-6.220475,155.63763);
addMarkerAtLatLng(41.387917,2.169919);
addMarkerAtLatLng(52.370216,4.895168);
addMarkerAtLatLng(37.605651,-0.991294);
addMarkerAtLatLng(41.860808,2.667772);
addMarkerAtLatLng(59.616462,16.551516);
addMarkerAtLatLng(54.542956,-6.926293);
addMarkerAtLatLng(13.414441,-88.343627);
addMarkerAtLatLng(14.930957,-91.909924);
addMarkerAtLatLng(14.07003,-90.463127);
addMarkerAtLatLng(46.3172,6.19385);
addMarkerAtLatLng(45.117799,39.423796);
addMarkerAtLatLng(20.673343,-103.344177);
addMarkerAtLatLng(35.180188,136.906565);
addMarkerAtLatLng(35.443708,139.638026);
addMarkerAtLatLng(52.921899,-1.475642);
addMarkerAtLatLng(41.919229,8.738635);
addMarkerAtLatLng(51.370489,6.172386);
addMarkerAtLatLng(35.856999,139.648849);
addMarkerAtLatLng(-8.974414,146.609497);
addMarkerAtLatLng(41.725175,1.823353);
addMarkerAtLatLng(13.6769444,-89.2797222);
addMarkerAtLatLng(41.450137,2.247419);
addMarkerAtLatLng(12.919106,-85.916609);
addMarkerAtLatLng(14.483333,-90.533333);
addMarkerAtLatLng(35.979375,140.149524);
addMarkerAtLatLng(14.740611,-91.159417);
addMarkerAtLatLng(54.502852,-6.769568);
addMarkerAtLatLng(43.31137,-3.055952);
addMarkerAtLatLng(51.512054,7.463573);
addMarkerAtLatLng(14.0833,-87.2167);
addMarkerAtLatLng(40.656422,-4.700322);
addMarkerAtLatLng(45.031933,35.382433);
addMarkerAtLatLng(14.7,-91.866667);
addMarkerAtLatLng(54.788077,-7.47303);
addMarkerAtLatLng(18.454645,-66.064619);
addMarkerAtLatLng(41.366667,9.266843);
addMarkerAtLatLng(54.625869,-5.982754);
addMarkerAtLatLng(18.47239,-66.719734);
addMarkerAtLatLng(14.297778,-90.786944);
addMarkerAtLatLng(35.443082,139.362489);
addMarkerAtLatLng(45.068938,16.375895);
addMarkerAtLatLng(39.829805,46.759851);
addMarkerAtLatLng(30.658601,104.064856);
addMarkerAtLatLng(52.63477,-1.129519);
addMarkerAtLatLng(12.136389,-86.251389);
addMarkerAtLatLng(15.563722,-88.625796);
addMarkerAtLatLng(43.545261,-5.661926);
addMarkerAtLatLng(40.656409,-4.700426);
addMarkerAtLatLng(54.18006,-6.33393);
addMarkerAtLatLng(59.858144,17.644586);
addMarkerAtLatLng(8.427805,-82.430643);
addMarkerAtLatLng(36.890196,140.008702);
addMarkerAtLatLng(50.928877,-2.856801);
addMarkerAtLatLng(39.936667,46.832778);
addMarkerAtLatLng(13.79833,-89.17889);
addMarkerAtLatLng(44.142987,16.098547);
addMarkerAtLatLng(13.09171,-86.00177);
addMarkerAtLatLng(42.232222,48.155278);
addMarkerAtLatLng(22.281867,114.161326);
addMarkerAtLatLng(40.639349,22.944616);
addMarkerAtLatLng(34.685087,135.805);
addMarkerAtLatLng(54.951082,-6.558998);
addMarkerAtLatLng(37.355509,-121.954262);
addMarkerAtLatLng(54.645861,-6.745149);
addMarkerAtLatLng(53.341,-1.28488);
addMarkerAtLatLng(42.846718,-2.671635);
addMarkerAtLatLng(35.011636,135.768029);
addMarkerAtLatLng(13.938518,-88.901366);
addMarkerAtLatLng(42.880888,20.867213);
addMarkerAtLatLng(37.805065,-122.273024);
addMarkerAtLatLng(42.816667,47.116667);
addMarkerAtLatLng(41.560953,2.01044);
addMarkerAtLatLng(38.254465,21.737066);
addMarkerAtLatLng(54.99451,-7.319996);
addMarkerAtLatLng(13.49446,-88.530343);
addMarkerAtLatLng(45.409538,11.876554);
addMarkerAtLatLng(39.810998,46.751147);
addMarkerAtLatLng(42.817988,-1.644184);
addMarkerAtLatLng(42.593869,-8.765962);
addMarkerAtLatLng(54.842824,-6.667731);
addMarkerAtLatLng(36.167783,-86.778365);
addMarkerAtLatLng(51.248429,-0.755979);
addMarkerAtLatLng(54.411142,-6.600146);
addMarkerAtLatLng(45.070562,7.686619);
addMarkerAtLatLng(52.516667,13.4);
addMarkerAtLatLng(45.511795,-122.675629);
addMarkerAtLatLng(13.9572222,-89.1897222);
addMarkerAtLatLng(52.104026,9.357261);
addMarkerAtLatLng(13.131923193,-86.3457422849);
addMarkerAtLatLng(35.33045,139.902677);
addMarkerAtLatLng(53.191458,-2.895007);
addMarkerAtLatLng(13.586201,-88.750773);
addMarkerAtLatLng(16.85,-90.883333);
addMarkerAtLatLng(45.796303,15.960716);
addMarkerAtLatLng(13.772142,-88.07664);
addMarkerAtLatLng(47.039225,-122.891429);
addMarkerAtLatLng(37.38264,-5.996295);
addMarkerAtLatLng(52.663857,-8.626773);
addMarkerAtLatLng(42.15,24.75);
addMarkerAtLatLng(40.140655,44.537998);
addMarkerAtLatLng(39.319439,46.146092);
addMarkerAtLatLng(42.340892,-3.699762);
addMarkerAtLatLng(41.67615,8.903952);
addMarkerAtLatLng(14.1928,-90.374835);
addMarkerAtLatLng(14.932162,-92.005523);
addMarkerAtLatLng(-6.7465,155.685171);
addMarkerAtLatLng(14.191665,-89.1706);
addMarkerAtLatLng(9.933333,-84.083333);
addMarkerAtLatLng(54.063074,-6.006978);
addMarkerAtLatLng(42.696492,23.326011);
addMarkerAtLatLng(50.850335,4.351685);
addMarkerAtLatLng(14.624422,-90.53288);
addMarkerAtLatLng(14.786319,-90.198581);
addMarkerAtLatLng(36.083486,140.076642);
addMarkerAtLatLng(34.487514,136.709336);
addMarkerAtLatLng(58.533712,31.291062);
addMarkerAtLatLng(41.591369,9.278311);
addMarkerAtLatLng(54.42071,-6.443767);
addMarkerAtLatLng(50.723645,-1.600276);
addMarkerAtLatLng(41.656285,-0.876533);
addMarkerAtLatLng(52.683556,-1.822359);
addMarkerAtLatLng(42.695391,-1.676069);
addMarkerAtLatLng(13.302702,-87.194423);
addMarkerAtLatLng(-5.874771,155.202988);
addMarkerAtLatLng(48.30694,14.28583);
addMarkerAtLatLng(8.994269,-79.518792);
addMarkerAtLatLng(16.912033,-90.299578);
addMarkerAtLatLng(34.515046,135.736392);
addMarkerAtLatLng(41.89052,12.494249);
addMarkerAtLatLng(15.095278,-91.150833);
addMarkerAtLatLng(13.445104,-88.246118);
addMarkerAtLatLng(14.965261,-91.795813);
addMarkerAtLatLng(45.445059,8.61863);
addMarkerAtLatLng(43.32412,-1.929857);
addMarkerAtLatLng(36.848311,-75.979278);
addMarkerAtLatLng(32.715695,-117.161719);
addMarkerAtLatLng(54.863117,-6.278343);
addMarkerAtLatLng(34.685354,135.832742);
addMarkerAtLatLng(41.652943,-4.728381);
addMarkerAtLatLng(51.192442,5.994695);
addMarkerAtLatLng(41.3275,19.8188889);
addMarkerAtLatLng(13.95,-88.63333);
addMarkerAtLatLng(43.34872,-3.010091);
addMarkerAtLatLng(41.126667,45.3075);
addMarkerAtLatLng(13.6333333,-88.2666667);
addMarkerAtLatLng(37.97918,23.716647);
addMarkerAtLatLng(13.466667,-88.183333);
addMarkerAtLatLng(37.566535,126.977969);
addMarkerAtLatLng(40.587515,-122.392934);
addMarkerAtLatLng(14.77312,-91.183037);
addMarkerAtLatLng(16.331111,-89.416944);
addMarkerAtLatLng(43.07563,-2.223667);
addMarkerAtLatLng(14.4,-91.3167);
addMarkerAtLatLng(18.5391667,-72.335);
addMarkerAtLatLng(39.840737,72.898807);
addMarkerAtLatLng(54.192934,-6.576051);
addMarkerAtLatLng(13.902951,-89.496613);
addMarkerAtLatLng(43.272052,-2.949076);
addMarkerAtLatLng(-3.584338,141.216599);
addMarkerAtLatLng(35.888287,-5.316195);
addMarkerAtLatLng(12.10629,-85.36452);
addMarkerAtLatLng(43.570376,7.077506);
addMarkerAtLatLng(35.610485,138.940028);
addMarkerAtLatLng(53.096828,-4.247399);
addMarkerAtLatLng(19.432608,-99.133207);
addMarkerAtLatLng(18.456792,-69.951164);
addMarkerAtLatLng(40.930004,45.467064);
addMarkerAtLatLng(43.052649,-3.001022);
addMarkerAtLatLng(-6.228251,155.565903);
addMarkerAtLatLng(54.317811,-7.536546);
addMarkerAtLatLng(38.848033,-77.12916);
addMarkerAtLatLng(52.372068,9.735686);
addMarkerAtLatLng(51.455313,-2.591902);
addMarkerAtLatLng(42.397834,9.492342);
addMarkerAtLatLng(34.509448,135.792626);
addMarkerAtLatLng(43.169068,-2.632655);
addMarkerAtLatLng(13.8333333,-88.7166667);
addMarkerAtLatLng(53.823933,9.287901);
addMarkerAtLatLng(54.755402,-6.606029);
addMarkerAtLatLng(40.416691,-3.700345);
addMarkerAtLatLng(42.697283,9.450881);
addMarkerAtLatLng(54.577792,-2.518802);
addMarkerAtLatLng(54.467967,-6.337967);
addMarkerAtLatLng(50.79891,-1.091163);
addMarkerAtLatLng(39.470239,-0.376805);
addMarkerAtLatLng(43.188611,-8.470278);
addMarkerAtLatLng(51.553731,-1.150317);
addMarkerAtLatLng(13.344322,-88.437463);
addMarkerAtLatLng(9.358577,-79.900015);
addMarkerAtLatLng(13.43204,-88.592239);
addMarkerAtLatLng(29.76045,-95.369784);
addMarkerAtLatLng(13.8769444,-89.173556);
addMarkerAtLatLng(59.332788,18.064488);
addMarkerAtLatLng(36.321909,139.003294);
addMarkerAtLatLng(40.069099,45.038189);
addMarkerAtLatLng(41.118663,1.24533);
addMarkerAtLatLng(24.80485,-107.385498);
addMarkerAtLatLng(54.131402,-6.586387);
addMarkerAtLatLng(43.003305,-2.612578);
addMarkerAtLatLng(15.498381,-90.982067);
addMarkerAtLatLng(14.242671,-87.375283);
addMarkerAtLatLng(18.203831,-67.146469);
addMarkerAtLatLng(55.75,37.616667);
addMarkerAtLatLng(11.727473,-86.21585);
addMarkerAtLatLng(43.299442,-1.859099);
addMarkerAtLatLng(14.866667,-91.933333);
addMarkerAtLatLng(32.750286,129.877667);
addMarkerAtLatLng(50.143338,8.569075);
addMarkerAtLatLng(-6.315071,155.495276);
addMarkerAtLatLng(50.087811,14.42046);
addMarkerAtLatLng(51.305605,-0.901253);
addMarkerAtLatLng(38.268837,140.8721);
addMarkerAtLatLng(43.383952,-1.30525);
addMarkerAtLatLng(14.277349,-90.303779);
addMarkerAtLatLng(35.181446,136.906398);
addMarkerAtGeo("Cebu City Philippines");
addMarkerAtGeo("Tingo Maria Peru");
addMarkerAtGeo("Pulwama Town India");
addMarkerAtGeo("Mavinga Angola");
addMarkerAtGeo("Nyanga South Africa");
addMarkerAtGeo("Huantar Peru");
addMarkerAtGeo("Ban Mano Thailand");
addMarkerAtGeo("Andhra Pradesh State India");
addMarkerAtGeo("Famagusta Cyprus");
addMarkerAtGeo("Kurunegala Sri Lanka");
addMarkerAtGeo("Muradiye Turkey");
addMarkerAtGeo("Panacan Philippines");
addMarkerAtGeo("Khutsong South Africa");
addMarkerAtGeo("Vila da Graca Angola");
addMarkerAtGeo("Eastern Province Sri Lanka");
addMarkerAtGeo("Haldwani Town India");
addMarkerAtGeo("Las Vegas Colombia");
addMarkerAtGeo("Kampala Uganda");
addMarkerAtGeo("Harsha Shinna India");
addMarkerAtGeo("Hakkari Turkey");
addMarkerAtGeo("Roodepoort South Africa");
addMarkerAtGeo("Pervari township Turkey");
addMarkerAtGeo("Southeast Turkey Turkey");
addMarkerAtGeo("Chittagong Bangladesh");
addMarkerAtGeo("Near Derazlet Turkey");
addMarkerAtGeo("New Delhi India");
addMarkerAtGeo("Sitio Botong Philippines");
addMarkerAtGeo("Ferozepur India");
addMarkerAtGeo("faysalabad Pakistan");
addMarkerAtGeo("Tricomalee Sri Lanka");
addMarkerAtGeo("Callao Peru");
addMarkerAtGeo("Maloke Village India");
addMarkerAtGeo("Wesselton South Africa");
addMarkerAtGeo("Ayahuarcuna area Peru");
addMarkerAtGeo("Msimini South Africa");
addMarkerAtGeo("Gumaca Philippines");
addMarkerAtGeo("Aparri Philippines");
addMarkerAtGeo("Pulmoddai Sri Lanka");
addMarkerAtGeo("La Plata Argentina");
addMarkerAtGeo("Chillan Chile");
addMarkerAtGeo("Siirt Turkey");
addMarkerAtGeo("Penco Chile");
addMarkerAtGeo("Kattlehong Township South Africa");
addMarkerAtGeo("Samanthurai Sri Lanka");
addMarkerAtGeo("Thanthirimale Sri Lanka");
addMarkerAtGeo("San Vicente Philippines");
addMarkerAtGeo("General Santos Philippines");
addMarkerAtGeo("Vavuniya District Sri Lanka");
addMarkerAtGeo("Aceh Province Indonesia");
addMarkerAtGeo("Cizre District Turkey");
addMarkerAtGeo("Nunoa Peru");
addMarkerAtGeo("Cape Town South Africa");
addMarkerAtGeo("Dhadhoi India");
addMarkerAtGeo("Huanta Dept Peru");
addMarkerAtGeo("aparri Philippines");
addMarkerAtGeo("Southern Mozambique Mozambique");
addMarkerAtGeo("Assiut Egypt");
addMarkerAtGeo("Makilala Philippines");
addMarkerAtGeo("Turbo Colombia");
addMarkerAtGeo("Baytuniya West Bank and Gaza Strip");
addMarkerAtGeo("Valencia Colombia");
addMarkerAtGeo("Bocekli Turkey");
addMarkerAtGeo("Dereler Turkey");
addMarkerAtGeo("Florida South Africa");
addMarkerAtGeo("Malague, Aklan Philippines");
addMarkerAtGeo("Yeniyazi Turkey");
addMarkerAtGeo("South Lebanon Lebanon");
addMarkerAtGeo("al-Tira West Bank and Gaza Strip");
addMarkerAtGeo("Quebrada Honda Colombia");
addMarkerAtGeo("Antonio Raymondi Prov. Peru");
addMarkerAtGeo("Negros Oriental Prov. Philippines");
addMarkerAtGeo("Srinagar India");
addMarkerAtGeo("Wandawaduwa Sri Lanka");
addMarkerAtGeo("Nitzamin Israel");
addMarkerAtGeo("Panguna Papua New Guinea");
addMarkerAtGeo("Villa Alemana Chile");
addMarkerAtGeo("Samanthurai Dist. Sri Lanka");
addMarkerAtGeo("Huasta Peru");
addMarkerAtGeo("zinarag Philippines");
addMarkerAtGeo("Cerro de Pasco Peru");
addMarkerAtGeo("Kachduro India");
addMarkerAtGeo("Bogota Colombia");
addMarkerAtGeo("Doganli Karahasan Turkey");
addMarkerAtGeo("Los Pinos Colombia");
addMarkerAtGeo("San Luis Philippines");
addMarkerAtGeo("Tamil Nadu State India");
addMarkerAtGeo("Chanchamayo Prov. Peru");
addMarkerAtGeo("Mankulam Sri Lanka");
addMarkerAtGeo("Gajabapura Sri Lanka");
addMarkerAtGeo("Maquisapa Peru");
addMarkerAtGeo("Nusaybin District Turkey");
addMarkerAtGeo("Kutlu Village Turkey");
addMarkerAtGeo("Silopi Township Turkey");
addMarkerAtGeo("Bijini India");
addMarkerAtGeo("Rafat West Bank and Gaza Strip");
addMarkerAtGeo("Unknown Colombia");
addMarkerAtGeo("Morawera Sri Lanka");
addMarkerAtGeo("Besta Bawer Turkey");
addMarkerAtGeo("Makhu India");
addMarkerAtGeo("Cordoba Dept. Colombia");
addMarkerAtGeo("Hungouan Philippines");
addMarkerAtGeo("Bhatinda Dist. India");
addMarkerAtGeo("Tillo District Turkey");
addMarkerAtGeo("Windhoek Namibia");
addMarkerAtGeo("Mutata Colombia");
addMarkerAtGeo("Tarn Taran India");
addMarkerAtGeo("Unknown El Salvador");
addMarkerAtGeo("Phnom Penh Cambodia");
addMarkerAtGeo("Huamanccacca Peru");
addMarkerAtGeo("Malabon Philippines");
addMarkerAtGeo("Island View South Africa");
addMarkerAtGeo("Maljchhari Bangladesh");
addMarkerAtGeo("Kudat Malaysia");
addMarkerAtGeo("Kuala state Malaysia");
addMarkerAtGeo("Uige Angola");
addMarkerAtGeo("Huancavelica Peru");
addMarkerAtGeo("Villa Dominico Argentina");
addMarkerAtGeo("Majitua District India");
addMarkerAtGeo("Mogadishu Somalia");
addMarkerAtGeo("Kilor India");
addMarkerAtGeo("Canas Peru");
addMarkerAtGeo("Damkala India");
addMarkerAtGeo("Belgachi Colombia");
addMarkerAtGeo("Soyo Angola");
addMarkerAtGeo("Akcay Turkey");
addMarkerAtGeo("San Pedro de Cajas District Peru");
addMarkerAtGeo("El Tablon Colombia");
addMarkerAtGeo("Kitgum District Uganda");
addMarkerAtGeo("Narbal India");
addMarkerAtGeo("Berian Spain");
addMarkerAtGeo("North Central Anuradhapura Sri Lanka");
addMarkerAtGeo("Rosario Philippines");
addMarkerAtGeo("Shebaa Lebanon");
addMarkerAtGeo("Lohan Village India");
addMarkerAtGeo("Wan Ela Sri Lanka");
addMarkerAtGeo("Ikizkaya Turkey");
addMarkerAtGeo("Cabudare Venezuela");
addMarkerAtGeo("Canayan Philippines");
addMarkerAtGeo("Sanga India");
addMarkerAtGeo("Ramatlabama South Africa");
addMarkerAtGeo("Polonnaruwa Sri Lanka");
addMarkerAtGeo("Eastern Zambia Zambia");
addMarkerAtGeo("Lucena Philippines");
addMarkerAtGeo("Bulacan Philippines");
addMarkerAtGeo("Ayacucho Peru");
addMarkerAtGeo("Bidar India");
addMarkerAtGeo("Rio de Oro Colombia");
addMarkerAtGeo("Patiala District India");
addMarkerAtGeo("Addis Ababa Ethiopia");
addMarkerAtGeo("Juniyah Lebanon");
addMarkerAtGeo("Warangal India");
addMarkerAtGeo("Pizana Port Peru");
addMarkerAtGeo("Bengo Province Angola");
addMarkerAtGeo("Hyderabad India");
addMarkerAtGeo("Bahn Liberia");
addMarkerAtGeo("Candelaria Philippines");
addMarkerAtGeo("Hanjiwala Pattan India");
addMarkerAtGeo("Shahpur Jhajhan India");
addMarkerAtGeo("Batangas City Philippines");
addMarkerAtGeo("Kabul Afghanistan");
addMarkerAtGeo("Northwest Somalia Somalia");
addMarkerAtGeo("Rajoke India");
addMarkerAtGeo("Sorsogon Province Philippines");
addMarkerAtGeo("Luena Angola");
addMarkerAtGeo("Sergovia Colombia");
addMarkerAtGeo("Pinchapunco Peru");
addMarkerAtGeo("Kitgum Uganda");
addMarkerAtGeo("Andamarca Peru");
addMarkerAtGeo("Unknown Japan");
addMarkerAtGeo("Rishon Lezion Israel");
addMarkerAtGeo("Jagraun India");
addMarkerAtGeo("Albina Suriname");
addMarkerAtGeo("islamabad Pakistan");
addMarkerAtGeo("Keran Sri Lanka");
addMarkerAtGeo("Khairpur Pakistan");
addMarkerAtGeo("Hapao Philippines");
addMarkerAtGeo("Barranca Peru");
addMarkerAtGeo("Myawadi Myanmar");
addMarkerAtGeo("Tarapoto Peru");
addMarkerAtGeo("Valle del Cauca Colombia");
addMarkerAtGeo("Bie Province Angola");
addMarkerAtGeo("Kofkiran Turkey");
addMarkerAtGeo("Iligan City Philippines");
addMarkerAtGeo("Unknown Sri Lanka");
addMarkerAtGeo("Acomayo Peru");
addMarkerAtGeo("Cajamarca Peru");
addMarkerAtGeo("Sirnak District Turkey");
addMarkerAtGeo("Bello Antioquia Colombia");
addMarkerAtGeo("Kirkkuyu Turkey");
addMarkerAtGeo("between Toledo and Samore Colombia");
addMarkerAtGeo("La Serena Chile");
addMarkerAtGeo("Gurdaspur Dist. India");
addMarkerAtGeo("Cennetpinar Turkey");
addMarkerAtGeo("Guzares Turkey");
addMarkerAtGeo("Trunde India");
addMarkerAtGeo("hyderabad Pakistan");
addMarkerAtGeo("Hughada Egypt");
addMarkerAtGeo("Kortanis Turkey");
addMarkerAtGeo("Lahore Pakistan");
addMarkerAtGeo("Bellavista Peru");
addMarkerAtGeo("Bandarban District Bangladesh");
addMarkerAtGeo("Ain Siniya Israel");
addMarkerAtGeo("Tambo Peru");
addMarkerAtGeo("Soweto Township South Africa");
addMarkerAtGeo("Shahbaajpur India");
addMarkerAtGeo("rawalpindin Pakistan");
addMarkerAtGeo("Iribamba Peru");
addMarkerAtGeo("Caqueta Colombia");
addMarkerAtGeo("Qatzir Israel");
addMarkerAtGeo("Andhra Pradesh India");
addMarkerAtGeo("Mungo Suriname");
addMarkerAtGeo("Nimba County Liberia");
addMarkerAtGeo("Khajala India");
addMarkerAtGeo("Rio de Janeiro Brazil");
addMarkerAtGeo("Venecia Colombia");
addMarkerAtGeo("Gonpur India");
addMarkerAtGeo("Karaingar Sri Lanka");
addMarkerAtGeo("Tehran Iran");
addMarkerAtGeo("Khan Younis West Bank and Gaza Strip");
addMarkerAtGeo("Abasan West Bank and Gaza Strip");
addMarkerAtGeo("Apalit Philippines");
addMarkerAtGeo("Monaragala Sri Lanka");
addMarkerAtGeo("Balanga Senegal");
addMarkerAtGeo("Umagon Philippines");
addMarkerAtGeo("Ambato Ecuador");
addMarkerAtGeo("Kagiso Township South Africa");
addMarkerAtGeo("Amritsar City India");
addMarkerAtGeo("Miraflores Colombia");
addMarkerAtGeo("manila Philippines");
addMarkerAtGeo("Datu Piang Philippines");
addMarkerAtGeo("Panchhari Bangladesh");
addMarkerAtGeo("Ramallah West Bank and Gaza Strip");
addMarkerAtGeo("Iligan Philippines");
addMarkerAtGeo("El Castillo Colombia");
addMarkerAtGeo("Vosloorus South Africa");
addMarkerAtGeo("Eravur Sri Lanka");
addMarkerAtGeo("San Juan de Topara Peru");
addMarkerAtGeo("Boudiediete Senegal");
addMarkerAtGeo("Cagayan Philippines");
addMarkerAtGeo("Tandra India");
addMarkerAtGeo("Aguachita Colombia");
addMarkerAtGeo("Derahine Turkey");
addMarkerAtGeo("Langadu Bangladesh");
addMarkerAtGeo("Vista Alegre Peru");
addMarkerAtGeo("Batala City India");
addMarkerAtGeo("Chimbote Peru");
addMarkerAtGeo("Ziguinchor Senegal");
addMarkerAtGeo("Luanda Angola");
addMarkerAtGeo("Beira Mozambique");
addMarkerAtGeo("Bronkhorstpruit South Africa");
addMarkerAtGeo("Vega Larga Colombia");
addMarkerAtGeo("San Jose del Guaviari Colombia");
addMarkerAtGeo("Llanabamba-Andamarca Peru");
addMarkerAtGeo("Sidon Lebanon");
addMarkerAtGeo("Upi Philippines");
addMarkerAtGeo("Chincha Peru");
addMarkerAtGeo("Buenos Aires Argentina");
addMarkerAtGeo("lahore Pakistan");
addMarkerAtGeo("Davan Philippines");
addMarkerAtGeo("Londrina Brazil");
addMarkerAtGeo("Kattankudi Sri Lanka");
addMarkerAtGeo("Huasta District Peru");
addMarkerAtGeo("Uzumkiran Turkey");
addMarkerAtGeo("Swayimani South Africa");
addMarkerAtGeo("Unguia Colombia");
addMarkerAtGeo("Kotlarai India");
addMarkerAtGeo("Unknown Chile");
addMarkerAtGeo("Acchabal India");
addMarkerAtGeo("Sitamarhi India");
addMarkerAtGeo("Mutar Sri Lanka");
addMarkerAtGeo("Assira al-Shamaliya Israel");
addMarkerAtGeo("Benguela Angola");
addMarkerAtGeo("Punjab State India");
addMarkerAtGeo("Ortigal Dist. Peru");
addMarkerAtGeo("johannesburg South Africa");
addMarkerAtGeo("Nicosia Cyprus");
addMarkerAtGeo("Bogazkoy Turkey");
addMarkerAtGeo("Enrile Philippines");
addMarkerAtGeo("Nazirhat Bangladesh");
addMarkerAtGeo("Ciudadela Argentina");
addMarkerAtGeo("Cavca Dipt Colombia");
addMarkerAtGeo("Kalawanchikudi Sri Lanka");
addMarkerAtGeo("Sammanthurai Sri Lanka");
addMarkerAtGeo("Pagbilao Philippines");
addMarkerAtGeo("Jaflan India");
addMarkerAtGeo("not stated * Israel");
addMarkerAtGeo("Cario Egypt");
addMarkerAtGeo("Gaza West Bank and Gaza Strip");
addMarkerAtGeo("Antioquia Dept Colombia");
addMarkerAtGeo("Todarmal India");
addMarkerAtGeo("Pretoria South Africa");
addMarkerAtGeo("Nabilatuk Uganda");
addMarkerAtGeo("Aija Peru");
addMarkerAtGeo("Near Hedris Turkey");
addMarkerAtGeo("Upper Huallaga Valley Peru");
addMarkerAtGeo("Sao Paulo State Brazil");
addMarkerAtGeo("Caqueta Department Colombia");
addMarkerAtGeo("El Carmen Colombia");
addMarkerAtGeo("Jullundur India");
addMarkerAtGeo("Assam State India");
addMarkerAtGeo("Puerto Belgica Colombia");
addMarkerAtGeo("Akkaaraipattu Sri Lanka");
addMarkerAtGeo("Pueblo Nuevo Colombia");
addMarkerAtGeo("Ovecek Village Turkey");
addMarkerAtGeo("Apartado Colombia");
addMarkerAtGeo("North Cotabato Prov. Philippines");
addMarkerAtGeo("El Paso Colombia");
addMarkerAtGeo("Ica Peru");
addMarkerAtGeo("Barpeta India");
addMarkerAtGeo("Tanar Senegal");
addMarkerAtGeo("Sebaste Philippines");
addMarkerAtGeo("Llicllactambo Peru");
addMarkerAtGeo("Valdivia Chile");
addMarkerAtGeo("Kudurippu Sri Lanka");
addMarkerAtGeo("Ampara District Sri Lanka");
addMarkerAtGeo("Omerli Turkey");
addMarkerAtGeo("Kogiso South Africa");
addMarkerAtGeo("Jolo Philippines");
addMarkerAtGeo("Diyarbakir Turkey");
addMarkerAtGeo("Ampatuan Philippines");
addMarkerAtGeo("Gaziantep Province Turkey");
addMarkerAtGeo("Yurimaguas Peru");
addMarkerAtGeo("Larkana Pakistan");
addMarkerAtGeo("Siakot Pakistan");
addMarkerAtGeo("Chabal Village India");
addMarkerAtGeo("Piura Peru");
addMarkerAtGeo("Manjacaze Mozambique");
addMarkerAtGeo("Faridkot India");
addMarkerAtGeo("Sogamoso Colombia");
addMarkerAtGeo("Point Pedro Sri Lanka");
addMarkerAtGeo("Talcahuano Chile");
addMarkerAtGeo("Cabinda Province Angola");
addMarkerAtGeo("La Merced Peru");
addMarkerAtGeo("260 miles north Bogota Colombia");
addMarkerAtGeo("Ndandu village Uganda");
addMarkerAtGeo("Unknown Algeria");
addMarkerAtGeo("Hyderabad Pakistan");
addMarkerAtGeo("Elmagulu Village Turkey");
addMarkerAtGeo("Sofala Province Mozambique");
addMarkerAtGeo("Afobka Suriname");
addMarkerAtGeo("Dondo District Mozambique");
addMarkerAtGeo("Ray Kobo Province Ethiopia");
addMarkerAtGeo("Braamfontein South Africa");
addMarkerAtGeo("Periyakulam Sri Lanka");
addMarkerAtGeo("Umlazi South Africa");
addMarkerAtGeo("Panguila Angola");
addMarkerAtGeo("Herkel Turkey");
addMarkerAtGeo("Puerto Triunfo Colombia");
addMarkerAtGeo("Yala Province Thailand");
addMarkerAtGeo("Eastern Province Zambia");
addMarkerAtGeo("Quezon Province Philippines");
addMarkerAtGeo("Bangued Philippines");
addMarkerAtGeo("Jbarra City Ecuador");
addMarkerAtGeo("Hoshiapur India");
addMarkerAtGeo("Steadville South Africa");
addMarkerAtGeo("Unknown Spain");
addMarkerAtGeo("El Bagre Colombia");
addMarkerAtGeo("Riofrio Colombia");
addMarkerAtGeo("Chavinillo Peru");
addMarkerAtGeo("Neiva Colombia");
addMarkerAtGeo("Pila Town Philippines");
addMarkerAtGeo("Balaa West Bank and Gaza Strip");
addMarkerAtGeo("Vina de Mar Chile");
addMarkerAtGeo("Lanao de Norte Prov. Philippines");
addMarkerAtGeo("Jammu Kashmir State India");
addMarkerAtGeo("Florencia Colombia");
addMarkerAtGeo("Zamore Municipality Colombia");
addMarkerAtGeo("Cabanatuan City Philippines");
addMarkerAtGeo("Zoxrim Turkey");
addMarkerAtGeo("Moamba District Mozambique");
addMarkerAtGeo("Masahkane South Africa");
addMarkerAtGeo("Rashaya Foukhar * Lebanon");
addMarkerAtGeo("Vavuniyu Sri Lanka");
addMarkerAtGeo("Bombay India");
addMarkerAtGeo("El Callao Peru");
addMarkerAtGeo("Jericho West Bank and Gaza Strip");
addMarkerAtGeo("Chehata India");
addMarkerAtGeo("San Luis de Shauro Peru");
addMarkerAtGeo("Damminna Sri Lanka");
addMarkerAtGeo("Tiaong Philippines");
addMarkerAtGeo("muzaffarabad Pakistan");
addMarkerAtGeo("Moyobamba Peru");
addMarkerAtGeo("Bogazoren Turkey");
addMarkerAtGeo("Kwamashu Township South Africa");
addMarkerAtGeo("Patti Town India");
addMarkerAtGeo("La Oroya Peru");
addMarkerAtGeo("Near Sultan Sexmus Turkey");
addMarkerAtGeo("Louis Trichardt South Africa");
addMarkerAtGeo("Unknown Northern Ireland");
addMarkerAtGeo("Meadowlands South Africa");
addMarkerAtGeo("Guneycam Village Turkey");
addMarkerAtGeo("Amnaija Peru");
addMarkerAtGeo("Cartagena Colombia");
addMarkerAtGeo("Huambo Angola");
addMarkerAtGeo("Cordoba Dept Colombia");
addMarkerAtGeo("San Carlos City Philippines");
addMarkerAtGeo("Kalwamora India");
addMarkerAtGeo("Vavuniya Sri Lanka");
addMarkerAtGeo("Putumayo Intendency Colombia");
addMarkerAtGeo("Chupaca Peru");
addMarkerAtGeo("Chandigarh India");
addMarkerAtGeo("Cassoalala Angola");
addMarkerAtGeo("Junin Department Peru");
addMarkerAtGeo("Sharpeville South Africa");
addMarkerAtGeo("Ocana Colombia");
addMarkerAtGeo("Ye Myanmar");
addMarkerAtGeo("Ibtin Israel");
addMarkerAtGeo("Ulla Pasyalachena Sri Lanka");
addMarkerAtGeo("Ifugao Province Philippines");
addMarkerAtGeo("Near Ziguinchor Senegal");
addMarkerAtGeo("Rangamati Bangladesh");
addMarkerAtGeo("Gazankulu South Africa");
addMarkerAtGeo("Caldas Colombia");
addMarkerAtGeo("Hungduan Philippines");
addMarkerAtGeo("Concepcion El Salvador");
addMarkerAtGeo("Arequipa Peru");
addMarkerAtGeo("Yemisli Village Turkey");
addMarkerAtGeo("Tandoz Iran");
addMarkerAtGeo("Tikana India");
addMarkerAtGeo("Mantara Turkey");
addMarkerAtGeo("Kufr Naame Israel");
addMarkerAtGeo("Ein Gedi Israel");
addMarkerAtGeo("Sunan India");
addMarkerAtGeo("Kale Turkey");
addMarkerAtGeo("Near Cican Turkey");
addMarkerAtGeo("Johannesburg South Africa");
addMarkerAtGeo("Tripoli Lebanon");
addMarkerAtGeo("Ceylanpinar Turkey");
addMarkerAtGeo("Huancavelica Dept Peru");
addMarkerAtGeo("Barira Philippines");
addMarkerAtGeo("Khair India");
addMarkerAtGeo("Caglayan Village Turkey");
addMarkerAtGeo("Ingenio Peru");
addMarkerAtGeo("Concepcion Chile");
addMarkerAtGeo("Valparaiso Chile");
addMarkerAtGeo("al-Bireh West Bank and Gaza Strip");
addMarkerAtGeo("Pachas Peru");
addMarkerAtGeo("karachi Pakistan");
addMarkerAtGeo("Fayoum Egypt");
addMarkerAtGeo("Shweikeh Israel");
addMarkerAtGeo("Senoures Egypt");
addMarkerAtGeo("Sanagoran Peru");
addMarkerAtGeo("Kemerli Turkey");
addMarkerAtGeo("MIndanao Island Philippines");
addMarkerAtGeo("Mamelodi Township South Africa");
addMarkerAtGeo("Caballito District Argentina");
addMarkerAtGeo("Degerlikoy Turkey");
addMarkerAtGeo("Dalwani Bhai India");
addMarkerAtGeo("Gesher Israel");
addMarkerAtGeo("Alekan Turkey");
addMarkerAtGeo("Khayelitsha South Africa");
addMarkerAtGeo("Chuschi Peru");
addMarkerAtGeo("Beytussebap Turkey");
addMarkerAtGeo("Unknown South Africa");
addMarkerAtGeo("Nawashah Pakistan");
addMarkerAtGeo("Chaheru India");
addMarkerAtGeo("Bethlehem West Bank and Gaza Strip");
addMarkerAtGeo("Chinavane Mozambique");
addMarkerAtGeo("Tangub City Philippines");
addMarkerAtGeo("Dwengu Township South Africa");
addMarkerAtGeo("Las Condes Chile");
addMarkerAtGeo("Popayan Colombia");
addMarkerAtGeo("Kandy District Sri Lanka");
addMarkerAtGeo("Near Orakoy Turkey");
addMarkerAtGeo("New Hanover South Africa");
addMarkerAtGeo("Nuevo Progresso Peru");
addMarkerAtGeo("Near Gundekevir Turkey");
addMarkerAtGeo("La Perfecta Nicaragua");
addMarkerAtGeo("Urchiza Peru");
addMarkerAtGeo("Bansalan Philippines");
addMarkerAtGeo("Tammane Elawaka Sri Lanka");
addMarkerAtGeo("Bnashi Lebanon");
addMarkerAtGeo("Santa Maria Baja Dist Peru");
addMarkerAtGeo("Siyanbalangoda Sri Lanka");
addMarkerAtGeo("Sammanturai Sri Lanka");
addMarkerAtGeo("Qazigunj Township India");
addMarkerAtGeo("Diyandin Region Turkey");
addMarkerAtGeo("Natal South Africa");
addMarkerAtGeo("Orion Town Philippines");
addMarkerAtGeo("Cabanatuan Philippines");
addMarkerAtGeo("Guachicono Colombia");
addMarkerAtGeo("Calcutta India");
addMarkerAtGeo("Amman Jordan");
addMarkerAtGeo("Sanjandi Colombia");
addMarkerAtGeo("Qazi Kund India");
addMarkerAtGeo("Rizal Philippines");
addMarkerAtGeo("Kukrichhari Town Bangladesh");
addMarkerAtGeo("Jambalo Colombia");
addMarkerAtGeo("Barera Philippines");
addMarkerAtGeo("Porto Velho Brazil");
addMarkerAtGeo("General santos city Philippines");
addMarkerAtGeo("El Salvador Town Philippines");
addMarkerAtGeo("Arboletes Colombia");
addMarkerAtGeo("Imbali South Africa");
addMarkerAtGeo("Dera Baba Nanek India");
addMarkerAtGeo("Bogota, apparently Colombia");
addMarkerAtGeo("Ntuzuma South Africa");
addMarkerAtGeo("Unknown Israel");
addMarkerAtGeo("Manchente Peru");
addMarkerAtGeo("Tate Turkey");
addMarkerAtGeo("Sartah Israel");
addMarkerAtGeo("Palali Sri Lanka");
addMarkerAtGeo("Pervari Turkey");
addMarkerAtGeo("Yumbo Colombia");
addMarkerAtGeo("San Nicolas Philippines");
addMarkerAtGeo("Venda Angola");
addMarkerAtGeo("Nintavur Sri Lanka");
addMarkerAtGeo("Nailam-Sonomoro Peru");
addMarkerAtGeo("Tenta Res Turkey");
addMarkerAtGeo("Randburg South Africa");
addMarkerAtGeo("Bitlis Turkey");
addMarkerAtGeo("Khan Yunis West Bank and Gaza Strip");
addMarkerAtGeo("Kangan India");
addMarkerAtGeo("Peruwelatalawa Sri Lanka");
addMarkerAtGeo("Masma Peru");
addMarkerAtGeo("Kalinga-Apayao Philippines");
addMarkerAtGeo("Tulua Colombia");
addMarkerAtGeo("Harding South Africa");
addMarkerAtGeo("Zilan Turkey");
addMarkerAtGeo("Judaydat Ghazir Lebanon");
addMarkerAtGeo("Igbaras Town Philippines");
addMarkerAtGeo("Jabalya West Bank and Gaza Strip");
addMarkerAtGeo("Corcancha Peru");
addMarkerAtGeo("Huaraz Peru");
addMarkerAtGeo("Murki India");
addMarkerAtGeo("Suriyatenne Sri Lanka");
addMarkerAtGeo("Vientiane Laos");
addMarkerAtGeo("Broummana Lebanon");
addMarkerAtGeo("Petah Tiqva Israel");
addMarkerAtGeo("Carltonville South Africa");
addMarkerAtGeo("Narli Turkey");
addMarkerAtGeo("Progreso Peru");
addMarkerAtGeo("Magabheni South Africa");
addMarkerAtGeo("Ortulu Turkey");
addMarkerAtGeo("Menaka Mali");
addMarkerAtGeo("Bukardi Turkey");
addMarkerAtGeo("Buchwind Village India");
addMarkerAtGeo("Pericohuayco area Peru");
addMarkerAtGeo("Casapaica Peru");
addMarkerAtGeo("Batala Police District India");
addMarkerAtGeo("Batticaloa Dist. Sri Lanka");
addMarkerAtGeo("Puerto Rico Colombia");
addMarkerAtGeo("Maclear South Africa");
addMarkerAtGeo("Uva Province Sri Lanka");
addMarkerAtGeo("Temuco Chile");
addMarkerAtGeo("Ghazeyeh Lebanon");
addMarkerAtGeo("Ayachcho Peru");
addMarkerAtGeo("Cagayan de Oro Philippines");
addMarkerAtGeo("Movene Mozambique");
addMarkerAtGeo("Catak-Pervari-Beytussebap area Turkey");
addMarkerAtGeo("Alindamadu Sri Lanka");
addMarkerAtGeo("Puerto Inirida Colombia");
addMarkerAtGeo("Angeles City Philippines");
addMarkerAtGeo("Nueva Ecija Province Philippines");
addMarkerAtGeo("Mpumalanga South Africa");
addMarkerAtGeo("Alongo Camp Angola");
addMarkerAtGeo("Davao City Philippines");
addMarkerAtGeo("Amparai district Sri Lanka");
addMarkerAtGeo("Kansla India");
addMarkerAtGeo("La Paz Bolivia");
addMarkerAtGeo("Kathua District India");
addMarkerAtGeo("Lira District Uganda");
addMarkerAtGeo("Veeracholai Sri Lanka");
addMarkerAtGeo("Kapatagan Philippines");
addMarkerAtGeo("Joaquim Nabuco Brazil");
addMarkerAtGeo("Morawewa Sri Lanka");
addMarkerAtGeo("Nablus West Bank and Gaza Strip");
addMarkerAtGeo("Kurtalan Tunisia");
addMarkerAtGeo("Abohar India");
addMarkerAtGeo("El Recverdo Colombia");
addMarkerAtGeo("Timbio Colombia");
addMarkerAtGeo("Pichanaki Peru");
addMarkerAtGeo("gujrat Pakistan");
addMarkerAtGeo("Cali Colombia");
addMarkerAtGeo("Targadh India");
addMarkerAtGeo("Kayaonu Turkey");
addMarkerAtGeo("Vilcashuaman Peru");
addMarkerAtGeo("Umkomaas South Africa");
addMarkerAtGeo("Capenda Camulemba Angola");
addMarkerAtGeo("San Calixto Colombia");
addMarkerAtGeo("Maokeng South Africa");
addMarkerAtGeo("Jhandoke India");
addMarkerAtGeo("Thembelihle South Africa");
addMarkerAtGeo("La Ley de Dios Colombia");
addMarkerAtGeo("Mazidagi Turkey");
addMarkerAtGeo("Cibiltine Turkey");
addMarkerAtGeo("La Pedrera El Salvador");
addMarkerAtGeo("Jatt Israel");
addMarkerAtGeo("Iran Village Turkey");
addMarkerAtGeo("Tembisa South Africa");
addMarkerAtGeo("Jaiyus village West Bank and Gaza Strip");
addMarkerAtGeo("Ganta Liberia");
addMarkerAtGeo("Sirnak Turkey");
addMarkerAtGeo("Baguio Philippines");
addMarkerAtGeo("Montelibano Colombia");
addMarkerAtGeo("Arboledas Colombia");
addMarkerAtGeo("Butuan Philippines");
addMarkerAtGeo("Langa South Africa");
addMarkerAtGeo("Barsala town India");
addMarkerAtGeo("Naria Bangladesh");
addMarkerAtGeo("Pacaicasa Dist. Peru");
addMarkerAtGeo("Vallevedi Sri Lanka");
addMarkerAtGeo("Peshawar Afghanistan");
addMarkerAtGeo("Nahajia India");
addMarkerAtGeo("floridablance Philippines");
addMarkerAtGeo("town unk Israel");
addMarkerAtGeo("Betulia Colombia");
addMarkerAtGeo("Montevideo Uruguay");
addMarkerAtGeo("Eibad Israel");
addMarkerAtGeo("Cotabato City Philippines");
addMarkerAtGeo("El Retiro Colombia");
addMarkerAtGeo("Roumieh Lebanon");
addMarkerAtGeo("Mdantsane Township South Africa");
addMarkerAtGeo("Valachchenai Sri Lanka");
addMarkerAtGeo("Cizre Turkey");
addMarkerAtGeo("Qena Governorate Egypt");
addMarkerAtGeo("Sassa Zau Angola");
addMarkerAtGeo("Andahuaylas Peru");
addMarkerAtGeo("Mandaitiu Island Sri Lanka");
addMarkerAtGeo("Djibouti Djibouti");
addMarkerAtGeo("Gujarat India");
addMarkerAtGeo("Banawan Philippines");
addMarkerAtGeo("Zapatosa Lake Colombia");
addMarkerAtGeo("Davao del Norte Prov. Philippines");
addMarkerAtGeo("Gedik Turkey");
addMarkerAtGeo("Munsieville South Africa");
addMarkerAtGeo("Vilcashuman Peru");
addMarkerAtGeo("Karachi Pakistan");
addMarkerAtGeo("Huamancaca Chico Peru");
addMarkerAtGeo("Kikone Village Uganda");
addMarkerAtGeo("Beersheba Israel");
addMarkerAtGeo("Chenkalady Sri Lanka");
addMarkerAtGeo("Portugal Colombia");
addMarkerAtGeo("Wahalkade Sri Lanka");
addMarkerAtGeo("Simaluguri India");
addMarkerAtGeo("Batamalu India");
addMarkerAtGeo("Dule Turkey");
addMarkerAtGeo("Tulkarm West Bank and Gaza Strip");
addMarkerAtGeo("Hakkari Province Turkey");
addMarkerAtGeo("Santiago Chile");
addMarkerAtGeo("Cavite Province Philippines");
addMarkerAtGeo("Itagui Colombia");
addMarkerAtGeo("Namaacha Mozambique");
addMarkerAtGeo("Dalwandi Bhai India");
addMarkerAtGeo("Carhuanca Peru");
addMarkerAtGeo("Bandar Abbas Iran");
addMarkerAtGeo("Secceslambra Peru");
addMarkerAtGeo("Mallidi Sri Lanka");
addMarkerAtGeo("Yukaridamlipinar Turkey");
addMarkerAtGeo("Kot Inayatullah Khan Pakistan");
addMarkerAtGeo("Panligam India");
addMarkerAtGeo("Beit Furik West Bank and Gaza Strip");
addMarkerAtGeo("Palampur Village India");
addMarkerAtGeo("Guinhulngan Philippines");
addMarkerAtGeo("Huanoayo Peru");
addMarkerAtGeo("Polatdere Turkey");
addMarkerAtGeo("Ressano Garcia Mozambique");
addMarkerAtGeo("Ciudad Bolivar Colombia");
addMarkerAtGeo("Gweru Zimbabwe");
addMarkerAtGeo("Sapore India");
addMarkerAtGeo("Myitkyina Myanmar");
addMarkerAtGeo("Goa Philippines");
addMarkerAtGeo("Abasah West Bank and Gaza Strip");
addMarkerAtGeo("Yukarigungoren Turkey");
addMarkerAtGeo("Bunawan Town Philippines");
addMarkerAtGeo("San Martin de Pangoa Peru");
addMarkerAtGeo("Serefhan Turkey");
addMarkerAtGeo("Cagayan Province Philippines");
addMarkerAtGeo("Gurdaspur District India");
addMarkerAtGeo("Huascahuru Peru");
addMarkerAtGeo("Capas Philippines");
addMarkerAtGeo("Blida Algeria");
addMarkerAtGeo("Zawtar ash-Sharqiyeh Lebanon");
addMarkerAtGeo("Nawimpuquio Peru");
addMarkerAtGeo("Batticaloa Dist Sri Lanka");
addMarkerAtGeo("Valvettiturai Sri Lanka");
addMarkerAtGeo("Jaffna area Sri Lanka");
addMarkerAtGeo("Chosica Peru");
addMarkerAtGeo("Gaza area West Bank and Gaza Strip");
addMarkerAtGeo("Harare Zimbabwe");
addMarkerAtGeo("Pannairuppukurdy Sri Lanka");
addMarkerAtGeo("Houmine al Faouqa Lebanon");
addMarkerAtGeo("Matanug Philippines");
addMarkerAtGeo("Garcia Rovira Colombia");
addMarkerAtGeo("Titlacayan Peru");
addMarkerAtGeo("Vina del Mar Chile");
addMarkerAtGeo("Ixacamal Guatemala");
addMarkerAtGeo("Airum Pirili Soviet Union");
addMarkerAtGeo("Wahabpura India");
addMarkerAtGeo("Pueblo Nuevo Peru");
addMarkerAtGeo("Corinto Colombia");
addMarkerAtGeo("Drusu India");
addMarkerAtGeo("Andulo Angola");
addMarkerAtGeo("Near Hesko Turkey");
addMarkerAtGeo("Media Luna Colombia");
addMarkerAtGeo("Mullaitivu Sri Lanka");
addMarkerAtGeo("El Sepa Peru");
addMarkerAtGeo("Kwamashu South Africa");
addMarkerAtGeo("Kokluce Village Turkey");
addMarkerAtGeo("Kempton Park South Africa");
addMarkerAtGeo("Cotaboto City Philippines");
addMarkerAtGeo("Maynay Peru");
addMarkerAtGeo("Akkaraipattu Sri Lanka");
addMarkerAtGeo("Nueva Ecija Philippines");
addMarkerAtGeo("La Gomez Colombia");
addMarkerAtGeo("Ayacucho Dept. Peru");
addMarkerAtGeo("Chepen Peru");
addMarkerAtGeo("Mahaduwuleva Trincomalee District Sri Lanka");
addMarkerAtGeo("Ngora Uganda");
addMarkerAtGeo("Pathankot India");
addMarkerAtGeo("Beit Israel");
addMarkerAtGeo("Satipo Peru");
addMarkerAtGeo("Bihar India");
addMarkerAtGeo("Beit Safara Israel");
addMarkerAtGeo("Palo, Leyete Island Philippines");
addMarkerAtGeo("Trincomalee District Sri Lanka");
addMarkerAtGeo("Subic Bay Naval Station Philippines");
addMarkerAtGeo("Claypole Argentina");
addMarkerAtGeo("Pudukudyiruppu Sri Lanka");
addMarkerAtGeo("Nationwide* El Salvador");
addMarkerAtGeo("turbat Pakistan");
addMarkerAtGeo("Chittagong Hills Bangladesh");
addMarkerAtGeo("Kokstad South Africa");
addMarkerAtGeo("Murica Philippines");
addMarkerAtGeo("Amritsar District India");
addMarkerAtGeo("Near Malatya Turkey");
addMarkerAtGeo("Bandaraduwa Sri Lanka");
addMarkerAtGeo("Sikwame Village Botswana");
addMarkerAtGeo("Infanta Philippines");
addMarkerAtGeo("Boutout District Senegal");
addMarkerAtGeo("Iquinota Bolivia");
addMarkerAtGeo("Kiangan Philippines");
addMarkerAtGeo("Tailaimannar Sri Lanka");
addMarkerAtGeo("Ankara Turkey");
addMarkerAtGeo("Jaffna Sri Lanka");
addMarkerAtGeo("Port Beira Zimbabwe");
addMarkerAtGeo("Davao Philippines");
addMarkerAtGeo("Bangkok Thailand");
addMarkerAtGeo("Huacho Peru");
addMarkerAtGeo("Khardali Lebanon");
addMarkerAtGeo("Culebras Peru");
addMarkerAtGeo("Sanchez Mira Philippines");
addMarkerAtGeo("Bloemfontein South Africa");
addMarkerAtGeo("Xirbekan Turkey");
addMarkerAtGeo("Yabad West Bank and Gaza Strip");
addMarkerAtGeo("Ovecek Turkey");
addMarkerAtGeo("Las Cordobas Colombia");
addMarkerAtGeo("Kupwara District India");
addMarkerAtGeo("Near Osyan Tunisia");
addMarkerAtGeo("Maigo Philippines");
addMarkerAtGeo("Abrego Colombia");
addMarkerAtGeo("Beirut Lebanon");
addMarkerAtGeo("Soweto South Africa");
addMarkerAtGeo("Siberia Colombia");
addMarkerAtGeo("Batticaloa Dostrict Sri Lanka");
addMarkerAtGeo("Pikit Town Philippines");
addMarkerAtGeo("Ashdod Israel");
addMarkerAtGeo("Hacari Colombia");
addMarkerAtGeo("Sadd al-Bawshariyah Lebanon");
addMarkerAtGeo("Yenisu Town Turkey");
addMarkerAtGeo("Delhi India");
addMarkerAtGeo("Bhunduwalla India");
addMarkerAtGeo("Niagisse Senegal");
addMarkerAtGeo("Valtoha India");
addMarkerAtGeo("Mathura India");
addMarkerAtGeo("Sumbal India");
addMarkerAtGeo("Palcamayo Peru");
addMarkerAtGeo("Laoag Philippines");
addMarkerAtGeo("Guneycam Turkey");
addMarkerAtGeo("Carmen de Atrato Colombia");
addMarkerAtGeo("Nawagamuwa Sri Lanka");
addMarkerAtGeo("Tetetes Ecuador");
addMarkerAtGeo("Warangal District India");
addMarkerAtGeo("Malanje Angola");
addMarkerAtGeo("Hyderbad Pakistan");
addMarkerAtGeo("Dibe Turkey");
addMarkerAtGeo("Kalawanchikudy Sri Lanka");
addMarkerAtGeo("Abu-Ghawsh Israel");
addMarkerAtGeo("Ermita Philippines");
addMarkerAtGeo("Uludere Twonship Turkey");
addMarkerAtGeo("Himmeh Israel");
addMarkerAtGeo("Kayapa Philippines");
addMarkerAtGeo("Miranda Colombia");
addMarkerAtGeo("Pucara District Peru");
addMarkerAtGeo("Bismil Turkey");
addMarkerAtGeo("Mukhivand India");
addMarkerAtGeo("Rangiya India");
addMarkerAtGeo("Cajabamba Province Peru");
addMarkerAtGeo("Near Ernabat Turkey");
addMarkerAtGeo("Quezon City Philippines");
addMarkerAtGeo("Istanbul Turkey");
addMarkerAtGeo("Ahmadgarh India");
addMarkerAtGeo("Gomez Plata Colombia");
addMarkerAtGeo("Maradodon Philippines");
addMarkerAtGeo("Barranco de Loba Colombia");
addMarkerAtGeo("Orurillo Peru");
addMarkerAtGeo("Kifangondo Angola");
addMarkerAtGeo("Tocache Peru");
addMarkerAtGeo("Assam Sttate India");
addMarkerAtGeo("Podankudu Sri Lanka");
addMarkerAtGeo("Kathankudy Sri Lanka");
addMarkerAtGeo("Tibu Colombia");
addMarkerAtGeo("Tunja Colombia");
addMarkerAtGeo("La Cuchilla Colombia");
addMarkerAtGeo("Caluza South Africa");
addMarkerAtGeo("Mannar district Sri Lanka");
addMarkerAtGeo("Siniria West Bank and Gaza Strip");
addMarkerAtGeo("Picota Peru");
addMarkerAtGeo("North Cypress Cyprus");
addMarkerAtGeo("Finca San Isidro Guatemala");
addMarkerAtGeo("Bulbul Turkey");
addMarkerAtGeo("Georgetown Guyana");
addMarkerAtGeo("Nabilatuk * Uganda");
addMarkerAtGeo("Corpanqui Peru");
addMarkerAtGeo("Welkom South Africa");
addMarkerAtGeo("Davao del Sur Prov. Philippines");
addMarkerAtGeo("Agri Turkey");
addMarkerAtGeo("Nechi Colombia");
addMarkerAtGeo("Rangamati Dist. Bangladesh");
addMarkerAtGeo("Asagiaratan Turkey");
addMarkerAtGeo("Sardasht Iran");
addMarkerAtGeo("Adana Turkey");
addMarkerAtGeo("Sepore India");
addMarkerAtGeo("Alwi Uganda");
addMarkerAtGeo("Buenaventura Colombia");
addMarkerAtGeo("Cairo Egypt");
addMarkerAtGeo("Maaroub Lebanon");
addMarkerAtGeo("Zamboanga Philippines");
addMarkerAtGeo("Choras Peru");
addMarkerAtGeo("Southern Colombia Colombia");
addMarkerAtGeo("Sitio Lumaid, Davao Philippines");
addMarkerAtGeo("Gugulethu township South Africa");
addMarkerAtGeo("Patia Colombia");
addMarkerAtGeo("Mannar District Sri Lanka");
addMarkerAtGeo("Valenzuela Philippines");
addMarkerAtGeo("Ortulu Village Turkey");
addMarkerAtGeo("Ilocos Norte Philippines");
addMarkerAtGeo("Huaylas Peru");
addMarkerAtGeo("Jerusalem Israel");
addMarkerAtGeo("Jaba Israel");
addMarkerAtGeo("East London South Africa");
addMarkerAtGeo("samar island Philippines");
addMarkerAtGeo("Cochamarca Peru");
addMarkerAtGeo("Ondachimaden Sri Lanka");
addMarkerAtGeo("Gurdaspur India");
addMarkerAtGeo("San Martin Dept Peru");
addMarkerAtGeo("Pamnanna Philippines");
addMarkerAtGeo("Pishupiaco Peru");
addMarkerAtGeo("Petah Tiova Israel");
addMarkerAtGeo("Gaza Province Mozambique");
addMarkerAtGeo("Cesar Dept Colombia");
addMarkerAtGeo("Butta India");
addMarkerAtGeo("Tocota Peru");
addMarkerAtGeo("Thinganyinaung Myanmar");
addMarkerAtGeo("Batikarakoc Turkey");
addMarkerAtGeo("Hablah Israel");
addMarkerAtGeo("Pointe Noire Angola");
addMarkerAtGeo("Palmitos Colombia");
addMarkerAtGeo("Campina Peru");
addMarkerAtGeo("Huamanga Peru");
addMarkerAtGeo("Sirnak Province Turkey");
addMarkerAtGeo("Ghaziyeh Lebanon");
addMarkerAtGeo("Santa Rosa Colombia");
addMarkerAtGeo("Fattawala India");
addMarkerAtGeo("Near Tinate Turkey");
addMarkerAtGeo("Chigorodo Colombia");
addMarkerAtGeo("Barangay Sucodan Philippines");
addMarkerAtGeo("quezon city Philippines");
addMarkerAtGeo("Fatahpur India");
addMarkerAtGeo("San Anton Peru");
addMarkerAtGeo("Kurukshetra India");
addMarkerAtGeo("Amritsar India");
addMarkerAtGeo("Almeida Colombia");
addMarkerAtGeo("Cala Guze Turkey");
addMarkerAtGeo("Chilca Peru");
addMarkerAtGeo("Tauramena Colombia");
addMarkerAtGeo("Davao Province Philippines");
addMarkerAtGeo("Guajira Province Colombia");
addMarkerAtGeo("Paddock South Africa");
addMarkerAtGeo("Baskale Township Turkey");
addMarkerAtGeo("peshawar Pakistan");
addMarkerAtGeo("Kutubchhari Bangladesh");
addMarkerAtGeo("Panabao Philippines");
addMarkerAtGeo("Talca Chile");
addMarkerAtGeo("Srinigar India");
addMarkerAtGeo("San Ramon Peru");
addMarkerAtGeo("Kyrenia Cyprus");
addMarkerAtGeo("Sopore India");
addMarkerAtGeo("Aguachica Colombia");
addMarkerAtGeo("Puerto narino Colombia");
addMarkerAtGeo("Barrancabermeja Colombia");
addMarkerAtGeo("Quezon city Philippines");
addMarkerAtGeo("Central Andes Area Peru");
addMarkerAtGeo("Carmen Colombia");
addMarkerAtGeo("Panabo Philippines");
addMarkerAtGeo("Churchak India");
addMarkerAtGeo("Tarma Peru");
addMarkerAtGeo("Zamboanga del Sur Province Philippines");
addMarkerAtGeo("Beit Sahour Israel");
addMarkerAtGeo("Zamboanga City Philippines");
addMarkerAtGeo("Gahnpa Liberia");
addMarkerAtGeo("Silos Colombia");
addMarkerAtGeo("Punchanur Sri Lanka");
addMarkerAtGeo("Olmos Peru");
addMarkerAtGeo("Loja Ecuador");
addMarkerAtGeo("County Tyrone Northern Ireland");
addMarkerAtGeo("Al-Minya Egypt");
addMarkerAtGeo("Amritsan India");
addMarkerAtGeo("Jalandhar India");
addMarkerAtGeo("South Sri Lanka Sri Lanka");
addMarkerAtGeo("Nagaland State India");
addMarkerAtGeo("Irine Village Turkey");
addMarkerAtGeo("General Natividad Philippines");
addMarkerAtGeo("Coihaique Chile");
addMarkerAtGeo("East of Medellin Colombia");
addMarkerAtGeo("Sincelejo Colombia");
addMarkerAtGeo("Savur area Turkey");
addMarkerAtGeo("Wazirabad Pakistan");
addMarkerAtGeo("Banare Colombia");
addMarkerAtGeo("Qazvin Iran");
addMarkerAtGeo("Amritsar Dist. India");
addMarkerAtGeo("Mae Sot Thailand");
addMarkerAtGeo("Caya Peru");
addMarkerAtGeo("San Juan de Jatunhaus Peru");
addMarkerAtGeo("Malay Town Philippines");
addMarkerAtGeo("Gerdi area Turkey");
addMarkerAtGeo("La Mar Province Peru");
addMarkerAtGeo("Kolokolo South Africa");
addMarkerAtGeo("Tacria Peru");
addMarkerAtGeo("Arc Village Turkey");
addMarkerAtGeo("Malakal Sudan");
addMarkerAtGeo("Quillota Chile");
addMarkerAtGeo("Barranquilla Colombia");
addMarkerAtGeo("jhang Pakistan");
addMarkerAtGeo("San Marcos Peru");
addMarkerAtGeo("Near Bykan Turkey");
addMarkerAtGeo("Ica Department Peru");
addMarkerAtGeo("Manchol Sri Lanka");
addMarkerAtGeo("Dubli India");
addMarkerAtGeo("Ganderbal India");
addMarkerAtGeo("Rao Soh Thailand");
addMarkerAtGeo("Paraisn Peru");
addMarkerAtGeo("Kundapokuna Mahaweli Sri Lanka");
addMarkerAtGeo("Southern Thailand Thailand");
addMarkerAtGeo("Alamada Philippines");
addMarkerAtGeo("Jamaleh Israel");
addMarkerAtGeo("Near Eynkaf Turkey");
addMarkerAtGeo("Idil Township Turkey");
addMarkerAtGeo("Tulkarm Refugee Camp West Bank and Gaza Strip");
addMarkerAtGeo("Near Tarlac Philippines");
addMarkerAtGeo("Omarim West Bank and Gaza Strip");
addMarkerAtGeo("Ruriwala India");
addMarkerAtGeo("Bherwar India");
addMarkerAtGeo("Janin West Bank and Gaza Strip");
addMarkerAtGeo("West Bank West Bank and Gaza Strip");
addMarkerAtGeo("Moron Argentina");
addMarkerAtGeo("Baramulla India");
addMarkerAtGeo("Munhango Angola");
addMarkerAtGeo("kot khizri Pakistan");
addMarkerAtGeo("Ropar District India");
addMarkerAtGeo("Gaza City West Bank and Gaza Strip");
addMarkerAtGeo("Bajo Calima Colombia");
addMarkerAtGeo("Nazareth Israel");
addMarkerAtGeo("Vosloorus Township South Africa");
addMarkerAtGeo("Haifa Israel");
addMarkerAtGeo("Luanda Province Angola");
addMarkerAtGeo("Dugunculer Turkey");
addMarkerAtGeo("Gauhati India");
addMarkerAtGeo("Awas Uganda");
addMarkerAtGeo("Bijbehara India");
addMarkerAtGeo("Dondo Angola");
addMarkerAtGeo("Acos Vinchos Peru");
addMarkerAtGeo("Kirlangic Village Turkey");
addMarkerAtGeo("Buenos AIres Argentina");
addMarkerAtGeo("Puente de Pierda Peru");
addMarkerAtGeo("Botshabelo South Africa");
addMarkerAtGeo("Thohoyandou Venda South Africa");
addMarkerAtGeo("Puerto Boyaca Colombia");
addMarkerAtGeo("Omogolo Village Uganda");
addMarkerAtGeo("Libbaya Lebanon");
addMarkerAtGeo("Ovacik Township Turkey");
addMarkerAtGeo("Patag Philippines");
addMarkerAtGeo("Ciftlikai Turkey");
addMarkerAtGeo("Cochabamba Bolivia");
addMarkerAtGeo("Khan Yunus West Bank and Gaza Strip");
addMarkerAtGeo("Maputo Mozambique");
addMarkerAtGeo("General Santos City Philippines");
addMarkerAtGeo("Peshawar Pakistan");
addMarkerAtGeo("Umlazi Township South Africa");
addMarkerAtGeo("Kwadabeka * South Africa");
addMarkerAtGeo("Asmera Ethiopia");
addMarkerAtGeo("Suveren Turkey");
addMarkerAtGeo("Las Juntas Colombia");
addMarkerAtGeo("Cape town South Africa");
addMarkerAtGeo("Beit Ummar West Bank and Gaza Strip");
addMarkerAtGeo("Zahedan Iran");
addMarkerAtGeo("Boalkhali Bangladesh");
addMarkerAtGeo("Valledupar Colombia");
addMarkerAtGeo("City not shown Colombia");
addMarkerAtGeo("Trincomalee Sri Lanka");
addMarkerAtGeo("Beit Hanina West Bank and Gaza Strip");
addMarkerAtGeo("Bellavista Colombia");
addMarkerAtGeo("Botleng South Africa");
addMarkerAtGeo("Ludhiana India");
addMarkerAtGeo("Hebron West Bank and Gaza Strip");
addMarkerAtGeo("Medellin Colombia");
addMarkerAtGeo("Nampula Province Mozambique");
addMarkerAtGeo("Caqueta Dept Colombia");
addMarkerAtGeo("Inchope Mozambique");
addMarkerAtGeo("Jabaliya West Bank and Gaza Strip");
addMarkerAtGeo("Kalahari South Africa");
addMarkerAtGeo("Muliyankadu Sri Lanka");
addMarkerAtGeo("Silat al-Harithiya Israel");
addMarkerAtGeo("Mamelodi South Africa");
addMarkerAtGeo("Mirjatilla Bangladesh");
addMarkerAtGeo("Cubara Colombia");
addMarkerAtGeo("Badgam District India");
addMarkerAtGeo("Cusco Peru");
addMarkerAtGeo("La Primavera Colombia");
addMarkerAtGeo("Ferozepore Dist India");
addMarkerAtGeo("Chandrapurna India");
addMarkerAtGeo("Ferozepur District India");
addMarkerAtGeo("Beit Hanoun Israel");
addMarkerAtGeo("muridke Pakistan");
addMarkerAtGeo("Cukurca Township Turkey");
addMarkerAtGeo("Rasht Iran");
addMarkerAtGeo("Dinaig Philippines");
addMarkerAtGeo("Azangaro Peru");
addMarkerAtGeo("Davao city Philippines");
addMarkerAtGeo("Lima Peru");
addMarkerAtGeo("Buldon Philippines");
addMarkerAtGeo("Quito Ecuador");
addMarkerAtGeo("Bucaramanga Colombia");
addMarkerAtGeo("Karmuwal India");
addMarkerAtGeo("Gole Turkey");
addMarkerAtGeo("Kiran Sri Lanka");
addMarkerAtGeo("Necocli Colombia");
addMarkerAtGeo("Mulotana Mozambique");
addMarkerAtGeo("Pampas Peru");
addMarkerAtGeo("Manijla Philippines");
addMarkerAtGeo("Dispur India");
addMarkerAtGeo("Galle District Sri Lanka");
addMarkerAtGeo("Not Stated India");
addMarkerAtGeo("Santiago de Chuco Province Peru");
addMarkerAtGeo("Los Encuentros El Salvador");
addMarkerAtGeo("Lubban as-Sharkiyah West Bank and Gaza Strip");
addMarkerAtGeo("Pueblo Bello Colombia");
addMarkerAtGeo("Kupwara India");
addMarkerAtGeo("Cocorna City Colombia");
addMarkerAtGeo("Raiya India");
addMarkerAtGeo("Cucuta Colombia");
addMarkerAtGeo("Gove Angola");
addMarkerAtGeo("al-Awzai Lebanon");
addMarkerAtGeo("Huanta Peru");
addMarkerAtGeo("Caculama Angola");
addMarkerAtGeo("Paphos Cyprus");
addMarkerAtGeo("Quinguila District Angola");
addMarkerAtGeo("Tame Colombia");
addMarkerAtGeo("Derik Turkey");
addMarkerAtGeo("Zaragoza Colombia");
addMarkerAtGeo("Biopio Dam Angola");
addMarkerAtGeo("Rushinga Zimbabwe");
addMarkerAtGeo("Cukurca Turkey");
addMarkerAtGeo("Jolo Island Philippines");
addMarkerAtGeo("Anuradhapura District Sri Lanka");
addMarkerAtGeo("Taraza Colombia");
addMarkerAtGeo("Mullaittivu Sri Lanka");
addMarkerAtGeo("Bawianwali Balaggan India");
addMarkerAtGeo("Marawi City Philippines");
addMarkerAtGeo("Kromkuil South Africa");
addMarkerAtGeo("Alto Pauralli Peru");
addMarkerAtGeo("Muktsar India");
addMarkerAtGeo("Batman Turkey");
addMarkerAtGeo("Kagiso South Africa");
addMarkerAtGeo("Tumbes City Peru");
addMarkerAtGeo("Lingayen Philippines");
addMarkerAtGeo("not stated Mozambique");
addMarkerAtGeo("Kufr Jammal Israel");
addMarkerAtGeo("Catarman Philippines");
addMarkerAtGeo("Paranthan Sri Lanka");
addMarkerAtGeo("Ortakoy Turkey");
addMarkerAtGeo("Moulmein Myanmar");
addMarkerAtGeo("Maramag Town Philippines");
addMarkerAtGeo("Puerto Escondido Colombia");
addMarkerAtGeo("Turfontein South Africa");
addMarkerAtGeo("Asagikavir Village Turkey");
addMarkerAtGeo("Patiala India");
addMarkerAtGeo("Pucara Peru");
addMarkerAtGeo("Karnataka State India");
addMarkerAtGeo("Kalmunai Sri Lanka");
addMarkerAtGeo("La Solicita Colombia");
addMarkerAtGeo("Jaintipura India");
addMarkerAtGeo("Sebokeng Township South Africa");
addMarkerAtGeo("Sachabamba Peru");
addMarkerAtGeo("Manawala India");
addMarkerAtGeo("Palaly Sri Lanka");
addMarkerAtGeo("Mexico Town Philippines");
addMarkerAtGeo("Cundinamarca Dept. Colombia");
addMarkerAtGeo("Keygam India");
addMarkerAtGeo("Envigado Colombia");
addMarkerAtGeo("Buntharik District Thailand");
addMarkerAtGeo("Durban South Africa");
addMarkerAtGeo("Qarawat Bani-Zayd Israel");
addMarkerAtGeo("Huayaucachi Peru");
addMarkerAtGeo("Inanda * South Africa");
addMarkerAtGeo("Poona India");
addMarkerAtGeo("not stated Zimbabwe");
addMarkerAtGeo("Kalawachikudi Sri Lanka");
addMarkerAtGeo("Dikbogaz Near Eruh Turkey");
addMarkerAtGeo("Simarona Colombia");
addMarkerAtGeo("Thohoyandou Venda* South Africa");
addMarkerAtGeo("Elephant Pass Sri Lanka");
addMarkerAtGeo("Ketziot Israel");
addMarkerAtGeo("Shujabad Pakistan");
addMarkerAtGeo("Kandecholi Sri Lanka");
addMarkerAtGeo("Jaffa Israel");
addMarkerAtGeo("Raisinghnagar India");
addMarkerAtGeo("Buldon Town Philippines");
addMarkerAtGeo("Teorama Colombia");
addMarkerAtGeo("Daglica District Turkey");
addMarkerAtGeo("Yebyu Myanmar");
addMarkerAtGeo("Longonjo Angola");
addMarkerAtGeo("Batticaloa District Sri Lanka");
addMarkerAtGeo("Vilcasusuya Peru");
addMarkerAtGeo("Tarma Province Peru");
addMarkerAtGeo("Seleti Senegal");
addMarkerAtGeo("Balilihan Philippines");
addMarkerAtGeo("Fatehgarh Churian India");
addMarkerAtGeo("Badiana Senegal");
addMarkerAtGeo("San Isidro Philippines");
addMarkerAtGeo("Ram-on Tannah Israel");
addMarkerAtGeo("Masbate Island Philippines");
addMarkerAtGeo("Uribe-Meta Colombia");
addMarkerAtGeo("Batticaloa Sri Lanka");
addMarkerAtGeo("Nyamaropa Mozambique");
addMarkerAtGeo("Recresh Peru");
addMarkerAtGeo("Gran Shinungari Peru");
addMarkerAtGeo("Bikfayah Lebanon");
addMarkerAtGeo("Baramula town India");
addMarkerAtGeo("Pietermaritzburg South Africa");
addMarkerAtGeo("Pucuguruguay Peru");
addMarkerAtGeo("Safakadal India");
addMarkerAtGeo("Kuminkadi India");
addMarkerAtGeo("Dhaka Bangladesh");
addMarkerAtGeo("Buenos Aires Peru");
addMarkerAtGeo("Llochegua Peru");
addMarkerAtGeo("Bespinarlar Turkey");
addMarkerAtGeo("Norte de Santandor Colombia");
addMarkerAtGeo("Karainagar Sri Lanka");
addMarkerAtGeo("Kashmir State India");
addMarkerAtGeo("Cevrimli Village Turkey");
addMarkerAtGeo("Santa Cruz Bolivia");
addMarkerAtGeo("Nyimba Zambia");
addMarkerAtGeo("Ochegua Peru");
addMarkerAtGeo("Capetown South Africa");
addMarkerAtGeo("Alberton South Africa");
addMarkerAtGeo("Paccha Peru");
addMarkerAtGeo("Cape Province South Africa");
addMarkerAtGeo("Parachinar Pakistan");
addMarkerAtGeo("Mar del Plata Argentina");
addMarkerAtGeo("Van Province Turkey");
addMarkerAtGeo("Palca Peru");
addMarkerAtGeo("Chupaq-Patacorral Peru");
addMarkerAtGeo("Anantnag India");
addMarkerAtGeo("Kale Area Turkey");
addMarkerAtGeo("Remedios Colombia");
addMarkerAtGeo("Roadeport South Africa");
addMarkerAtGeo("Rosario Argentina");
addMarkerAtGeo("al-Nabatiyah Lebanon");
addMarkerAtGeo("Makilalal Philippines");
addMarkerAtGeo("Trujillo Colombia");
addMarkerAtGeo("Ness Ziona Israel");
addMarkerAtGeo("Northern Angola Angola");
addMarkerAtGeo("Meerut India");
addMarkerAtGeo("Iqlim al-Tuffah Lebanon");
addMarkerAtGeo("Chupata Peru");
addMarkerAtGeo("San Francisco Colombia");
addMarkerAtGeo("Cabria Angola");
addMarkerAtGeo("Guayabetal Colombia");
addMarkerAtGeo("Luenca Angola");
addMarkerAtGeo("San Fernando Philippines");
addMarkerAtGeo("Xocoalchica Guatemala");
addMarkerAtGeo("Kenniya Sri Lanka");
addMarkerAtGeo("Cuzco Peru");
addMarkerAtGeo("Benguela Province Angola");
addMarkerAtGeo("Pagudpud Philippines");
addMarkerAtGeo("Morawaka Sri Lanka");
addMarkerAtGeo("Northwest Spain Spain");
addMarkerAtGeo("Saint Palais France");
addMarkerAtGeo("Muks District Turkey");
addMarkerAtGeo("Pereira Colombia");
addMarkerAtGeo("Near Derecik Turkey");
addMarkerAtGeo("Northern Israel Israel");
addMarkerAtGeo("Los Palmitos Colombia");
addMarkerAtGeo("Rafah West Bank and Gaza Strip");
addMarkerAtGeo("Transkei Homeland South Africa");
addMarkerAtGeo("rural Cacua dept Colombia");
addMarkerAtGeo("Abra Lebanon");
addMarkerAtGeo("Jaimito Peru");
addMarkerAtGeo("Madras India");
addMarkerAtGeo("Sibundoy Colombia");
addMarkerAtGeo("Near Zaragoza Colombia");
addMarkerAtGeo("Hazhaz Ethiopia");
addMarkerAtGeo("Bade village India");
addMarkerAtGeo("Paucartambo Peru");
addMarkerAtGeo("Rishon al Ziyyon Israel");
addMarkerAtGeo("Chamesa Colombia");
addMarkerAtGeo("Panay Island Philippines");
addMarkerAtGeo("Central Somalia Somalia");
addMarkerAtGeo("San Pedro Laguna Philippines");
addMarkerAtGeo("Mardin Turkey");
addMarkerAtGeo("Waripura India");
addMarkerAtGeo("Between Maria Teresa and Calomboloca Angola");
addMarkerAtGeo("Colombo Sri Lanka");
addMarkerAtGeo("Sanza Pombo Angola");
addMarkerAtGeo("Caceres Colombia");
addMarkerAtGeo("Ixopo South Africa");
addMarkerAtGeo("Cacuaco Angola");
addMarkerAtGeo("Rawalpindi Pakistan");
addMarkerAtGeo("Dikbogaz Turkey");
addMarkerAtGeo("Lahowal India");
addMarkerAtGeo("MaquiPasa Peru");
addMarkerAtGeo("Manila Philippines");
addMarkerAtGeo("caloocan city Philippines");
addMarkerAtGeo("Bhuduwalla India");
addMarkerAtGeo("Puerto Valdivia Colombia");
addMarkerAtGeo("Beytusebap District Turkey");
addMarkerAtGeo("Tagum Town Philippines");
addMarkerAtGeo("North Burma Myanmar");
addMarkerAtGeo("Luango Angola");
addMarkerAtGeo("Centro Bagio Philippines");
addMarkerAtGeo("San Carlos Colombia");
addMarkerAtGeo("Jammu India");
addMarkerAtGeo("Castellano Philippines");
addMarkerAtGeo("Caxito Angola");
addMarkerAtGeo("Bongabong Town Philippines");
addMarkerAtGeo("La Estrella Colombia");
addMarkerAtGeo("Batala India");
addMarkerAtGeo("Pagadian City Philippines");
addMarkerAtGeo("Asillo Peru");
addMarkerAtGeo("Dayrut Egypt");
addMarkerAtGeo("Tel Aviv Israel");
addMarkerAtGeo("Guagua Philippines");
addMarkerAtGeo("Molapo South Africa");
addMarkerAtGeo("Chelig Iran");
addMarkerAtGeo("Talwandibhai India");
addMarkerAtGeo("Quetta Pakistan");
addMarkerAtGeo("Pasig Philippines");
addMarkerAtGeo("Gercekli Turkey");
addMarkerAtGeo("Nurhak Turkey");
addMarkerAtGeo("Bostanli Village Turkey");
addMarkerAtGeo("Santa Cruz Philippines");
addMarkerAtGeo("Cuito Angola");
addMarkerAtGeo("La Vega Colombia");
addMarkerAtGeo("Sepapani Village India");
addMarkerAtGeo("Hilal Turkey");
addMarkerAtGeo("Western Section Lebanon");
addMarkerAtGeo("Goreshwar India");
addMarkerAtGeo("Bani Suhaylah West Bank and Gaza Strip");
addMarkerAtGeo("Debtachhari Bangladesh");
addMarkerAtGeo("Huayucachi Peru");
addMarkerAtGeo("Ninatavur Village Sri Lanka");
addMarkerAtGeo("Nkullu South Africa");
addMarkerAtGeo("Hesenan Turkey");
addMarkerAtGeo("Ferozepore District India");
addMarkerAtGeo("Sopor India");
addMarkerAtGeo("Amparai District Sri Lanka");
addMarkerAtGeo("Buenavista Peru");
addMarkerAtGeo("Moengo Suriname");
addMarkerAtGeo("Huaura Peru");
addMarkerAtGeo("Loch Neagh Northern Ireland");
addMarkerAtGeo("Luangwa District Zambia");
addMarkerAtGeo("Ramlal Village India");
addMarkerAtGeo("Kwamashu * South Africa");
addMarkerAtGeo("Orcotuna Village Peru");
addMarkerAtGeo("Tyre Lebanon");
addMarkerAtGeo("Halambagaswewa Sri Lanka");
addMarkerAtGeo("Vichada Colombia");
addMarkerAtGeo("Murunkan Sri Lanka");
addMarkerAtGeo("Bhatinda India");
addMarkerAtGeo("Panipat India");
addMarkerAtGeo("Villa Garzon Colombia");
addMarkerAtGeo("Masiu Philippines");
addMarkerAtGeo("Emthonjeni South Africa");
addMarkerAtGeo("Sebokeng South Africa");
addMarkerAtGeo("El Pantano Colombia");
addMarkerAtGeo("Dabeiba Colombia");
addMarkerAtGeo("Arrabeh West Bank and Gaza Strip");
addMarkerAtGeo("Nacaroa Mozambique");
addMarkerAtGeo("Cimitarra Colombia");
addMarkerAtGeo("Germiston South Africa");
addMarkerAtGeo("Ayacucno Peru");
addMarkerAtGeo("zawalpindi Pakistan");
addMarkerAtGeo("Sao Paulo Brazil");
addMarkerAtGeo("Alto Paurelli Peru");
addMarkerAtGeo("Gabela Angola");
addMarkerAtGeo("Pajule Uganda");
addMarkerAtGeo("Claveria Philippines");
addMarkerAtGeo("area unk Mozambique");
addMarkerAtGeo("Ozyurt Turkey");
addMarkerAtGeo("Central Province Sri Lanka");
addMarkerAtGeo("Brahmawal Tandi India");
addMarkerAtGeo("Matola - Rio Mozambique");
addMarkerAtGeo("Ziguincher Senegal");
addMarkerAtGeo("Qabatiyah Israel");
addMarkerAtGeo("Siferezan Turkey");
addMarkerAtGeo("Huancayo Peru");
addMarkerAtGeo("Mapinhame Mozambique");
addMarkerAtGeo("El Rodeo El Salvador");
addMarkerAtGeo("Shati refugee camp Israel");
addMarkerAtGeo("Jenin West Bank and Gaza Strip");
