addMarkerAtLatLng(48.856614,2.352222);
addMarkerAtLatLng(51.236419,-0.570291);
addMarkerAtLatLng(13.99,-88.758);
addMarkerAtLatLng(13.85077,-88.90406);
addMarkerAtLatLng(-6.15837269318,155.382212277);
addMarkerAtLatLng(43.387537,-1.675432);
addMarkerAtLatLng(13.65,-88.9);
addMarkerAtLatLng(52.279911,8.047179);
addMarkerAtLatLng(13.673556,-89.248333);
addMarkerAtLatLng(34.693738,135.502165);
addMarkerAtLatLng(13.6588889,-89.183556);
addMarkerAtLatLng(22.311183,114.169265);
addMarkerAtLatLng(53.354715,-4.234764);
addMarkerAtLatLng(18.380782,-65.957387);
addMarkerAtLatLng(53.119088,-4.130307);
addMarkerAtLatLng(54.577043,-8.126228);
addMarkerAtLatLng(42.231356,-8.712447);
addMarkerAtLatLng(52.570246,-0.243734);
addMarkerAtLatLng(35.664035,139.698212);
addMarkerAtLatLng(42.567651,8.757222);
addMarkerAtLatLng(40.886105,-74.280944);
addMarkerAtLatLng(13.84222,-89.09694);
addMarkerAtLatLng(25.728985,-80.237419);
addMarkerAtLatLng(13.808917,-89.228637);
addMarkerAtLatLng(13.447063,-88.556531);
addMarkerAtLatLng(36.597591,-121.896772);
addMarkerAtLatLng(38.871899,-77.155479);
addMarkerAtLatLng(13.842778,-89.4472222);
addMarkerAtLatLng(14.147318,-89.519693);
addMarkerAtLatLng(37.501265,-3.672423);
addMarkerAtLatLng(13.802046,-87.896732);
addMarkerAtLatLng(50.850335,4.351685);
addMarkerAtLatLng(13.89271,-88.043983);
addMarkerAtLatLng(54.347539,-6.656108);
addMarkerAtLatLng(52.722818,-4.055409);
addMarkerAtLatLng(13.333325,-85.372013);
addMarkerAtLatLng(18.207906,-71.09953);
addMarkerAtLatLng(52.708174,-2.754321);
addMarkerAtLatLng(14.029529,-88.881689);
addMarkerAtLatLng(13.835,-89.2744444);
addMarkerAtLatLng(53.553813,9.991586);
addMarkerAtLatLng(48.562303,-1.928174);
addMarkerAtLatLng(13.909089,-89.164841);
addMarkerAtLatLng(35.776608,140.318781);
addMarkerAtLatLng(-6.219231,155.496286);
addMarkerAtLatLng(43.46096,-3.807934);
addMarkerAtLatLng(12.861759,-85.941473);
addMarkerAtLatLng(32.08078,-81.090719);
addMarkerAtLatLng(43.507604,-5.604447);
addMarkerAtLatLng(53.410777,-2.977838);
addMarkerAtLatLng(42.06388,-1.605718);
addMarkerAtLatLng(43.370873,-8.395835);
addMarkerAtLatLng(55.828558,37.621336);
addMarkerAtLatLng(42.880447,-8.546303);
addMarkerAtLatLng(13.561665,-88.490093);
addMarkerAtLatLng(14.8,-89.55);
addMarkerAtLatLng(29.187525,-82.140394);
addMarkerAtLatLng(13.2538889,-88.2477778);
addMarkerAtLatLng(13.9166667,-88.2333333);
addMarkerAtLatLng(51.500152,-0.126236);
addMarkerAtLatLng(13.99417,-89.55972);
addMarkerAtLatLng(47.218371,-1.553621);
addMarkerAtLatLng(12.223183,-85.422843);
addMarkerAtLatLng(54.536706,-6.70361);
addMarkerAtLatLng(54.482055,-8.088244);
addMarkerAtLatLng(43.143332,-2.962985);
addMarkerAtLatLng(13.5,-88.35);
addMarkerAtLatLng(13.738762,-89.054916);
addMarkerAtLatLng(35.685826,139.756684);
addMarkerAtLatLng(53.957702,-1.082286);
addMarkerAtLatLng(35.329197,25.138667);
addMarkerAtLatLng(13.7666667,-88.2666667);
addMarkerAtLatLng(-17.624167,177.452778);
addMarkerAtLatLng(40.183333,44.516667);
addMarkerAtLatLng(42.895218,-2.168798);
addMarkerAtLatLng(53.999977,-6.403739);
addMarkerAtLatLng(35.906259,139.628634);
addMarkerAtLatLng(-8.25,147.0666667);
addMarkerAtLatLng(13.5,-88.8666667);
addMarkerAtLatLng(43.230556,-2.845833);
addMarkerAtLatLng(52.955115,-1.149172);
addMarkerAtLatLng(34.05349,-118.245319);
addMarkerAtLatLng(37.950902,23.641103);
addMarkerAtLatLng(13.85,-88.85);
addMarkerAtLatLng(54.823432,-7.468374);
addMarkerAtLatLng(15.50167,-88.02774);
addMarkerAtLatLng(13.7682,-88.129139);
addMarkerAtLatLng(13.7333333,-88.8833333);
addMarkerAtLatLng(14.551944,-90.942222);
addMarkerAtLatLng(38.997652,-1.86007);
addMarkerAtLatLng(37.869885,-122.270539);
addMarkerAtLatLng(48.208174,16.373819);
addMarkerAtLatLng(41.634202,-1.27299);
addMarkerAtLatLng(56.6,-6.233333);
addMarkerAtLatLng(37.983445,-1.12989);
addMarkerAtLatLng(54.101529,-6.526442);
addMarkerAtLatLng(14.677931,-92.14893);
addMarkerAtLatLng(54.180913,-6.229722);
addMarkerAtLatLng(14.563479,-90.982067);
addMarkerAtLatLng(54.238631,-7.170908);
addMarkerAtLatLng(14.454176,-87.643076);
addMarkerAtLatLng(15.25,-89.75);
addMarkerAtLatLng(14.19096,-89.428112);
addMarkerAtLatLng(13.95,-88.6333333);
addMarkerAtLatLng(13.949826,-88.146348);
addMarkerAtLatLng(43.320812,-1.984447);
addMarkerAtLatLng(54.060164,-6.59568);
addMarkerAtLatLng(42.774838,-1.655764);
addMarkerAtLatLng(13.749987,-89.423305);
addMarkerAtLatLng(13.97556,-89.34);
addMarkerAtLatLng(43.108611,-2.911111);
addMarkerAtLatLng(13.79833,-89.17889);
addMarkerAtLatLng(13.701964,-89.147774);
addMarkerAtLatLng(42.465776,-2.449995);
addMarkerAtLatLng(-4.373414,139.351478);
addMarkerAtLatLng(13.6247222,-87.8936111);
addMarkerAtLatLng(13.557072,-88.349433);
addMarkerAtLatLng(12.929811,-85.917027);
addMarkerAtLatLng(41.88415,-87.632409);
addMarkerAtLatLng(54.597269,-5.930109);
addMarkerAtLatLng(13.7166667,-88.1166667);
addMarkerAtLatLng(54.510893,-6.042726);
addMarkerAtLatLng(13.719546,-88.360633);
addMarkerAtLatLng(13.69288,-89.199161);
addMarkerAtLatLng(13.78944,-86.012157);
addMarkerAtLatLng(13.723215,-88.819097);
addMarkerAtLatLng(44.912998,-0.243985);
addMarkerAtLatLng(13.558889,-88.43);
addMarkerAtLatLng(14.316514,-89.171394);
addMarkerAtLatLng(26.640845,-81.868194);
addMarkerAtLatLng(43.280364,-2.171588);
addMarkerAtLatLng(13.5166667,-88.3833333);
addMarkerAtLatLng(15.891524,-89.229486);
addMarkerAtLatLng(33.749074,-117.873943);
addMarkerAtLatLng(33.823555,-113.542024);
addMarkerAtLatLng(13.36899,-88.658074);
addMarkerAtLatLng(13.965554,-88.892274);
addMarkerAtLatLng(14.370243,-89.209569);
addMarkerAtLatLng(43.320698,-2.420475);
addMarkerAtLatLng(43.256963,-2.923441);
addMarkerAtLatLng(15.9250939247,-90.9145393372);
addMarkerAtLatLng(13.61177,-88.026466);
addMarkerAtLatLng(54.577389,-6.677339);
addMarkerAtLatLng(43.066466,-2.489145);
addMarkerAtLatLng(14.088915,-88.957833);
addMarkerAtLatLng(13.6391667,-89.3783333);
addMarkerAtLatLng(51.22181,1.402734);
addMarkerAtLatLng(54.428873,-7.13241);
addMarkerAtLatLng(14.523889,-90.798333);
addMarkerAtLatLng(52.069858,4.291111);
addMarkerAtLatLng(13.36497,-85.83496);
addMarkerAtLatLng(40.993764,22.876291);
addMarkerAtLatLng(14.11923,-87.231951);
addMarkerAtLatLng(40.639349,22.944616);
addMarkerAtLatLng(42.292435,-85.601114);
addMarkerAtLatLng(13.536835,-88.780584);
addMarkerAtLatLng(19.3833333,-70.4166667);
addMarkerAtLatLng(38.445515,-121.816104);
addMarkerAtLatLng(42.167839,-1.690636);
addMarkerAtLatLng(13.64121,-88.785423);
addMarkerAtLatLng(52.505803,13.331741);
addMarkerAtLatLng(40.629816,-3.166493);
addMarkerAtLatLng(37.089532,127.032699);
addMarkerAtLatLng(40.438335,-79.997459);
addMarkerAtLatLng(40.617222,47.15);
addMarkerAtLatLng(41.387917,2.169919);
addMarkerAtLatLng(32.221553,-110.969754);
addMarkerAtLatLng(54.542956,-6.926293);
addMarkerAtLatLng(-6.228251,155.565903);
addMarkerAtLatLng(11.817878998,-85.0336360931);
addMarkerAtLatLng(13.7333333,-87.9333333);
addMarkerAtLatLng(34.198444,-78.344135);
addMarkerAtLatLng(47.19504,-120.939419);
addMarkerAtLatLng(14.107072,-89.072863);
addMarkerAtLatLng(38.464524,23.60507);
addMarkerAtLatLng(33.502115,-86.755509);
addMarkerAtLatLng(42.3586111,20.825);
addMarkerAtLatLng(45.764043,4.835659);
addMarkerAtLatLng(35.605057,140.123306);
addMarkerAtLatLng(41.919229,8.738635);
addMarkerAtLatLng(54.542468,-6.043481);
addMarkerAtLatLng(13.71667,-88.65);
addMarkerAtLatLng(41.725175,1.823353);
addMarkerAtLatLng(12.382409,-85.51372);
addMarkerAtLatLng(45.529783,9.038125);
addMarkerAtLatLng(12.800014,-85.133347);
addMarkerAtLatLng(13.6769444,-89.2797222);
addMarkerAtLatLng(42.846718,-2.671635);
addMarkerAtLatLng(14.050173,-88.837704);
addMarkerAtLatLng(39.107891,26.555374);
addMarkerAtLatLng(43.163141,-1.23811);
addMarkerAtLatLng(54.981084,-6.682382);
addMarkerAtLatLng(13.85,-88.3);
addMarkerAtLatLng(14.15695,-89.011475);
addMarkerAtLatLng(15.319722,-91.47833);
addMarkerAtLatLng(43.311307,-1.900896);
addMarkerAtLatLng(14.0,-88.9);
addMarkerAtLatLng(54.502852,-6.769568);
addMarkerAtLatLng(16.8,-89.933333);
addMarkerAtLatLng(14.17224,-89.996549);
addMarkerAtLatLng(14.932386,-91.913588);
addMarkerAtLatLng(54.713382,-6.216761);
addMarkerAtLatLng(44.696228,10.627795);
addMarkerAtLatLng(55.070718,-6.514895);
addMarkerAtLatLng(13.72528,-89.74639);
addMarkerAtLatLng(53.281723,-3.828439);
addMarkerAtLatLng(54.788077,-7.47303);
addMarkerAtLatLng(-6.2723,155.668594);
addMarkerAtLatLng(43.388051,-1.663055);
addMarkerAtLatLng(40.481663,-3.364136);
addMarkerAtLatLng(-5.858188,144.242934);
addMarkerAtLatLng(43.317073,-2.678975);
addMarkerAtLatLng(49.008085,8.403756);
addMarkerAtLatLng(29.868336,121.54399);
addMarkerAtLatLng(36.947147,14.605876);
addMarkerAtLatLng(40.8501,-73.866246);
addMarkerAtLatLng(51.801116,-4.971537);
addMarkerAtLatLng(16.3394,-90.5778);
addMarkerAtLatLng(15.397896,-90.870876);
addMarkerAtLatLng(14.191091,-90.982067);
addMarkerAtLatLng(43.545261,-5.661926);
addMarkerAtLatLng(43.483152,-1.558626);
addMarkerAtLatLng(42.113828,8.701548);
addMarkerAtLatLng(36.594682,136.625573);
addMarkerAtLatLng(52.0422,-0.7047);
addMarkerAtLatLng(50.661027,14.032997);
addMarkerAtLatLng(54.18006,-6.33393);
addMarkerAtLatLng(43.296482,5.36978);
addMarkerAtLatLng(47.498406,19.040758);
addMarkerAtLatLng(15.433,-87.917);
addMarkerAtLatLng(38.579065,-121.491014);
addMarkerAtLatLng(51.124707,6.19314);
addMarkerAtLatLng(25.826745,-80.281494);
addMarkerAtLatLng(42.118119,2.764748);
addMarkerAtLatLng(44.391415,8.194362);
addMarkerAtLatLng(13.6667,-88.208264);
addMarkerAtLatLng(40.458904,-3.479771);
addMarkerAtLatLng(39.6425,-77.717579);
addMarkerAtLatLng(36.377413,25.479973);
addMarkerAtLatLng(13.08956,-86.354361);
addMarkerAtLatLng(-6.304047,155.72656);
addMarkerAtLatLng(-6.219262,155.627069);
addMarkerAtLatLng(54.255696,-5.948804);
addMarkerAtLatLng(43.00732,40.989151);
addMarkerAtLatLng(54.951082,-6.558998);
addMarkerAtLatLng(54.645861,-6.745149);
addMarkerAtLatLng(55.129345,-6.663439);
addMarkerAtLatLng(39.706772,-3.431007);
addMarkerAtLatLng(13.938518,-88.901366);
addMarkerAtLatLng(13.42778,-87.9333333);
addMarkerAtLatLng(42.129208,-1.137434);
addMarkerAtLatLng(15.766786,-86.833055);
addMarkerAtLatLng(54.99451,-7.319996);
addMarkerAtLatLng(13.49446,-88.530343);
addMarkerAtLatLng(45.409538,11.876554);
addMarkerAtLatLng(13.3166667,-88.5833333);
addMarkerAtLatLng(54.208418,-5.891745);
addMarkerAtLatLng(39.810998,46.751147);
addMarkerAtLatLng(42.817988,-1.644184);
addMarkerAtLatLng(13.879493,-89.01261);
addMarkerAtLatLng(13.420304,-88.571307);
addMarkerAtLatLng(54.411142,-6.600146);
addMarkerAtLatLng(43.054198,-2.178116);
addMarkerAtLatLng(13.4333333,-88.7);
addMarkerAtLatLng(51.964711,7.628498);
addMarkerAtLatLng(13.9572222,-89.1897222);
addMarkerAtLatLng(39.905556,116.395833);
addMarkerAtLatLng(14.04111,-88.938568);
addMarkerAtLatLng(51.92942,7.681123);
addMarkerAtLatLng(14.070743,-88.905453);
addMarkerAtLatLng(13.586201,-88.750773);
addMarkerAtLatLng(54.077313,-6.608787);
addMarkerAtLatLng(54.467377,-6.261373);
addMarkerAtLatLng(31.231763,121.484443);
addMarkerAtLatLng(54.65548,-5.674815);
addMarkerAtLatLng(15.4518538322,-86.6750149591);
addMarkerAtLatLng(13.772142,-88.07664);
addMarkerAtLatLng(13.902951,-89.496613);
addMarkerAtLatLng(13.874575,-88.627779);
addMarkerAtLatLng(50.111445,8.680615);
addMarkerAtLatLng(18.369196,-66.165967);
addMarkerAtLatLng(13.814197,-88.34682);
addMarkerAtLatLng(19.7577778,-72.2041667);
addMarkerAtLatLng(52.090142,5.109665);
addMarkerAtLatLng(41.347783,26.493128);
addMarkerAtLatLng(43.224079,-2.718935);
addMarkerAtLatLng(-20.452203,166.617329);
addMarkerAtLatLng(14.191665,-89.1706);
addMarkerAtLatLng(54.18064,-6.410521);
addMarkerAtLatLng(13.888888,-88.901631);
addMarkerAtLatLng(30.33138,-81.655799);
addMarkerAtLatLng(9.933333,-84.083333);
addMarkerAtLatLng(52.570091,-1.798329);
addMarkerAtLatLng(53.104966,-3.911578);
addMarkerAtLatLng(15.133333,-87.133333);
addMarkerAtLatLng(43.492949,-1.474841);
addMarkerAtLatLng(14.624422,-90.53288);
addMarkerAtLatLng(38.725299,-9.150036);
addMarkerAtLatLng(54.42071,-6.443767);
addMarkerAtLatLng(35.680432,140.026526);
addMarkerAtLatLng(-6.72367,146.990906);
addMarkerAtLatLng(42.695391,-1.676069);
addMarkerAtLatLng(13.7,-88.1);
addMarkerAtLatLng(13.58944,-89.28889);
addMarkerAtLatLng(43.768732,11.256901);
addMarkerAtLatLng(8.994269,-79.518792);
addMarkerAtLatLng(41.330476,2.093149);
addMarkerAtLatLng(16.912033,-90.299578);
addMarkerAtLatLng(43.189944,-2.052454);
addMarkerAtLatLng(41.89052,12.494249);
addMarkerAtLatLng(54.462881,-7.028646);
addMarkerAtLatLng(54.258585,-5.84266);
addMarkerAtLatLng(15.095278,-91.150833);
addMarkerAtLatLng(54.6197,-6.50612);
addMarkerAtLatLng(14.032462,-88.910688);
addMarkerAtLatLng(13.445104,-88.246118);
addMarkerAtLatLng(14.965261,-91.795813);
addMarkerAtLatLng(54.102813,-6.259412);
addMarkerAtLatLng(43.232653,-3.013887);
addMarkerAtLatLng(43.338233,-1.789272);
addMarkerAtLatLng(43.222177,-2.885668);
addMarkerAtLatLng(54.088462,-6.37122);
addMarkerAtLatLng(13.818333,-87.9713889);
addMarkerAtLatLng(16.85,-90.883333);
addMarkerAtLatLng(13.6166667,-88.5666667);
addMarkerAtLatLng(32.715695,-117.161719);
addMarkerAtLatLng(13.53333,-88.35);
addMarkerAtLatLng(52.516667,13.4);
addMarkerAtLatLng(11.4293029567,-84.8391742706);
addMarkerAtLatLng(11.901553,-84.403479);
addMarkerAtLatLng(51.091922,6.888806);
addMarkerAtLatLng(15.047369,-91.811557);
addMarkerAtLatLng(17.99008,-66.112324);
addMarkerAtLatLng(54.238079,-6.161199);
addMarkerAtLatLng(13.619026,-88.930144);
addMarkerAtLatLng(55.676075,12.568316);
addMarkerAtLatLng(14.0833,-87.2167);
addMarkerAtLatLng(41.699801,9.346925);
addMarkerAtLatLng(50.940664,6.959912);
addMarkerAtLatLng(13.933732,-89.025836);
addMarkerAtLatLng(13.97667,-89.7472);
addMarkerAtLatLng(13.6333333,-88.2666667);
addMarkerAtLatLng(14.176874,-88.920431);
addMarkerAtLatLng(42.577204,-2.846297);
addMarkerAtLatLng(37.97918,23.716647);
addMarkerAtLatLng(13.466667,-88.183333);
addMarkerAtLatLng(33.748315,-84.391109);
addMarkerAtLatLng(51.889804,0.901235);
addMarkerAtLatLng(14.77312,-91.183037);
addMarkerAtLatLng(43.325239,-3.011475);
addMarkerAtLatLng(14.4,-91.3167);
addMarkerAtLatLng(18.5391667,-72.335);
addMarkerAtLatLng(13.8333333,-88.7166667);
addMarkerAtLatLng(14.528065,-91.367422);
addMarkerAtLatLng(28.475562,-16.267372);
addMarkerAtLatLng(42.9105556,21.1930556);
addMarkerAtLatLng(43.267454,-2.020169);
addMarkerAtLatLng(13.66667,-89.26667);
addMarkerAtLatLng(42.530333,-1.674269);
addMarkerAtLatLng(42.975677,-2.290072);
addMarkerAtLatLng(51.534471,7.685883);
addMarkerAtLatLng(41.005342,-2.78473);
addMarkerAtLatLng(19.432608,-99.133207);
addMarkerAtLatLng(18.456792,-69.951164);
addMarkerAtLatLng(45.551596,18.68077);
addMarkerAtLatLng(41.280029,-3.477578);
addMarkerAtLatLng(50.22715,8.61592);
addMarkerAtLatLng(14.761426,-90.991885);
addMarkerAtLatLng(43.136978,-2.073914);
addMarkerAtLatLng(14.12458,-89.293171);
addMarkerAtLatLng(14.009286,-88.940189);
addMarkerAtLatLng(52.372068,9.735686);
addMarkerAtLatLng(13.864829,-88.7494);
addMarkerAtLatLng(51.455313,-2.591902);
addMarkerAtLatLng(14.833333,-91.516667);
addMarkerAtLatLng(18.0845,-66.357154);
addMarkerAtLatLng(14.548389,-91.354326);
addMarkerAtLatLng(18.249015,-66.034034);
addMarkerAtLatLng(42.854587,-1.744925);
addMarkerAtLatLng(12.886513,-85.268628);
addMarkerAtLatLng(14.331414,-89.442393);
addMarkerAtLatLng(45.463681,9.188171);
addMarkerAtLatLng(40.416691,-3.700345);
addMarkerAtLatLng(13.805691,-88.145787);
addMarkerAtLatLng(-33.873651,151.20689);
addMarkerAtLatLng(54.467967,-6.337967);
addMarkerAtLatLng(53.344104,-6.267494);
addMarkerAtLatLng(39.470239,-0.376805);
addMarkerAtLatLng(13.7833333,-88.1333333);
addMarkerAtLatLng(38.89051,-77.086294);
addMarkerAtLatLng(13.487179,-88.765032);
addMarkerAtLatLng(13.344322,-88.437463);
addMarkerAtLatLng(39.093245,-94.415629);
addMarkerAtLatLng(15.03,-91.15);
addMarkerAtLatLng(13.8769444,-89.173556);
addMarkerAtLatLng(59.332788,18.064488);
addMarkerAtLatLng(36.740685,-119.785734);
addMarkerAtLatLng(14.487721,-90.805956);
addMarkerAtLatLng(14.169631,-89.102686);
addMarkerAtLatLng(43.003305,-2.612578);
addMarkerAtLatLng(15.498381,-90.982067);
addMarkerAtLatLng(55.75,37.616667);
addMarkerAtLatLng(43.20725,-71.536604);
addMarkerAtLatLng(43.299442,-1.859099);
addMarkerAtLatLng(49.606945,15.579348);
addMarkerAtLatLng(-6.315071,155.495276);
addMarkerAtLatLng(50.087811,14.42046);
addMarkerAtLatLng(10.666667,-61.516667);
addMarkerAtLatLng(43.029037,-1.932957);
addMarkerAtLatLng(13.7188889,-89.7241667);
addMarkerAtLatLng(13.498952,-89.069988);
addMarkerAtLatLng(13.8761111,-89.3597222);
addMarkerAtLatLng(14.338896,-89.178268);
addMarkerAtLatLng(13.8833333,-88.9666667);
addMarkerAtGeo("Mineros De Antioquia Colombia");
addMarkerAtGeo("Huanuco Peru");
addMarkerAtGeo("Kurunegala Sri Lanka");
addMarkerAtGeo("Embilipitiya Sri Lanka");
addMarkerAtGeo("Beytussebab Turkey");
addMarkerAtGeo("Kegalle District Sri Lanka");
addMarkerAtGeo("Chittagong Bangladesh");
addMarkerAtGeo("Paditirippu Sri Lanka");
addMarkerAtGeo("Cajatambo Peru");
addMarkerAtGeo("Coloso Colombia");
addMarkerAtGeo("Lakewood Philippines");
addMarkerAtGeo("Aceh Province Indonesia");
addMarkerAtGeo("Mount Lavinia Sri Lanka");
addMarkerAtGeo("Puente Lamarate Peru");
addMarkerAtGeo("Turbo Colombia");
addMarkerAtGeo("El Tambo Peru");
addMarkerAtGeo("Toledo Colombia");
addMarkerAtGeo("Chifunde Mozambique");
addMarkerAtGeo("Srinagar India");
addMarkerAtGeo("Johal India");
addMarkerAtGeo("Kurungala Sri Lanka");
addMarkerAtGeo("Cerro de Pasco Peru");
addMarkerAtGeo("Heel Oya Sri Lanka");
addMarkerAtGeo("Atwal India");
addMarkerAtGeo("Makhu India");
addMarkerAtGeo("Kapalturai Sri Lanka");
addMarkerAtGeo("Unknown Sri Lanka");
addMarkerAtGeo("Ropar India");
addMarkerAtGeo("Mullaitivu Sri Lanka");
addMarkerAtGeo("Kebethegollawa Sri Lanka");
addMarkerAtGeo("Chiquian Peru");
addMarkerAtGeo("srinigar India");
addMarkerAtGeo("Galle Sri Lanka");
addMarkerAtGeo("Deniyaya Sri Lanka");
addMarkerAtGeo("Eerste River South Africa");
addMarkerAtGeo("Chaclacayo Peru");
addMarkerAtGeo("Al Khidr Israel");
addMarkerAtGeo("Akbopure Sri Lanka");
addMarkerAtGeo("Mecca Saudi Arabia");
addMarkerAtGeo("Mendoza Argentina");
addMarkerAtGeo("Rasoolpur India");
addMarkerAtGeo("Azangaro Peru");
addMarkerAtGeo("Nabuke India");
addMarkerAtGeo("Pacaran Peru");
addMarkerAtGeo("Morowaka Sri Lanka");
addMarkerAtGeo("Amgallegama Sri Lanka");
addMarkerAtGeo("Bugaramanca Colombia");
addMarkerAtGeo("Vietiane Laos");
addMarkerAtGeo("Masbate Philippines");
addMarkerAtGeo("Androgue Argentina");
addMarkerAtGeo("Santa Maria Colombia");
addMarkerAtGeo("Texas Vitali Philippines");
addMarkerAtGeo("Patiala district India");
addMarkerAtGeo("Chundikulam Sri Lanka");
addMarkerAtGeo("Mavaddapuram Sri Lanka");
addMarkerAtGeo("Huallaga Peru");
addMarkerAtGeo("Thon Buri Thailand");
addMarkerAtGeo("Palestina Colombia");
addMarkerAtGeo("Beltran Colombia");
addMarkerAtGeo("Northeastern Province Sri Lanka");
addMarkerAtGeo("Hira India");
addMarkerAtGeo("Baddegana Sri Lanka");
addMarkerAtGeo("Jullundur District India");
addMarkerAtGeo("Khan Younis West Bank and Gaza Strip");
addMarkerAtGeo("Kehllawela Sri Lanka");
addMarkerAtGeo("Yapraktepe Turkey");
addMarkerAtGeo("Zawiya West Bank and Gaza Strip");
addMarkerAtGeo("Mawarella Sri Lanka");
addMarkerAtGeo("South Lebanon Lebanon");
addMarkerAtGeo("Potungan Philippines");
addMarkerAtGeo("Agusan Del Sur Prov. Philippines");
addMarkerAtGeo("Tamulasco El Salvador");
addMarkerAtGeo("Ferozepore India");
addMarkerAtGeo("Lislico El Salvador");
addMarkerAtGeo("Faridkot District India");
addMarkerAtGeo("Homesh West Bank and Gaza Strip");
addMarkerAtGeo("Sammanthurai Sri Lanka");
addMarkerAtGeo("Hakkari Prov. Turkey");
addMarkerAtGeo("Yeoville South Africa");
addMarkerAtGeo("Kurucesme Turkey");
addMarkerAtGeo("Kalkanli Turkey");
addMarkerAtGeo("Gaza West Bank and Gaza Strip");
addMarkerAtGeo("Dhaniyachhara Bangladesh");
addMarkerAtGeo("Pretoria South Africa");
addMarkerAtGeo("Aija Peru");
addMarkerAtGeo("Matanza Colombia");
addMarkerAtGeo("Jullundur India");
addMarkerAtGeo("Assam State India");
addMarkerAtGeo("Kulian India");
addMarkerAtGeo("Quiches Peru");
addMarkerAtGeo("Guanalocha Peru");
addMarkerAtGeo("Chupamarca Peru");
addMarkerAtGeo("Dusibandh India");
addMarkerAtGeo("Ampara District Sri Lanka");
addMarkerAtGeo("Akduzgun Turkey");
addMarkerAtGeo("kokrajhar district India");
addMarkerAtGeo("OLuklu Turkey");
addMarkerAtGeo("La Merced Peru");
addMarkerAtGeo("Anuradahapura Sri Lanka");
addMarkerAtGeo("Bongabong Philippines");
addMarkerAtGeo("Pantarpata Peru");
addMarkerAtGeo("Anantnag Town India");
addMarkerAtGeo("Debathgama Sri Lanka");
addMarkerAtGeo("Faure Station South Africa");
addMarkerAtGeo("Patiali India");
addMarkerAtGeo("Bogazoren Turkey");
addMarkerAtGeo("Maharagama Sri Lanka");
addMarkerAtGeo("Cartagena Colombia");
addMarkerAtGeo("Marrupa Mozambique");
addMarkerAtGeo("Huatasani Peru");
addMarkerAtGeo("Barangay Bigal Philippines");
addMarkerAtGeo("Quelimane Mozambique");
addMarkerAtGeo("Cassoalala Angola");
addMarkerAtGeo("Jaro Philippines");
addMarkerAtGeo("Vilankulam Sri Lanka");
addMarkerAtGeo("Kegalle Sri Lanka");
addMarkerAtGeo("Parashga Peru");
addMarkerAtGeo("Sandton South Africa");
addMarkerAtGeo("Samrawan India");
addMarkerAtGeo("Uludere Turkey");
addMarkerAtGeo("la Palma Colombia");
addMarkerAtGeo("Singhbitia India");
addMarkerAtGeo("San Jose Aguacatitan El Salvador");
addMarkerAtGeo("West Bank West Bank and Gaza Strip");
addMarkerAtGeo("Ongwediva South Africa");
addMarkerAtGeo("Petah Tikva Israel");
addMarkerAtGeo("Mindoro Island Philippines");
addMarkerAtGeo("Mdadza village Zimbabwe");
addMarkerAtGeo("Vubwe Zambia");
addMarkerAtGeo("Kandy District Sri Lanka");
addMarkerAtGeo("La Ceiba Colombia");
addMarkerAtGeo("Thoppur Village Sri Lanka");
addMarkerAtGeo("Chavakachcheri Sri Lanka");
addMarkerAtGeo("myawaddy Myanmar");
addMarkerAtGeo("Chonguene Mozambique");
addMarkerAtGeo("Cheherta India");
addMarkerAtGeo("San Nicolas Philippines");
addMarkerAtGeo("Papudo Chile");
addMarkerAtGeo("Angeles Philippines");
addMarkerAtGeo("Dikenli Turkey");
addMarkerAtGeo("al-Mawayra Israel");
addMarkerAtGeo("Dilekli Turkey");
addMarkerAtGeo("near Moengo Suriname");
addMarkerAtGeo("Angooa Sri Lanka");
addMarkerAtGeo("Uva Province Sri Lanka");
addMarkerAtGeo("Aktas Turkey");
addMarkerAtGeo("Pasco Dept Peru");
addMarkerAtGeo("Chavin Peru");
addMarkerAtGeo("Khangnadesian India");
addMarkerAtGeo("Supe Peru");
addMarkerAtGeo("Dickwella Sri Lanka");
addMarkerAtGeo("Talisay Philippines");
addMarkerAtGeo("Catembe Mozambique");
addMarkerAtGeo("Doma Myanmar");
addMarkerAtGeo("Pata South Africa");
addMarkerAtGeo("Kwamashu township South Africa");
addMarkerAtGeo("Anilmis Turkey");
addMarkerAtGeo("Ayacucho City Peru");
addMarkerAtGeo("Nuevo Progresso Peru");
addMarkerAtGeo("San Antonio Colombia");
addMarkerAtGeo("Tekoa Israel");
addMarkerAtGeo("Tulkarm West Bank and Gaza Strip");
addMarkerAtGeo("King Williams Town South Africa");
addMarkerAtGeo("Natagaima Colombia");
addMarkerAtGeo("Near Amritsar India");
addMarkerAtGeo("Arauca Intendency Colombia");
addMarkerAtGeo("Ulapane Sri Lanka");
addMarkerAtGeo("Madugastalawa Sri Lanka");
addMarkerAtGeo("Kichki Peru");
addMarkerAtGeo("Veyangoda Sri Lanka");
addMarkerAtGeo("Beit Yahoun Lebanon");
addMarkerAtGeo("San Anton Peru");
addMarkerAtGeo("Bishop Lavis South Africa");
addMarkerAtGeo("Chosica Peru");
addMarkerAtGeo("Chibuto Mozambique");
addMarkerAtGeo("Vina del Mar Chile");
addMarkerAtGeo("Jauja Peru");
addMarkerAtGeo("Pueblo Nuevo Peru");
addMarkerAtGeo("Fidel Castro Village Mozambique");
addMarkerAtGeo("Kwamashu South Africa");
addMarkerAtGeo("Brahma Attari India");
addMarkerAtGeo("Mata de Coco Venezuela");
addMarkerAtGeo("Har Dou Lebanon");
addMarkerAtGeo("Guragaon India");
addMarkerAtGeo("Bekaa Valley Lebanon");
addMarkerAtGeo("Mitchells Plain South Africa");
addMarkerAtGeo("San Bernardo Colombia");
addMarkerAtGeo("Mullaitivu District Sri Lanka");
addMarkerAtGeo("Rancagua Chile");
addMarkerAtGeo("Huacaybamba Peru");
addMarkerAtGeo("Churcampa Peru");
addMarkerAtGeo("Teldeniya Sri Lanka");
addMarkerAtGeo("Aramtah Lebanon");
addMarkerAtGeo("North Cotabato Prov. Philippines");
addMarkerAtGeo("Adilabad District India");
addMarkerAtGeo("Acobamba Peru");
addMarkerAtGeo("Piang Luang Thailand");
addMarkerAtGeo("LLama Corral Peru");
addMarkerAtGeo("Anilar Turkey");
addMarkerAtGeo("Carepa Colombia");
addMarkerAtGeo("Razik Turkey");
addMarkerAtGeo("Huamachuco Peru");
addMarkerAtGeo("Beirut Lebanon");
addMarkerAtGeo("Soweto South Africa");
addMarkerAtGeo("Kurunegala District Sri Lanka");
addMarkerAtGeo("Sol de Oro Peru");
addMarkerAtGeo("Carmen de Atrato Colombia");
addMarkerAtGeo("Hanwella Sri Lanka");
addMarkerAtGeo("Hyderbad Pakistan");
addMarkerAtGeo("San Vicente de Chucuri Peru");
addMarkerAtGeo("near Mahabad Iran");
addMarkerAtGeo("Quezon City Philippines");
addMarkerAtGeo("Velvettiturai Sri Lanka");
addMarkerAtGeo("Junin Peru");
addMarkerAtGeo("Sohal India");
addMarkerAtGeo("Laguna de Maramaca Peru");
addMarkerAtGeo("Gulburnu Turkey");
addMarkerAtGeo("La Herradura Peru");
addMarkerAtGeo("Jahanabad Dist India");
addMarkerAtGeo("Notre De Santander Dedt Colombia");
addMarkerAtGeo("Isla Tabaco Colombia");
addMarkerAtGeo("Mecula Mozambique");
addMarkerAtGeo("Rangamati District Bangladesh");
addMarkerAtGeo("San Ildefonso El Salvador");
addMarkerAtGeo("Aydogdu Turkey");
addMarkerAtGeo("Hoshiardpur district India");
addMarkerAtGeo("Jerusalem Israel");
addMarkerAtGeo("Siruc Turkey");
addMarkerAtGeo("East London South Africa");
addMarkerAtGeo("Batticaloa Sri Lanka");
addMarkerAtGeo("San Martin Dept Peru");
addMarkerAtGeo("Kafr Tibnit Lebanon");
addMarkerAtGeo("Idnah West Bank and Gaza Strip");
addMarkerAtGeo("Huayllay Peru");
addMarkerAtGeo("San Carlos Colombia");
addMarkerAtGeo("Huamanga Peru");
addMarkerAtGeo("La Quebrada del Loro Colombia");
addMarkerAtGeo("Yunguyo Peru");
addMarkerAtGeo("Occollo Peru");
addMarkerAtGeo("Gaza  City West Bank and Gaza Strip");
addMarkerAtGeo("Galawela Sri Lanka");
addMarkerAtGeo("San Critobal Peru");
addMarkerAtGeo("Huancayo city Peru");
addMarkerAtGeo("Alawathuwala Sri Lanka");
addMarkerAtGeo("Lunugamvehera Sri Lanka");
addMarkerAtGeo("Srinigar India");
addMarkerAtGeo("Caicedonia Colombia");
addMarkerAtGeo("Arapa Peru");
addMarkerAtGeo("Alkan Province Philippines");
addMarkerAtGeo("Pariajasa Peru");
addMarkerAtGeo("Runikheta India");
addMarkerAtGeo("Dubai United Arab Emirates");
addMarkerAtGeo("Colombo District Sri Lanka");
addMarkerAtGeo("Mainimukh Bangladesh");
addMarkerAtGeo("Siyam Balanduwa Sri Lanka");
addMarkerAtGeo("Ramle Israel");
addMarkerAtGeo("Quilpue Chile");
addMarkerAtGeo("Rio Cuarto Argentina");
addMarkerAtGeo("Oddusuddan Sri Lanka");
addMarkerAtGeo("Barranquilla Colombia");
addMarkerAtGeo("Al-Khiyam Lebanon");
addMarkerAtGeo("Paramarid Suriname");
addMarkerAtGeo("Kamisili Turkey");
addMarkerAtGeo("Pangasinan Prov. Philippines");
addMarkerAtGeo("Lakhana Village India");
addMarkerAtGeo("Nawala Sri Lanka");
addMarkerAtGeo("Petah Tiqua Israel");
addMarkerAtGeo("Nimalawa Sri Lanka");
addMarkerAtGeo("Gauhati India");
addMarkerAtGeo("Kilometer 20 Colombia");
addMarkerAtGeo("Risaralda Colombia");
addMarkerAtGeo("Nhassacara Mozambique");
addMarkerAtGeo("Ratnapura District Sri Lanka");
addMarkerAtGeo("Yamunanagar India");
addMarkerAtGeo("Gaza Strip West Bank and Gaza Strip");
addMarkerAtGeo("Unknown Philippines");
addMarkerAtGeo("Medellin Colombia");
addMarkerAtGeo("Kwamakuta South Africa");
addMarkerAtGeo("Cusco Peru");
addMarkerAtGeo("Nongkrating Thailand");
addMarkerAtGeo("Rambukpotha Sri Lanka");
addMarkerAtGeo("Beit Hanoun Israel");
addMarkerAtGeo("Thohoyandou South Africa");
addMarkerAtGeo("Lakhne India");
addMarkerAtGeo("Buldon Philippines");
addMarkerAtGeo("San Juan Peru");
addMarkerAtGeo("Nigel South Africa");
addMarkerAtGeo("Omdurman Sudan");
addMarkerAtGeo("Pothuhera Sri Lanka");
addMarkerAtGeo("Tampalakamam Sri Lanka");
addMarkerAtGeo("Mardan Pakistan");
addMarkerAtGeo("Huambo Province Angola");
addMarkerAtGeo("Pariahuanca Peru");
addMarkerAtGeo("Huechuas Peru");
addMarkerAtGeo("Kurunegala Region Sri Lanka");
addMarkerAtGeo("Andabamba Peru");
addMarkerAtGeo("New Dheli India");
addMarkerAtGeo("Pucallpa Peru");
addMarkerAtGeo("Pasco Peru");
addMarkerAtGeo("Koholwila Sri Lanka");
addMarkerAtGeo("Mullaittivu Sri Lanka");
addMarkerAtGeo("Hambantota District Sri Lanka");
addMarkerAtGeo("Marawi City Philippines");
addMarkerAtGeo("Chitega Colombia");
addMarkerAtGeo("Manizales Colombia");
addMarkerAtGeo("Dereler Turkey");
addMarkerAtGeo("Urubokke Sri Lanka");
addMarkerAtGeo("Jabalyan Israel");
addMarkerAtGeo("Mafikeng South Africa");
addMarkerAtGeo("Pucara Peru");
addMarkerAtGeo("Kalmunai Sri Lanka");
addMarkerAtGeo("Sindanga Philippines");
addMarkerAtGeo("Chola India");
addMarkerAtGeo("Losaka Zambia");
addMarkerAtGeo("Megiddo Israel");
addMarkerAtGeo("Southern Province Sri Lanka");
addMarkerAtGeo("Mattakuliya Sri Lanka");
addMarkerAtGeo("Concepcion Peru");
addMarkerAtGeo("Pacha Peru");
addMarkerAtGeo("Gulu Uganda");
addMarkerAtGeo("Godigamuwa Sri Lanka");
addMarkerAtGeo("Chitta Village India");
addMarkerAtGeo("Saravena Colombia");
addMarkerAtGeo("Bandulla District Sri Lanka");
addMarkerAtGeo("Colombo (Pettah area) Sri Lanka");
addMarkerAtGeo("Dili Indonesia");
addMarkerAtGeo("Bir Zeit West Bank and Gaza Strip");
addMarkerAtGeo("agartala India");
addMarkerAtGeo("Baddewewa Sri Lanka");
addMarkerAtGeo("Montana De Jaca Spain");
addMarkerAtGeo("Alldays South Africa");
addMarkerAtGeo("Sarzulgarh India");
addMarkerAtGeo("Islamabad Pakistan");
addMarkerAtGeo("Huaraz Peru");
addMarkerAtGeo("Cota Bambas Peru");
addMarkerAtGeo("Sidli India");
addMarkerAtGeo("Cajamarquilla Peru");
addMarkerAtGeo("Casanarg Intendency Colombia");
addMarkerAtGeo("Pardes Kaz Israel");
addMarkerAtGeo("Norte de Santander Dept. Colombia");
addMarkerAtGeo("Santander Dept. Colombia");
addMarkerAtGeo("Ponta Pora Brazil");
addMarkerAtGeo("Kotta Gol Shah India");
addMarkerAtGeo("San Jose Peru");
addMarkerAtGeo("Kohuwela Sri Lanka");
addMarkerAtGeo("Arghastan Afghanistan");
addMarkerAtGeo("Stellenbosch South Africa");
addMarkerAtGeo("Walpita Sri Lanka");
addMarkerAtGeo("Winwa Myanmar");
addMarkerAtGeo("Chipazi Mozambique");
addMarkerAtGeo("Girandurukotte Sri Lanka");
addMarkerAtGeo("Barranca Bermeja Colombia");
addMarkerAtGeo("Divulapitiya Sri Lanka");
addMarkerAtGeo("Point Pedro Sri Lanka");
addMarkerAtGeo("La Vega Colombia");
addMarkerAtGeo("Esperanza Philippines");
addMarkerAtGeo("Bani Suhaylah West Bank and Gaza Strip");
addMarkerAtGeo("amritsar India");
addMarkerAtGeo("Ferozepore District India");
addMarkerAtGeo("North Cotabato Province Philippines");
addMarkerAtGeo("Huancavelila Peru");
addMarkerAtGeo("Tangalla Sri Lanka");
addMarkerAtGeo("Surigao Del Sur Prov. Philippines");
addMarkerAtGeo("San Francisco Colombia");
addMarkerAtGeo("Rumichaca Peru");
addMarkerAtGeo("Bengtol India");
addMarkerAtGeo("Kfar Ruppin Israel");
addMarkerAtGeo("El Carrizalillo El Salvador");
addMarkerAtGeo("Assam state India");
addMarkerAtGeo("Matale District Sri Lanka");
addMarkerAtGeo("Katakwe Village Zambia");
addMarkerAtGeo("Rangamati Bangladesh");
addMarkerAtGeo("Salakati India");
addMarkerAtGeo("Tingo Maria Peru");
addMarkerAtGeo("Juliaca Peru");
addMarkerAtGeo("La Jagua de Jbirico Colombia");
addMarkerAtGeo("Jamphal India");
addMarkerAtGeo("Kusluca Turkey");
addMarkerAtGeo("Inadi township South Africa");
addMarkerAtGeo("Mantaro Peru");
addMarkerAtGeo("Khongolote Mozambique");
addMarkerAtGeo("Tricomalee Sri Lanka");
addMarkerAtGeo("Kumi Uganda");
addMarkerAtGeo("La Plata Argentina");
addMarkerAtGeo("Chillan Chile");
addMarkerAtGeo("Itsmina Colombia");
addMarkerAtGeo("San Juan Batista Peru");
addMarkerAtGeo("Vavuniya District Sri Lanka");
addMarkerAtGeo("Iriga Philippines");
addMarkerAtGeo("Dutuwewa Sri Lanka");
addMarkerAtGeo("Andanarca Peru");
addMarkerAtGeo("Azzun West Bank and Gaza Strip");
addMarkerAtGeo("San Miguel Peru");
addMarkerAtGeo("Valencia Colombia");
addMarkerAtGeo("Unknown Niger");
addMarkerAtGeo("Canaire Peru");
addMarkerAtGeo("Fayoum Egypt");
addMarkerAtGeo("Mahiyangana Sri Lanka");
addMarkerAtGeo("Huaurahua Peru");
addMarkerAtGeo("Boskamp Suriname");
addMarkerAtGeo("Chiara Peru");
addMarkerAtGeo("Atkas Village Turkey");
addMarkerAtGeo("Matale Sri Lanka");
addMarkerAtGeo("Ratanda South Africa");
addMarkerAtGeo("Silopi Township Turkey");
addMarkerAtGeo("Erzincan Turkey");
addMarkerAtGeo("Kabakan Philippines");
addMarkerAtGeo("Kapsanget Kenya");
addMarkerAtGeo("Puno Peru");
addMarkerAtGeo("Porac Philippines");
addMarkerAtGeo("Bihar State India");
addMarkerAtGeo("Khandwala India");
addMarkerAtGeo("Siirt Province Turkey");
addMarkerAtGeo("Wilpattu National Park Sri Lanka");
addMarkerAtGeo("srinagar India");
addMarkerAtGeo("Aranagala Sri Lanka");
addMarkerAtGeo("Ayacucho Peru");
addMarkerAtGeo("Damascus Syria");
addMarkerAtGeo("Huaripampa Peru");
addMarkerAtGeo("Bengo Province Angola");
addMarkerAtGeo("Nueva Esperanza Peru");
addMarkerAtGeo("myawadi Myanmar");
addMarkerAtGeo("Rasulpar India");
addMarkerAtGeo("Cangallo Peru");
addMarkerAtGeo("North of Huancayo Peru");
addMarkerAtGeo("Poddala Sri Lanka");
addMarkerAtGeo("San Nicolas Argentina");
addMarkerAtGeo("Talwandi Rai Dadoo India");
addMarkerAtGeo("Yakir Israel");
addMarkerAtGeo("Borma Somalia");
addMarkerAtGeo("Wekarein Myanmar");
addMarkerAtGeo("Pardes Hanna Israel");
addMarkerAtGeo("Tangalle Sri Lanka");
addMarkerAtGeo("Hungama Sri Lanka");
addMarkerAtGeo("Caracas Venezuela");
addMarkerAtGeo("Larkana Pakistan");
addMarkerAtGeo("Mistrato Colombia");
addMarkerAtGeo("Isla Tobaco Colombia");
addMarkerAtGeo("Holmberg Argentina");
addMarkerAtGeo("Timbique Colombia");
addMarkerAtGeo("Soweto Township South Africa");
addMarkerAtGeo("Kalutara Sri Lanka");
addMarkerAtGeo("South Israel Israel");
addMarkerAtGeo("Pampa Coris Peru");
addMarkerAtGeo("Catanauan Philippines");
addMarkerAtGeo("Dargecit Turkey");
addMarkerAtGeo("tripura state India");
addMarkerAtGeo("North Central Province Sri Lanka");
addMarkerAtGeo("Ramallah West Bank and Gaza Strip");
addMarkerAtGeo("Bogota Colombia");
addMarkerAtGeo("Sincilejo Colombia");
addMarkerAtGeo("Luanda Angola");
addMarkerAtGeo("Calanugan Philippines");
addMarkerAtGeo("Sidon Lebanon");
addMarkerAtGeo("Sultan Kudarat Philippines");
addMarkerAtGeo("San Juan de Oro Peru");
addMarkerAtGeo("Tabuk Philippines");
addMarkerAtGeo("Aguasan Del Sur Prov. Philippines");
addMarkerAtGeo("Bulembu South Africa");
addMarkerAtGeo("Astillero Colombia");
addMarkerAtGeo("Rogongon Philippines");
addMarkerAtGeo("Antioquia Dept Colombia");
addMarkerAtGeo("Yarima Colombia");
addMarkerAtGeo("Ambalangoda Sri Lanka");
addMarkerAtGeo("Wilsonia South Africa");
addMarkerAtGeo("Dharamgarh India");
addMarkerAtGeo("Sangrur District India");
addMarkerAtGeo("Meetiyagoda Sri Lanka");
addMarkerAtGeo("Gugapir India");
addMarkerAtGeo("Shekhawal India");
addMarkerAtGeo("Capetown South Africa");
addMarkerAtGeo("Matara District Sri Lanka");
addMarkerAtGeo("Ayacucho Dept. Peru");
addMarkerAtGeo("Hakkari prov Turkey");
addMarkerAtGeo("El Bagre Colombia");
addMarkerAtGeo("Los Andes Chile");
addMarkerAtGeo("Haryana India");
addMarkerAtGeo("Mantaro River Peru");
addMarkerAtGeo("Jericho West Bank and Gaza Strip");
addMarkerAtGeo("Banadia Colombia");
addMarkerAtGeo("Nabas Town Philippines");
addMarkerAtGeo("Puttalam Sri Lanka");
addMarkerAtGeo("Mdantsane South Africa");
addMarkerAtGeo("Apoera Suriname");
addMarkerAtGeo("San Juan de Castrovirreyna Peru");
addMarkerAtGeo("Agusan del Sur Prov. Philippines");
addMarkerAtGeo("Cifteitepe Turkey");
addMarkerAtGeo("Meadowlands South Africa");
addMarkerAtGeo("El Penon El Salvador");
addMarkerAtGeo("Anantnag India");
addMarkerAtGeo("Grand Bassis Mauritius");
addMarkerAtGeo("Location unk Colombia");
addMarkerAtGeo("Northern Iraq Iraq");
addMarkerAtGeo("Qiryat Shemona Israel");
addMarkerAtGeo("Arequipa Peru");
addMarkerAtGeo("Balarkalan India");
addMarkerAtGeo("Dereler Kirmizitepe Turkey");
addMarkerAtGeo("Tripoli Lebanon");
addMarkerAtGeo("Bronswg Suriname");
addMarkerAtGeo("Renaca Chile");
addMarkerAtGeo("Chittagong Hill Tracts District Bangladesh");
addMarkerAtGeo("Hargobindpur India");
addMarkerAtGeo("Chimoio Mozambique");
addMarkerAtGeo("Santiago de Chuco Peru");
addMarkerAtGeo("Cucumacayan El Salvador");
addMarkerAtGeo("Uruh Turkey");
addMarkerAtGeo("Katu Myanmar");
addMarkerAtGeo("Mpopmeni South Africa");
addMarkerAtGeo("Menikhinna Sri Lanka");
addMarkerAtGeo("karnal India");
addMarkerAtGeo("Pachagra Peru");
addMarkerAtGeo("Tambo Peru");
addMarkerAtGeo("Weli Oya District Sri Lanka");
addMarkerAtGeo("Puttur Sri Lanka");
addMarkerAtGeo("Porongo Peru");
addMarkerAtGeo("Arahuay Peru");
addMarkerAtGeo("Baghdad Iraq");
addMarkerAtGeo("Mundoviejo Colombia");
addMarkerAtGeo("Dighinala Bangladesh");
addMarkerAtGeo("Bayt Yahun Lebanon");
addMarkerAtGeo("La Polvora Peru");
addMarkerAtGeo("Pacaycasa Peru");
addMarkerAtGeo("Uckardesler Turkey");
addMarkerAtGeo("Gamapaha District Sri Lanka");
addMarkerAtGeo("livingstone Zambia");
addMarkerAtGeo("Galilee Israel");
addMarkerAtGeo("Al-Khiam Lebanon");
addMarkerAtGeo("San Antonio Bajo Colombia");
addMarkerAtGeo("Cajacay Peru");
addMarkerAtGeo("Montevideo Uruguay");
addMarkerAtGeo("gacia rovira Colombia");
addMarkerAtGeo("Siran Turkey");
addMarkerAtGeo("nueva esperanza Peru");
addMarkerAtGeo("La Zorra El Salvador");
addMarkerAtGeo("Pallca Peru");
addMarkerAtGeo("Lokka India");
addMarkerAtGeo("Antuco Chile");
addMarkerAtGeo("Makulella Sri Lanka");
addMarkerAtGeo("Phagwara India");
addMarkerAtGeo("Dinaig Town Philippines");
addMarkerAtGeo("Madhoke Village India");
addMarkerAtGeo("Movene Mozambique");
addMarkerAtGeo("Angeles City Philippines");
addMarkerAtGeo("San Martin Colombia");
addMarkerAtGeo("Florencia Colombia");
addMarkerAtGeo("Chevella Village India");
addMarkerAtGeo("Kadugli Sudan");
addMarkerAtGeo("Kundasale Sri Lanka");
addMarkerAtGeo("Cidade de Magude Mozambique");
addMarkerAtGeo("Tembisa South Africa");
addMarkerAtGeo("Ambar Peru");
addMarkerAtGeo("San Marcos Peru");
addMarkerAtGeo("Magalona Philippines");
addMarkerAtGeo("Ocros Peru");
addMarkerAtGeo("Chittigong Hills Bangladesh");
addMarkerAtGeo("Retama Peru");
addMarkerAtGeo("Valachenai Sri Lanka");
addMarkerAtGeo("khargone India");
addMarkerAtGeo("Karachi Pakistan");
addMarkerAtGeo("Terra Alta Colombia");
addMarkerAtGeo("Ambalantota Sri Lanka");
addMarkerAtGeo("Loria Para India");
addMarkerAtGeo("Ayacucho Dept Peru");
addMarkerAtGeo("Cajamarqilla Peru");
addMarkerAtGeo("khagragachi Bangladesh");
addMarkerAtGeo("Cauca Dept. Colombia");
addMarkerAtGeo("Sucre Bolivia");
addMarkerAtGeo("Gurdapur district India");
addMarkerAtGeo("Konkulam Sri Lanka");
addMarkerAtGeo("Paramaribo Suriname");
addMarkerAtGeo("El Manao Nicaragua");
addMarkerAtGeo("San Martin de Pangoa Peru");
addMarkerAtGeo("Sudhpora India");
addMarkerAtGeo("Htonaing Myanmar");
addMarkerAtGeo("Sardalli Turkey");
addMarkerAtGeo("Asanthe Sri Lanka");
addMarkerAtGeo("mogaung township Myanmar");
addMarkerAtGeo("Ananea Peru");
addMarkerAtGeo("el-mahmoudiya Egypt");
addMarkerAtGeo("Unknown Chile");
addMarkerAtGeo("Katuwana Sri Lanka");
addMarkerAtGeo("Beruit Lebanon");
addMarkerAtGeo("Tlokweng Botswana");
addMarkerAtGeo("Horowpathana Sri Lanka");
addMarkerAtGeo("Kuala Lumpur Malaysia");
addMarkerAtGeo("Kataragama Sri Lanka");
addMarkerAtGeo("Pulagahawella India");
addMarkerAtGeo("La Bateca Colombia");
addMarkerAtGeo("Hermon Israel");
addMarkerAtGeo("Contamana Peru");
addMarkerAtGeo("Huarcanta Peru");
addMarkerAtGeo("Liberal Party Colombia");
addMarkerAtGeo("Vistahermosa Colombia");
addMarkerAtGeo("Hingurakgoda Sri Lanka");
addMarkerAtGeo("Kozagac Turkey");
addMarkerAtGeo("Mbabane Swaziland");
addMarkerAtGeo("Besagac Village Turkey");
addMarkerAtGeo("Udalgiri India");
addMarkerAtGeo("Hakmana Sri Lanka");
addMarkerAtGeo("Mahmoobnagar Dist. India");
addMarkerAtGeo("Border Gate South Africa");
addMarkerAtGeo("San Jacinto Colombia");
addMarkerAtGeo("La Parra Nicaragua");
addMarkerAtGeo("Resistencia Argentina");
addMarkerAtGeo("Onculer Turkey");
addMarkerAtGeo("Vischongos Peru");
addMarkerAtGeo("Palpa Peru");
addMarkerAtGeo("Lanao del Sur Prov. Philippines");
addMarkerAtGeo("Kafr Falus Lebanon");
addMarkerAtGeo("Chikarawa Zambia");
addMarkerAtGeo("Malapatan Philippines");
addMarkerAtGeo("Kohali India");
addMarkerAtGeo("Galilee District Israel");
addMarkerAtGeo("Amarkalan India");
addMarkerAtGeo("Dhilwan Village India");
addMarkerAtGeo("Yurac Yurac Peru");
addMarkerAtGeo("Santu Nangal India");
addMarkerAtGeo("Davao del Sur Prov. Philippines");
addMarkerAtGeo("Ozamis City Philippines");
addMarkerAtGeo("quetta Pakistan");
addMarkerAtGeo("Bilgi Village Turkey");
addMarkerAtGeo("Santo Domingo Colombia");
addMarkerAtGeo("Anuradhapura Sri Lanka");
addMarkerAtGeo("Nat Miao Myanmar");
addMarkerAtGeo("Cucuta Colombia");
addMarkerAtGeo("hmawbi Myanmar");
addMarkerAtGeo("Salgar Colombia");
addMarkerAtGeo("Cesar Dept Colombia");
addMarkerAtGeo("Jammu India");
addMarkerAtGeo("Bogamuwewayaya Sri Lanka");
addMarkerAtGeo("Ninacaca Peru");
addMarkerAtGeo("Habarana Sri Lanka");
addMarkerAtGeo("Polonnaruwa District Sri Lanka");
addMarkerAtGeo("Maimburg* Philippines");
addMarkerAtGeo("Manhica Mozambique");
addMarkerAtGeo("Amritsar India");
addMarkerAtGeo("Jenin West Bank and Gaza Strip");
addMarkerAtGeo("Outjo Namibia");
addMarkerAtGeo("Tierra Alta Colombia");
addMarkerAtGeo("Kawkaba Lebanon");
addMarkerAtGeo("Unknown Colombia");
addMarkerAtGeo("Gorentepe Turkey");
addMarkerAtGeo("La Morada Peru");
addMarkerAtGeo("Loja Ecuador");
addMarkerAtGeo("Uda Walawe Sri Lanka");
addMarkerAtGeo("Posadas Argentina");
addMarkerAtGeo("quito Ecuador");
addMarkerAtGeo("Mullaitivu Dist. Sri Lanka");
addMarkerAtGeo("Kalawewa Sri Lanka");
addMarkerAtGeo("Northeast El Salvador El Salvador");
addMarkerAtGeo("Pahki India");
addMarkerAtGeo("Maymyo Myanmar");
addMarkerAtGeo("Lagalla Sri Lanka");
addMarkerAtGeo("Renca Chile");
addMarkerAtGeo("Janin West Bank and Gaza Strip");
addMarkerAtGeo("Coppename River Crossing Suriname");
addMarkerAtGeo("San Berardo Colombia");
addMarkerAtGeo("Mehanwana India");
addMarkerAtGeo("Sirnak Turkey");
addMarkerAtGeo("Hullaitivu Sri Lanka");
addMarkerAtGeo("Raipur Rian India");
addMarkerAtGeo("Deraniyangala Sri Lanka");
addMarkerAtGeo("Tolima Depart. Colombia");
addMarkerAtGeo("Attil West Bank and Gaza Strip");
addMarkerAtGeo("Purathagode Sri Lanka");
addMarkerAtGeo("Valledupar Colombia");
addMarkerAtGeo("Trincomalee Sri Lanka");
addMarkerAtGeo("Loon Philippines");
addMarkerAtGeo("Hebron West Bank and Gaza Strip");
addMarkerAtGeo("Gothatuwa Sri Lanka");
addMarkerAtGeo("Angulana Sri Lanka");
addMarkerAtGeo("Cordoba Dept Colombia");
addMarkerAtGeo("Mannar Sri Lanka");
addMarkerAtGeo("Bambradeniya Sri Lanka");
addMarkerAtGeo("Liborina Colombia");
addMarkerAtGeo("Chupan Peru");
addMarkerAtGeo("Cocorna Colombia");
addMarkerAtGeo("Ikiyaka Turkey");
addMarkerAtGeo("Galle District Sri Lanka");
addMarkerAtGeo("Divandarreh Iran");
addMarkerAtGeo("Central Region Sri Lanka");
addMarkerAtGeo("Soacha Colombia");
addMarkerAtGeo("Gandara Sri Lanka");
addMarkerAtGeo("Zaragoza Colombia");
addMarkerAtGeo("Nongoma South Africa");
addMarkerAtGeo("Bandarawela Sri Lanka");
addMarkerAtGeo("Witwatersrand South Africa");
addMarkerAtGeo("Huichinga Peru");
addMarkerAtGeo("Nalbari India");
addMarkerAtGeo("Pelawatte Sri Lanka");
addMarkerAtGeo("Kraka Suriname");
addMarkerAtGeo("Catarman Philippines");
addMarkerAtGeo("Lenegama Sri Lanka");
addMarkerAtGeo("Silopi Turkey");
addMarkerAtGeo("Eppawala Sri Lanka");
addMarkerAtGeo("Nilandiguwa Sri Lanka");
addMarkerAtGeo("Habla West Bank and Gaza Strip");
addMarkerAtGeo("Patiala India");
addMarkerAtGeo("Rio Negro Colombia");
addMarkerAtGeo("Zulia State Venezuela");
addMarkerAtGeo("sirajganj district Bangladesh");
addMarkerAtGeo("Gurutalawa Sri Lanka");
addMarkerAtGeo("Attampola Sri Lanka");
addMarkerAtGeo("Bokhajhuli India");
addMarkerAtGeo("Elsies River South Africa");
addMarkerAtGeo("Thanchi Village Bangladesh");
addMarkerAtGeo("Ica Peru");
addMarkerAtGeo("Mabalane Mozambique");
addMarkerAtGeo("Huayhuas Peru");
addMarkerAtGeo("Gaza City West Bank and Gaza Strip");
addMarkerAtGeo("Marawi Philippines");
addMarkerAtGeo("Morococha Peru");
addMarkerAtGeo("Masapur India");
addMarkerAtGeo("Nelspruit South Africa");
addMarkerAtGeo("Tulua Colombia");
addMarkerAtGeo("srinigr India");
addMarkerAtGeo("Kinogitan Philippines");
addMarkerAtGeo("Volta Redonda Brazil");
addMarkerAtGeo("Santa Cruz Bolivia");
addMarkerAtGeo("Saiza Colombia");
addMarkerAtGeo("Bello Colombia");
addMarkerAtGeo("Luabo Mozambique");
addMarkerAtGeo("Cape Province South Africa");
addMarkerAtGeo("Carhua Pampa Peru");
addMarkerAtGeo("Hoshiapur District India");
addMarkerAtGeo("Las Cruces El Salvador");
addMarkerAtGeo("Yala Thailand");
addMarkerAtGeo("Kabipur India");
addMarkerAtGeo("Cauca Department Colombia");
addMarkerAtGeo("Punum Peru");
addMarkerAtGeo("Livingstone Zambia");
addMarkerAtGeo("Punjab State India");
addMarkerAtGeo("Ciudadela Argentina");
addMarkerAtGeo("Matara Sri Lanka");
addMarkerAtGeo("Atambagahakada Sri Lanka");
addMarkerAtGeo("Urunlu Turkey");
addMarkerAtGeo("El Sitio El Salvador");
addMarkerAtGeo("Rafah West Bank and Gaza Strip");
addMarkerAtGeo("Uraba Colombia");
addMarkerAtGeo("Furancungo Mozambique");
addMarkerAtGeo("Cauca Dept Colombia");
addMarkerAtGeo("Pampa Cores Peru");
addMarkerAtGeo("Lusaka Zambia");
addMarkerAtGeo("Thanghi Bangladesh");
addMarkerAtGeo("Grocio Prado Peru");
addMarkerAtGeo("Rawalpindi Pakistan");
addMarkerAtGeo("Kambakottai Sri Lanka");
addMarkerAtGeo("Sharinwala India");
addMarkerAtGeo("Aucayacu Peru");
addMarkerAtGeo("Manila Philippines");
addMarkerAtGeo("Palenga Uganda");
addMarkerAtGeo("Pacaysapa Peru");
addMarkerAtGeo("North Burma Myanmar");
addMarkerAtGeo("Pamococha Peru");
addMarkerAtGeo("Matola Mozambique");
addMarkerAtGeo("Padalangala Sri Lanka");
addMarkerAtGeo("Ramaduggu India");
addMarkerAtGeo("Tel Aviv Israel");
addMarkerAtGeo("Quetta Pakistan");
addMarkerAtGeo("El Alto Bolivia");
addMarkerAtGeo("Ramgoon Myanmar");
addMarkerAtGeo("Cora Cora Peru");
addMarkerAtGeo("Esuwagaon India");
addMarkerAtGeo("Boulogne Argentina");
addMarkerAtGeo("Burawin Philippines");
addMarkerAtGeo("Acikkoy Turkey");
addMarkerAtGeo("Kekirawa Sri Lanka");
addMarkerAtGeo("Patilia India");
addMarkerAtGeo("Alto San Jorge Colombia");
addMarkerAtGeo("Huamali Peru");
addMarkerAtGeo("upper Huallaga River Peru");
addMarkerAtGeo("Nabi Taher Lebanon");
addMarkerAtGeo("Guaranda Colombia");
addMarkerAtGeo("Chakania India");
addMarkerAtGeo("Inanda township South Africa");
addMarkerAtGeo("Kala Afghana India");
addMarkerAtGeo("Tarntaran India");
addMarkerAtGeo("San Marcos District, Ancash Dept. Peru");
addMarkerAtGeo("Palmira Colombia");
addMarkerAtGeo("Pankulam Sri Lanka");
addMarkerAtGeo("Yarinacocha Peru");
addMarkerAtGeo("Moragollagama Sri Lanka");
addMarkerAtGeo("Ghawanda devi India");
addMarkerAtGeo("Niassa Province Mozambique");
addMarkerAtGeo("La Oroyo Peru");
addMarkerAtGeo("Hakkari Turkey");
addMarkerAtGeo("Xinavane Mozambique");
addMarkerAtGeo("Ischccana Peru");
addMarkerAtGeo("Santan Rita de Ituango Colombia");
addMarkerAtGeo("New Delhi India");
addMarkerAtGeo("SamisipTown Philippines");
addMarkerAtGeo("Yattah West Bank and Gaza Strip");
addMarkerAtGeo("ambo Peru");
addMarkerAtGeo("Samanthurai Sri Lanka");
addMarkerAtGeo("Ja-Ela Sri Lanka");
addMarkerAtGeo("La Pena Colombia");
addMarkerAtGeo("Juan Parra del Riego Peru");
addMarkerAtGeo("Mattakkuliya Sri Lanka");
addMarkerAtGeo("Jhabal India");
addMarkerAtGeo("Maragra Mozambique");
addMarkerAtGeo("sinagar India");
addMarkerAtGeo("Zarit Israel");
addMarkerAtGeo("Village of Arraba Israel");
addMarkerAtGeo("La Mira Colombia");
addMarkerAtGeo("Bethlahem West Bank and Gaza Strip");
addMarkerAtGeo("Wear Itaue Chile");
addMarkerAtGeo("Cangola Angola");
addMarkerAtGeo("Huncayo Peru");
addMarkerAtGeo("Balveren Village Turkey");
addMarkerAtGeo("Cordoba Argentina");
addMarkerAtGeo("Marj Uyun-Ibil Lebanon");
addMarkerAtGeo("Ayacucho city Peru");
addMarkerAtGeo("Hargeisa Somalia");
addMarkerAtGeo("guwahati India");
addMarkerAtGeo("Cabo Delgado Prov. Mozambique");
addMarkerAtGeo("Pavona Abajo Nicaragua");
addMarkerAtGeo("Ankumura Sri Lanka");
addMarkerAtGeo("Qotraneh Lebanon");
addMarkerAtGeo("Athlone South Africa");
addMarkerAtGeo("Makoho Zimbabwe");
addMarkerAtGeo("Akkaraipattu Sri Lanka");
addMarkerAtGeo("La Esmeralda Colombia");
addMarkerAtGeo("Parco Peru");
addMarkerAtGeo("Masamari Peru");
addMarkerAtGeo("Bhatinda India");
addMarkerAtGeo("Tachira State Venezuela");
addMarkerAtGeo("Bhoragaon India");
addMarkerAtGeo("Polonnaruwa Sri Lanka");
addMarkerAtGeo("Tomayquichua Peru");
addMarkerAtGeo("Bangalore City India");
addMarkerAtGeo("Cartago Colombia");
addMarkerAtGeo("udalgiri India");
addMarkerAtGeo("Sanguane Mozambique");
addMarkerAtGeo("Habur Turkey");
addMarkerAtGeo("Kabul Afghanistan");
addMarkerAtGeo("Haifa Israel");
addMarkerAtGeo("Jullunder India");
addMarkerAtGeo("Tulcahuano Chile");
addMarkerAtGeo("Jaela Sri Lanka");
addMarkerAtGeo("Minneriya Sri Lanka");
addMarkerAtGeo("Myawadi Myanmar");
addMarkerAtGeo("dighinala Bangladesh");
addMarkerAtGeo("Nizip Turkey");
addMarkerAtGeo("San Roque Colombia");
addMarkerAtGeo("Battambang Cambodia");
addMarkerAtGeo("La Picota hill Colombia");
addMarkerAtGeo("Tirapata Peru");
addMarkerAtGeo("Arauca Colombia");
addMarkerAtGeo("Changuan Chile");
addMarkerAtGeo("Vina Del Mar Chile");
addMarkerAtGeo("Obongi Uganda");
addMarkerAtGeo("Kermanshah Iran");
addMarkerAtGeo("Ipabamba Peru");
addMarkerAtGeo("Loma Linda El Salvador");
addMarkerAtGeo("Hostigal Peru");
addMarkerAtGeo("Pitigala Sri Lanka");
addMarkerAtGeo("Monaragala Sri Lanka");
addMarkerAtGeo("Rijatipet India");
addMarkerAtGeo("Golgoddam Village India");
addMarkerAtGeo("Matara Town Sri Lanka");
addMarkerAtGeo("Badri Kalan India");
addMarkerAtGeo("Udawalawe Sri Lanka");
addMarkerAtGeo("Pokigron Suriname");
addMarkerAtGeo("Kokrajhar India");
addMarkerAtGeo("Dikwella Sri Lanka");
addMarkerAtGeo("kangan India");
addMarkerAtGeo("Qalqilyah Israel");
addMarkerAtGeo("Nedunkerni Sri Lanka");
addMarkerAtGeo("Dhaligaon India");
addMarkerAtGeo("Gampaha Dist. Sri Lanka");
addMarkerAtGeo("Benoni South Africa");
addMarkerAtGeo("Dehiwela Sri Lanka");
addMarkerAtGeo("Ashdod Yaacor Israel");
addMarkerAtGeo("Lanarca Cyprus");
addMarkerAtGeo("Coronie District Suriname");
addMarkerAtGeo("Beit Lid Israel");
addMarkerAtGeo("La Rioja Argentina");
addMarkerAtGeo("Pamunugama Sri Lanka");
addMarkerAtGeo("Galgediyawa Sri Lanka");
addMarkerAtGeo("Torono district Uganda");
addMarkerAtGeo("Silwad West Bank and Gaza Strip");
addMarkerAtGeo("El Carmen Colombia");
addMarkerAtGeo("Duduza South Africa");
addMarkerAtGeo("Pujiawali India");
addMarkerAtGeo("Dayr Harfa Lebanon");
addMarkerAtGeo("Aluthgoda Sri Lanka");
addMarkerAtGeo("Osorno Chile");
addMarkerAtGeo("Pacific Highway Guatemala");
addMarkerAtGeo("Mphophomeni South Africa");
addMarkerAtGeo("Ambato Ecuador");
addMarkerAtGeo("Tarapoto Peru");
addMarkerAtGeo("Girardota Colombia");
addMarkerAtGeo("Randfontein South Africa");
addMarkerAtGeo("Yala Province Thailand");
addMarkerAtGeo("Surigao del Norte Philippines");
addMarkerAtGeo("Dhaka Bangladesh");
addMarkerAtGeo("Castrovirreyna Peru");
addMarkerAtGeo("Kurungala Dist. Sri Lanka");
addMarkerAtGeo("Siguy Philippines");
addMarkerAtGeo("khulna Bangladesh");
addMarkerAtGeo("Delazi Turkey");
addMarkerAtGeo("Panagoda Homagama Sri Lanka");
addMarkerAtGeo("Imagode Sri Lanka");
addMarkerAtGeo("Naula Sri Lanka");
addMarkerAtGeo("La Oroya Peru");
addMarkerAtGeo("Tamra Israel");
addMarkerAtGeo("Akuressa Sri Lanka");
addMarkerAtGeo("Unknown Greece");
addMarkerAtGeo("Pattani Province Thailand");
addMarkerAtGeo("Nakon Ratchasima Thailand");
addMarkerAtGeo("Oyeros Peru");
addMarkerAtGeo("Vavuniya Sri Lanka");
addMarkerAtGeo("Hambantata Dist. Sri Lanka");
addMarkerAtGeo("Chandigarh India");
addMarkerAtGeo("sudhapora Ecuador");
addMarkerAtGeo("anantnag India");
addMarkerAtGeo("Orcasita Peru");
addMarkerAtGeo("lusaka Zambia");
addMarkerAtGeo("Matagama Sri Lanka");
addMarkerAtGeo("Igidir Turkey");
addMarkerAtGeo("Anuradapura Sri Lanka");
addMarkerAtGeo("Yuraq Cancha Peru");
addMarkerAtGeo("Kaler India");
addMarkerAtGeo("Talaimannar Sri Lanka");
addMarkerAtGeo("Huanuco dept Peru");
addMarkerAtGeo("Saladoblanco Colombia");
addMarkerAtGeo("Samanturai Sri Lanka");
addMarkerAtGeo("Chia Colombia");
addMarkerAtGeo("Manhica District Mozambique");
addMarkerAtGeo("Atacma Region Chile");
addMarkerAtGeo("Tumaco Colombia");
addMarkerAtGeo("Gaborone Botswana");
addMarkerAtGeo("Cullpa Peru");
addMarkerAtGeo("Mahalehhari Bangladesh");
addMarkerAtGeo("La Maranosa Nicaragua");
addMarkerAtGeo("Mindanao Island Philippines");
addMarkerAtGeo("Popayan Colombia");
addMarkerAtGeo("Khagrachhari Bangladesh");
addMarkerAtGeo("Santander de Quilichao Colombia");
addMarkerAtGeo("Cerro De Pasco Peru");
addMarkerAtGeo("Vitarte Peru");
addMarkerAtGeo("Urchiza Peru");
addMarkerAtGeo("Palliwalli India");
addMarkerAtGeo("Guaduas Colombia");
addMarkerAtGeo("Kamburupitiya Sri Lanka");
addMarkerAtGeo("Calcutta India");
addMarkerAtGeo("Murianga Mozambique");
addMarkerAtGeo("Hathangoda Sri Lanka");
addMarkerAtGeo("Kadawella Sri Lanka");
addMarkerAtGeo("Karaotlak Turkey");
addMarkerAtGeo("Ludhiansa India");
addMarkerAtGeo("Metulla Israel");
addMarkerAtGeo("Ntuzuma South Africa");
addMarkerAtGeo("Kedymandi India");
addMarkerAtGeo("Wakabasee Suriname");
addMarkerAtGeo("Jezzine Lebanon");
addMarkerAtGeo("Ressando Garcia Mozambique");
addMarkerAtGeo("Herat Afghanistan");
addMarkerAtGeo("Gondola Mozambique");
addMarkerAtGeo("Kler Village India");
addMarkerAtGeo("Pucuruhuay Peru");
addMarkerAtGeo("bihar India");
addMarkerAtGeo("Ramla Israel");
addMarkerAtGeo("Placer Philippines");
addMarkerAtGeo("Myawady Myanmar");
addMarkerAtGeo("San Jose Belen Guatemala");
addMarkerAtGeo("San Jeronimo Peru");
addMarkerAtGeo("La Paz Bolivia");
addMarkerAtGeo("Klippan South Africa");
addMarkerAtGeo("Padaviya Sri Lanka");
addMarkerAtGeo("Ratnapura Sri Lanka");
addMarkerAtGeo("Valle Del Cauca Dept. Colombia");
addMarkerAtGeo("Taurapampa Peru");
addMarkerAtGeo("Chongos Peru");
addMarkerAtGeo("Pujapitiya Sri Lanka");
addMarkerAtGeo("Badalkumbura Sri Lanka");
addMarkerAtGeo("Denora Sri Lanka");
addMarkerAtGeo("Mannar District Sri Lanka");
addMarkerAtGeo("Buruquin West Bank and Gaza Strip");
addMarkerAtGeo("Jullandur District India");
addMarkerAtGeo("Villa Madero Argentina");
addMarkerAtGeo("Shankerdura India");
addMarkerAtGeo("Tsakane South Africa");
addMarkerAtGeo("Foniva Qatar");
addMarkerAtGeo("Qaffin Village West Bank and Gaza Strip");
addMarkerAtGeo("Bongaigaon Town Sri Lanka");
addMarkerAtGeo("San Marcos District, Ancasn Dept. Peru");
addMarkerAtGeo("Hakkari Province Turkey");
addMarkerAtGeo("Santiago Chile");
addMarkerAtGeo("Eruh Turkey");
addMarkerAtGeo("San Cesar Colombia");
addMarkerAtGeo("Borawewa Sri Lanka");
addMarkerAtGeo("Jamuguri India");
addMarkerAtGeo("Tanyongmas Thailand");
addMarkerAtGeo("Silca Peru");
addMarkerAtGeo("yangon (rangoon) Myanmar");
addMarkerAtGeo("Gamalakke South Africa");
addMarkerAtGeo("Abancay province Peru");
addMarkerAtGeo("Ressano Garcia Mozambique");
addMarkerAtGeo("Bor Town Sudan");
addMarkerAtGeo("Bucaramanga Colombia");
addMarkerAtGeo("Cotabato Philippines");
addMarkerAtGeo("Kundasala Sri Lanka");
addMarkerAtGeo("Arauquita Colombia");
addMarkerAtGeo("Quilcajasa Peru");
addMarkerAtGeo("Erzurum Turkey");
addMarkerAtGeo("Nagoda Sri Lanka");
addMarkerAtGeo("Witwatersrand area South Africa");
addMarkerAtGeo("Samore Colombia");
addMarkerAtGeo("Ahangama Sri Lanka");
addMarkerAtGeo("Santiago de Pupuja Peru");
addMarkerAtGeo("Yei Sudan");
addMarkerAtGeo("Weligama Sri Lanka");
addMarkerAtGeo("Salem Village Israel");
addMarkerAtGeo("Laggala Sri Lanka");
addMarkerAtGeo("Pinillos Colombia");
addMarkerAtGeo("Kumi district Uganda");
addMarkerAtGeo("Lacor Uganda");
addMarkerAtGeo("Torit Sudan");
addMarkerAtGeo("Battambang Prov. Cambodia");
addMarkerAtGeo("Santa Rita Colombia");
addMarkerAtGeo("El-Bireh West Bank and Gaza Strip");
addMarkerAtGeo("Acevedo Colombia");
addMarkerAtGeo("Jaffna Sri Lanka");
addMarkerAtGeo("Bangkok Thailand");
addMarkerAtGeo("Huacho Peru");
addMarkerAtGeo("Kizilsu Area Turkey");
addMarkerAtGeo("Mushawa Village Zambia");
addMarkerAtGeo("Dhariwal Kalan India");
addMarkerAtGeo("Wanni Sri Lanka");
addMarkerAtGeo("Mahisabari India");
addMarkerAtGeo("Cudi Mountain Turkey");
addMarkerAtGeo("Kalukgolla Sri Lanka");
addMarkerAtGeo("Bikfayya Lebanon");
addMarkerAtGeo("Uchiza Peru");
addMarkerAtGeo("Lisama Colombia");
addMarkerAtGeo("Dhaka Pakistan");
addMarkerAtGeo("La Linea Colombia");
addMarkerAtGeo("Carmen Philippines");
addMarkerAtGeo("Upper Huallaga river Valley Peru");
addMarkerAtGeo("Baddowal India");
addMarkerAtGeo("Ahmadgarh India");
addMarkerAtGeo("Tolima Dept. Colombia");
addMarkerAtGeo("Tunja Colombia");
addMarkerAtGeo("Tamoun Israel");
addMarkerAtGeo("Narathiwai Province Thailand");
addMarkerAtGeo("Kaduwela Sri Lanka");
addMarkerAtGeo("Walasmulla Sri Lanka");
addMarkerAtGeo("Nechi Colombia");
addMarkerAtGeo("Carmen Town Philippines");
addMarkerAtGeo("La Rochela Colombia");
addMarkerAtGeo("Cairo Egypt");
addMarkerAtGeo("Chwindi devi India");
addMarkerAtGeo("South Catabato Province Philippines");
addMarkerAtGeo("Ferozepur District India");
addMarkerAtGeo("Ludhiana District India");
addMarkerAtGeo("Matugama Sri Lanka");
addMarkerAtGeo("Kinavane Mozambique");
addMarkerAtGeo("Motepuez Mozambique");
addMarkerAtGeo("Khargone India");
addMarkerAtGeo("Bangani Namibia");
addMarkerAtGeo("Panbari India");
addMarkerAtGeo("Moratuwa Sri Lanka");
addMarkerAtGeo("ludhiana India");
addMarkerAtGeo("Karuwalagaswewe Sri Lanka");
addMarkerAtGeo("Akurugoda Sri Lanka");
addMarkerAtGeo("Seapani India");
addMarkerAtGeo("Bie Province Angola");
addMarkerAtGeo("Asmara Ethiopia");
addMarkerAtGeo("Nusaybin Turkey");
addMarkerAtGeo("bairabil India");
addMarkerAtGeo("Sincelejo Colombia");
addMarkerAtGeo("Risaralda Dept Colombia");
addMarkerAtGeo("Mukalvando Angola");
addMarkerAtGeo("Jalandhar District India");
addMarkerAtGeo("Al Jahiliyah Lebanon");
addMarkerAtGeo("Mulkirigala Sri Lanka");
addMarkerAtGeo("Macari Peru");
addMarkerAtGeo("Junin Dept, Jauja Province Peru");
addMarkerAtGeo("Uda Beragama Sri Lanka");
addMarkerAtGeo("Delhi India");
addMarkerAtGeo("Mohnyin Thailand");
addMarkerAtGeo("Trujillo Peru");
addMarkerAtGeo("Udalgiri area India");
addMarkerAtGeo("Dirsekli Turkey");
addMarkerAtGeo("Massin Philippines");
addMarkerAtGeo("Lebauese Forces Militia Lebanon");
addMarkerAtGeo("Zamboanga city Philippines");
addMarkerAtGeo("Bukidon Province Philippines");
addMarkerAtGeo("Antioyvia Dept. Colombia");
addMarkerAtGeo("Risaralda Dept. Colombia");
addMarkerAtGeo("Mersin Turkey");
addMarkerAtGeo("Ricran Peru");
addMarkerAtGeo("Villavicencio Colombia");
addMarkerAtGeo("Cajamarquillo Peru");
addMarkerAtGeo("La Zolla El Salvador");
addMarkerAtGeo("Otoboi Uganda");
addMarkerAtGeo("Dikbiyik Turkey");
addMarkerAtGeo("Negombo District Sri Lanka");
addMarkerAtGeo("Bellville South Africa");
addMarkerAtGeo("Satipo Peru");
addMarkerAtGeo("Ludhiana India");
addMarkerAtGeo("Rionegro Colombia");
addMarkerAtGeo("Katukeliyawa Sri Lanka");
addMarkerAtGeo("El Bireh West Bank and Gaza Strip");
addMarkerAtGeo("Pakwach Uganda");
addMarkerAtGeo("Mamelodi South Africa");
addMarkerAtGeo("Kangraiyan India");
addMarkerAtGeo("Weli Oya Village Sri Lanka");
addMarkerAtGeo("Saiburi District Thailand");
addMarkerAtGeo("Port Elizabeth South Africa");
addMarkerAtGeo("Jauja Province Peru");
addMarkerAtGeo("gosaigon subdivision India");
addMarkerAtGeo("La Putana Colombia");
addMarkerAtGeo("Nazareth Israel");
addMarkerAtGeo("Bachalor India");
addMarkerAtGeo("Soragune Sri Lanka");
addMarkerAtGeo("Cukurca Turkey");
addMarkerAtGeo("Taraza Colombia");
addMarkerAtGeo("Amritsan District India");
addMarkerAtGeo("Colombo (Borella area) Sri Lanka");
addMarkerAtGeo("Isabela (Basilan Island) Philippines");
addMarkerAtGeo("Yauyos Peru");
addMarkerAtGeo("Mohali India");
addMarkerAtGeo("Buluan Philippines");
addMarkerAtGeo("Moga India");
addMarkerAtGeo("Diyarbakir Turkey");
addMarkerAtGeo("Dinanagar India");
addMarkerAtGeo("Hambantota Sri Lanka");
addMarkerAtGeo("Elviti El Salvador");
addMarkerAtGeo("Yaylipinar Turkey");
addMarkerAtGeo("Yauricocha Peru");
addMarkerAtGeo("Cudi Mountain area Turkey");
addMarkerAtGeo("Alto Huallaga Peru");
addMarkerAtGeo("Akhrur India");
addMarkerAtGeo("Sarare Colombia");
addMarkerAtGeo("Meegahatenna Sri Lanka");
addMarkerAtGeo("Beit Likya West Bank and Gaza Strip");
addMarkerAtGeo("Chilcas Peru");
addMarkerAtGeo("Ginnot Shomron Israel");
addMarkerAtGeo("Saral Amanat Khan India");
addMarkerAtGeo("Ratanhira India");
addMarkerAtGeo("Baliveren Turkey");
addMarkerAtGeo("Vicus Peru");
addMarkerAtGeo("Nakodar India");
addMarkerAtGeo("Huechuraba Chile");
addMarkerAtGeo("Laudium South Africa");
addMarkerAtGeo("Bhai Ladhu India");
addMarkerAtGeo("Culluchaca Peru");
addMarkerAtGeo("Aguaytia Peru");
addMarkerAtGeo("Rano Philippines");
addMarkerAtGeo("Tete Mozambique");
addMarkerAtGeo("King Willliams Town South Africa");
addMarkerAtGeo("UCO Peru");
addMarkerAtGeo("Pereira Colombia");
addMarkerAtGeo("Nabulus West Bank and Gaza Strip");
addMarkerAtGeo("Quinti Peru");
addMarkerAtGeo("Abra Lebanon");
addMarkerAtGeo("Espiritu Peru");
addMarkerAtGeo("El Boqueron del Padre del Abad Peru");
addMarkerAtGeo("Nzero Mozambique");
addMarkerAtGeo("Sohara Village India");
addMarkerAtGeo("Naledi South Africa");
addMarkerAtGeo("Huancayo Dept Peru");
addMarkerAtGeo("Cumaral Colombia");
addMarkerAtGeo("Younis West Bank and Gaza Strip");
addMarkerAtGeo("Nhamatanda Mozambique");
addMarkerAtGeo("Wijerama Mawatha Sri Lanka");
addMarkerAtGeo("Welimada Sri Lanka");
addMarkerAtGeo("Acolla Peru");
addMarkerAtGeo("Cosquin Argentina");
addMarkerAtGeo("Bhantinda India");
addMarkerAtGeo("Lower Siring Philippines");
addMarkerAtGeo("Kufr Tult West Bank and Gaza Strip");
addMarkerAtGeo("Subpanjalla Peru");
addMarkerAtGeo("Kiwulla Sri Lanka");
addMarkerAtGeo("Digalhera Sri Lanka");
addMarkerAtGeo("Fakirgram India");
addMarkerAtGeo("Magangue Colombia");
addMarkerAtGeo("Vijaypura India");
addMarkerAtGeo("Andahua Peru");
addMarkerAtGeo("Lopez Philippines");
addMarkerAtGeo("Serrania de Perija * Colombia");
addMarkerAtGeo("Shabqadar Pakistan");
addMarkerAtGeo("Bongaigaon India");
addMarkerAtGeo("Tirappane Sri Lanka");
addMarkerAtGeo("Santa Barbara Colombia");
addMarkerAtGeo("Khagrachari Hill District Bangladesh");
addMarkerAtGeo("Badulla Sri Lanka");
addMarkerAtGeo("Sao Paolo Brazil");
addMarkerAtGeo("Chambimbal area Colombia");
addMarkerAtGeo("Punjab state India");
addMarkerAtGeo("San Luis de Shuaro Peru");
addMarkerAtGeo("Barrira Philippines");
addMarkerAtGeo("Cuanza-Notre Prov Angola");
addMarkerAtGeo("Kampala Uganda");
addMarkerAtGeo("Afobaka dam Suriname");
addMarkerAtGeo("Tripura State India");
addMarkerAtGeo("La Pampa Argentina");
addMarkerAtGeo("Tinsukia India");
addMarkerAtGeo("Callao Peru");
addMarkerAtGeo("Pisco Peru");
addMarkerAtGeo("Kawdulla Sri Lanka");
addMarkerAtGeo("Trincomalee Dist. Sri Lanka");
addMarkerAtGeo("Nhamatsane Mozambique");
addMarkerAtGeo("Elmabahce Turkey");
addMarkerAtGeo("Cape Town South Africa");
addMarkerAtGeo("Apure State Venezuela");
addMarkerAtGeo("Medelin Colombia");
addMarkerAtGeo("Covenas Colombia");
addMarkerAtGeo("Andean Foothills Peru");
addMarkerAtGeo("new delhi India");
addMarkerAtGeo("kashmir state India");
addMarkerAtGeo("Kumburupittiya Sri Lanka");
addMarkerAtGeo("Angunukolapalessa Sri Lanka");
addMarkerAtGeo("Thokoza South Africa");
addMarkerAtGeo("Piscobamba Peru");
addMarkerAtGeo("Soroti Uganda");
addMarkerAtGeo("Wear Amritsar India");
addMarkerAtGeo("Tinte Peru");
addMarkerAtGeo("Atapallan Peru");
addMarkerAtGeo("Rovira Colombia");
addMarkerAtGeo("Ambo Peru");
addMarkerAtGeo("Davao Del Sur Prov. Philippines");
addMarkerAtGeo("Tarn Taran India");
addMarkerAtGeo("Jandiala County India");
addMarkerAtGeo("Saqqez Iran");
addMarkerAtGeo("Las Hamacas Nicaragua");
addMarkerAtGeo("Pilpichaca Peru");
addMarkerAtGeo("Gorkajuli India");
addMarkerAtGeo("Acosvinchos Peru");
addMarkerAtGeo("Tantarpata Peru");
addMarkerAtGeo("Transkei South Africa");
addMarkerAtGeo("sringagar India");
addMarkerAtGeo("Ra-nge District Thailand");
addMarkerAtGeo("San Francisco Philippines");
addMarkerAtGeo("Monposina Colombia");
addMarkerAtGeo("Burala India");
addMarkerAtGeo("Amritstar district India");
addMarkerAtGeo("uri India");
addMarkerAtGeo("Mann India");
addMarkerAtGeo("Wablus West Bank and Gaza Strip");
addMarkerAtGeo("Red Arch Northern Ireland");
addMarkerAtGeo("Ramin Israel");
addMarkerAtGeo("Pa-an Myanmar");
addMarkerAtGeo("Norte de Santander Dept Colombia");
addMarkerAtGeo("Hichinga Peru");
addMarkerAtGeo("Nyanga Zimbabwe");
addMarkerAtGeo("near Jerusalem Israel");
addMarkerAtGeo("Elpitiya Sri Lanka");
addMarkerAtGeo("La Ceiba El Salvador");
addMarkerAtGeo("Lahore Pakistan");
addMarkerAtGeo("Imperial Peru");
addMarkerAtGeo("Imphal India");
addMarkerAtGeo("Tenjo Colombia");
addMarkerAtGeo("Hatmana Sri Lanka");
addMarkerAtGeo("Machahuay Peru");
addMarkerAtGeo("Amritsar City India");
addMarkerAtGeo("Sariaya Philippines");
addMarkerAtGeo("Ratmalana Sri Lanka");
addMarkerAtGeo("Mahmudpur India");
addMarkerAtGeo("Belhar South Africa");
addMarkerAtGeo("Hiniduma Sri Lanka");
addMarkerAtGeo("Beira Mozambique");
addMarkerAtGeo("Pichanaki Peru");
addMarkerAtGeo("Miraflores Peru");
addMarkerAtGeo("Kandy Sri Lanka");
addMarkerAtGeo("Kottegoda Sri Lanka");
addMarkerAtGeo("Buenos Aires Argentina");
addMarkerAtGeo("Menongue City Angola");
addMarkerAtGeo("Petauke Zambia");
addMarkerAtGeo("Ventanilla Peru");
addMarkerAtGeo("Lefkosa Cyprus");
addMarkerAtGeo("Colquemarca Peru");
addMarkerAtGeo("Nicosia Cyprus");
addMarkerAtGeo("Guardaspur Dist India");
addMarkerAtGeo("Stutterheim South Africa");
addMarkerAtGeo("Baghaichhari Bangladesh");
addMarkerAtGeo("Lingelethu West South Africa");
addMarkerAtGeo("Huancayo Province Peru");
addMarkerAtGeo("Yinyon village Myanmar");
addMarkerAtGeo("Weibe* South Africa");
addMarkerAtGeo("Gampaha Sri Lanka");
addMarkerAtGeo("Vavuniya Area Sri Lanka");
addMarkerAtGeo("Matanog Philippines");
addMarkerAtGeo("Usibampa Peru");
addMarkerAtGeo("Muqui Peru");
addMarkerAtGeo("Klaaskreek Suriname");
addMarkerAtGeo("Piura Peru");
addMarkerAtGeo("batala India");
addMarkerAtGeo("Munani Peru");
addMarkerAtGeo("Talcahuano Chile");
addMarkerAtGeo("Fortul Colombia");
addMarkerAtGeo("Puerto Nare Colombia");
addMarkerAtGeo("Gossaigoan India");
addMarkerAtGeo("Hayatabad Pakistan");
addMarkerAtGeo("Maceo Colombia");
addMarkerAtGeo("Occidental Mindoro Prov. Philippines");
addMarkerAtGeo("Igdir Turkey");
addMarkerAtGeo("San Pedro de Loc Peru");
addMarkerAtGeo("Hnitkarin Village Myanmar");
addMarkerAtGeo("Huari Pampa Peru");
addMarkerAtGeo("Huamaguilla Peru");
addMarkerAtGeo("Windhoek Namibia");
addMarkerAtGeo("Puerto Callao Peru");
addMarkerAtGeo("Jotapuquio Peru");
addMarkerAtGeo("Dodampe Sri Lanka");
addMarkerAtGeo("Tuao Philippines");
addMarkerAtGeo("Jibrayel Lebanon");
addMarkerAtGeo("Siyambalanduwa Sri Lanka");
addMarkerAtGeo("Pallebage Sri Lanka");
addMarkerAtGeo("bardeta India");
addMarkerAtGeo("Merida Venezuela");
addMarkerAtGeo("Gujarpur India");
addMarkerAtGeo("Piliyandala Sri Lanka");
addMarkerAtGeo("Rawal Pindi Pakistan");
addMarkerAtGeo("Uitenhage South Africa");
addMarkerAtGeo("Mazro Turkey");
addMarkerAtGeo("Johannesburg South Africa");
addMarkerAtGeo("Firozapur village India");
addMarkerAtGeo("Sandhurst South Africa");
addMarkerAtGeo("Thaton Myanmar");
addMarkerAtGeo("Concepcion Chile");
addMarkerAtGeo("Valparaiso Chile");
addMarkerAtGeo("Moengo Suriname");
addMarkerAtGeo("Pahala Sri Lanka");
addMarkerAtGeo("Sanagoran Peru");
addMarkerAtGeo("Quinua Peru");
addMarkerAtGeo("Huaraz Province Peru");
addMarkerAtGeo("Akarai Pattu Sri Lanka");
addMarkerAtGeo("Quinches Peru");
addMarkerAtGeo("Ongwediva Namibia");
addMarkerAtGeo("Caucasia Colombia");
addMarkerAtGeo("Beit Sahour Israel");
addMarkerAtGeo("Wiloluwa Sri Lanka");
addMarkerAtGeo("Tarija Bolivia");
addMarkerAtGeo("Chiriguana Colombia");
addMarkerAtGeo("Springs South Africa");
addMarkerAtGeo("Pervari Turkey");
addMarkerAtGeo("Gloriapatria Peru");
addMarkerAtGeo("Mexico-Guatemala Border Guatemala");
addMarkerAtGeo("Chacca Huanta Peru");
addMarkerAtGeo("Ipambamba Peru");
addMarkerAtGeo("Mantaro Valley Peru");
addMarkerAtGeo("Welioya Sri Lanka");
addMarkerAtGeo("Macho Mono Colombia");
addMarkerAtGeo("Katzir Israel");
addMarkerAtGeo("Yaluca Nicaragua");
addMarkerAtGeo("Chalhuanca Peru");
addMarkerAtGeo("Temuco Chile");
addMarkerAtGeo("Kathunangal India");
addMarkerAtGeo("Alto Paujil * Colombia");
addMarkerAtGeo("Khera India");
addMarkerAtGeo("Nalbari District India");
addMarkerAtGeo("Nablus West Bank and Gaza Strip");
addMarkerAtGeo("Mulqui Peru");
addMarkerAtGeo("La Pata de la Gallina El Salvador");
addMarkerAtGeo("Cali Colombia");
addMarkerAtGeo("Dakshin Kanengdesha India");
addMarkerAtGeo("Medirigiriya Sri Lanka");
addMarkerAtGeo("Southern Pakistan Pakistan");
addMarkerAtGeo("Palloa Peru");
addMarkerAtGeo("Santa Maria Delvalle Peru");
addMarkerAtGeo("Ciskei South Africa");
addMarkerAtGeo("Puerto Lopez Colombia");
addMarkerAtGeo("Transvaal Prov. South Africa");
addMarkerAtGeo("Chiuta Mozambique");
addMarkerAtGeo("Bartam India");
addMarkerAtGeo("Maputo Zambia");
addMarkerAtGeo("Canhoca Angola");
addMarkerAtGeo("Suravaram India");
addMarkerAtGeo("Pervavi Turkey");
addMarkerAtGeo("Dondo Mozambique");
addMarkerAtGeo("Coliat Philippines");
addMarkerAtGeo("Amritsar Area India");
addMarkerAtGeo("Vavunitya Dist. Sri Lanka");
addMarkerAtGeo("Bosphorus Strait Turkey");
addMarkerAtGeo("Banate Philippines");
addMarkerAtGeo("Nampala Province Mozambique");
addMarkerAtGeo("Tammun Israel");
addMarkerAtGeo("Arauca Department Colombia");
addMarkerAtGeo("Badulla District Sri Lanka");
addMarkerAtGeo("Espinal Colombia");
addMarkerAtGeo("Daet Philippines");
addMarkerAtGeo("Kullapadu-Mullaitivu Sri Lanka");
addMarkerAtGeo("La Mascota El Salvador");
addMarkerAtGeo("Cachira Colombia");
addMarkerAtGeo("Oroya Peru");
addMarkerAtGeo("Choclococha Peru");
addMarkerAtGeo("Rio Blanco Colombia");
addMarkerAtGeo("Mocuba Mozambique");
addMarkerAtGeo("Khasawal India");
addMarkerAtGeo("Santa Marta Colombia");
addMarkerAtGeo("El Tamal Guatemala");
addMarkerAtGeo("Guayaquil Ecuador");
addMarkerAtGeo("Moraketiya Sri Lanka");
addMarkerAtGeo("Garcia Rovira Colombia");
addMarkerAtGeo("Puyuhuan Peru");
addMarkerAtGeo("Colpa Peru");
addMarkerAtGeo("San Mateo Peru");
addMarkerAtGeo("Santander Dept Colombia");
addMarkerAtGeo("Dhreli India");
addMarkerAtGeo("Quinota Peru");
addMarkerAtGeo("Chavalakadai Sri Lanka");
addMarkerAtGeo("assam state India");
addMarkerAtGeo("San Juan Bautista Peru");
addMarkerAtGeo("Apartado Colombia");
addMarkerAtGeo("Korat Thailand");
addMarkerAtGeo("El-Minya Egypt");
addMarkerAtGeo("Kelaniya Sri Lanka");
addMarkerAtGeo("Amritsar District India");
addMarkerAtGeo("Jhuliwala India");
addMarkerAtGeo("Afobakka Suriname");
addMarkerAtGeo("Iranai Sri Lanka");
addMarkerAtGeo("Ankara Turkey");
addMarkerAtGeo("Nyun Combe Suriname");
addMarkerAtGeo("Israel-Syria-Jordan border Israel");
addMarkerAtGeo("Santo Tomas Peru");
addMarkerAtGeo("Hakkari prov. Turkey");
addMarkerAtGeo("El Colorado Peru");
addMarkerAtGeo("Callenueva Colombia");
addMarkerAtGeo("Taytay Town Philippines");
addMarkerAtGeo("Mahiyangama Sri Lanka");
addMarkerAtGeo("Achi Colombia");
addMarkerAtGeo("Cachachi Peru");
addMarkerAtGeo("Gangarampur India");
addMarkerAtGeo("Negros Island Philippines");
addMarkerAtGeo("Tananta Palo Blanco Peru");
addMarkerAtGeo("Kodagoda Sri Lanka");
addMarkerAtGeo("Urumiye Iran");
addMarkerAtGeo("Jaffija* Sri Lanka");
addMarkerAtGeo("Bethlehem West Bank and Gaza Strip");
addMarkerAtGeo("Taplada de Ludin Peru");
addMarkerAtGeo("chintpurani India");
addMarkerAtGeo("Istanbul Turkey");
addMarkerAtGeo("Orurillo Peru");
addMarkerAtGeo("Bene Beraq Israel");
addMarkerAtGeo("Katleheng South Africa");
addMarkerAtGeo("El Tablon El Salvador");
addMarkerAtGeo("Las Conchas Colombia");
addMarkerAtGeo("Fatehpur India");
addMarkerAtGeo("Etale Namibia");
addMarkerAtGeo("Diepkloof South Africa");
addMarkerAtGeo("runikhata India");
addMarkerAtGeo("Bahirkhedi India");
addMarkerAtGeo("Bajo Simacota * Colombia");
addMarkerAtGeo("Tuba Philippines");
addMarkerAtGeo("Buenaventura Colombia");
addMarkerAtGeo("Pattaya Thailand");
addMarkerAtGeo("Zamboanga Philippines");
addMarkerAtGeo("Meta Dept. Colombia");
addMarkerAtGeo("Ludhiana City India");
addMarkerAtGeo("Bago City Philippines");
addMarkerAtGeo("Davao Philippines");
addMarkerAtGeo("nalbari district India");
addMarkerAtGeo("Khartoum Sudan");
addMarkerAtGeo("Sonada India");
addMarkerAtGeo("Chokwe Mozambique");
addMarkerAtGeo("Amarilis Peru");
addMarkerAtGeo("Andean Highlands Peru");
addMarkerAtGeo("Tissamaharama Sri Lanka");
addMarkerAtGeo("Upper Siring Philippines");
addMarkerAtGeo("Masindi Town Uganda");
addMarkerAtGeo("Ressado Garcia Mozambique");
addMarkerAtGeo("Callejon de Huaylas Peru");
addMarkerAtGeo("Kurunegele District Sri Lanka");
addMarkerAtGeo("Jagtial India");
addMarkerAtGeo("Kurunegala Dist. Sri Lanka");
addMarkerAtGeo("Maguindarao Province Philippines");
addMarkerAtGeo("Bar Elias Lebanon");
addMarkerAtGeo("Talca Chile");
addMarkerAtGeo("Kabarwala India");
addMarkerAtGeo("Las Trochas Colombia");
addMarkerAtGeo("Boqueron Colombia");
addMarkerAtGeo("La Union Colombia");
addMarkerAtGeo("Morawakakanda Sri Lanka");
addMarkerAtGeo("Tarma Peru");
addMarkerAtGeo("Zamboanga City Philippines");
addMarkerAtGeo("Khaldah Lebanon");
addMarkerAtGeo("Huacrachuco Peru");
addMarkerAtGeo("Currulao Colombia");
addMarkerAtGeo("Khagrachari District Bangladesh");
addMarkerAtGeo("Boyaca Dept Colombia");
addMarkerAtGeo("Talanta zone, AITO Huallaga Peru");
addMarkerAtGeo("Sri Lanka Sri Lanka");
addMarkerAtGeo("Kyondo Myanmar");
addMarkerAtGeo("San Juan de Llanac Peru");
addMarkerAtGeo("Naples and Rome Italy");
addMarkerAtGeo("Macomia Mozambique");
addMarkerAtGeo("sundaridia India");
addMarkerAtGeo("Paveh Iran");
addMarkerAtGeo("City not given South Africa");
addMarkerAtGeo("San Pedro de Chonpampa Peru");
addMarkerAtGeo("Yali Colombia");
addMarkerAtGeo("Pessene Mozambique");
addMarkerAtGeo("Peradeniya Sri Lanka");
addMarkerAtGeo("rangoon Myanmar");
addMarkerAtGeo("Kiryat Malachi Israel");
addMarkerAtGeo("Khan Yunus West Bank and Gaza Strip");
addMarkerAtGeo("Maputo Mozambique");
addMarkerAtGeo("Beliatta Sri Lanka");
addMarkerAtGeo("Peshawar Pakistan");
addMarkerAtGeo("El Playon Colombia");
addMarkerAtGeo("Maria La Baja Colombia");
addMarkerAtGeo("Khagrachari Hills Bangladesh");
addMarkerAtGeo("Hobo Colombia");
addMarkerAtGeo("Monteria Colombia");
addMarkerAtGeo("nadu state India");
addMarkerAtGeo("KwaThema South Africa");
addMarkerAtGeo("dhaka Bangladesh");
addMarkerAtGeo("ujani dam India");
addMarkerAtGeo("Lima Peru");
addMarkerAtGeo("Gampola Sri Lanka");
addMarkerAtGeo("Quito Ecuador");
addMarkerAtGeo("Huanta Peru");
addMarkerAtGeo("Tame Colombia");
addMarkerAtGeo("Kawkareik township Myanmar");
addMarkerAtGeo("Barranca Peru");
addMarkerAtGeo("Kokrajhar District India");
addMarkerAtGeo("Suriyawewa Sri Lanka");
addMarkerAtGeo("Imaduwa Sri Lanka");
addMarkerAtGeo("Tuabo Colombia");
addMarkerAtGeo("Gothrai India");
addMarkerAtGeo("Izmir Turkey");
addMarkerAtGeo("Kafr Saffa Israel");
addMarkerAtGeo("Ocana Colombia");
addMarkerAtGeo("Tsavo West Kenya");
addMarkerAtGeo("La Serena Chile");
addMarkerAtGeo("Durban South Africa");
addMarkerAtGeo("Chang Village India");
addMarkerAtGeo("Nittambuwa Sri Lanka");
addMarkerAtGeo("Palampattu Sri Lanka");
addMarkerAtGeo("chittagong Bangladesh");
addMarkerAtGeo("Pachitea River Peru");
addMarkerAtGeo("Malibigha India");
addMarkerAtGeo("Kuiripetha India");
addMarkerAtGeo("Tarma Province Peru");
addMarkerAtGeo("Memba Mozambique");
addMarkerAtGeo("Karativu Sri Lanka");
addMarkerAtGeo("Panadura Sri Lanka");
addMarkerAtGeo("Cardanqui Peru");
addMarkerAtGeo("Chun India");
addMarkerAtGeo("Pilimatalawa Sri Lanka");
addMarkerAtGeo("Huancavelica Peru");
addMarkerAtGeo("Marjayoun Lebanon");
addMarkerAtGeo("La Belleza Colombia");
addMarkerAtGeo("Boyagodayaya Sri Lanka");
addMarkerAtGeo("Berlin Colombia");
addMarkerAtGeo("Batticalo Sri Lanka");
addMarkerAtGeo("Kokrajhar district India");
addMarkerAtGeo("Rosario Peru");
addMarkerAtGeo("Rangamati Dist. Bangladesh");
addMarkerAtGeo("Hopton Estate Sri Lanka");
addMarkerAtGeo("Tammum Israel");
addMarkerAtGeo("Gaza strip West Bank and Gaza Strip");
addMarkerAtGeo("Balia Village India");
addMarkerAtGeo("Canto Grande Peru");
addMarkerAtGeo("La Guaria Colombia");
addMarkerAtGeo("Chiare District Peru");
addMarkerAtGeo("Huertas Peru");
addMarkerAtGeo("Morawaka Sri Lanka");
addMarkerAtGeo("Azangaro Province Peru");
addMarkerAtGeo("Huarpacha Peru");
addMarkerAtGeo("Punewa Sri Lanka");
addMarkerAtGeo("Lonqavi Chile");
addMarkerAtGeo("Lota Chile");
addMarkerAtGeo("Bushertala India");
addMarkerAtGeo("Obuke India");
addMarkerAtGeo("Kafr Danis Lebanon");
addMarkerAtGeo("Mardin Turkey");
addMarkerAtGeo("Rhino Camp Uganda");
addMarkerAtGeo("Colombo Sri Lanka");
addMarkerAtGeo("Gampaha District Sri Lanka");
addMarkerAtGeo("Neeraveli Sri Lanka");
addMarkerAtGeo("Chincayllapa Peru");
addMarkerAtGeo("Sallalli Peru");
addMarkerAtGeo("Eldoret Kenya");
addMarkerAtGeo("andhra pradesh state India");
addMarkerAtGeo("Malabe Sri Lanka");
addMarkerAtGeo("Danktal India");
addMarkerAtGeo("Jhenaidah District Bangladesh");
addMarkerAtGeo("Batala India");
addMarkerAtGeo("Mirakut India");
addMarkerAtGeo("Kiryat Shmona Israel");
addMarkerAtGeo("Pasig Philippines");
addMarkerAtGeo("Santa Lucia Peru");
addMarkerAtGeo("Bentota Sri Lanka");
addMarkerAtGeo("Movene* Mozambique");
addMarkerAtGeo("Paramonga Peru");
addMarkerAtGeo("Los Pozos El Salvador");
addMarkerAtGeo("Rosh Haniqra Israel");
addMarkerAtGeo("Sanchez Carrion Peru");
addMarkerAtGeo("El Patrero Colombia");
addMarkerAtGeo("Pervari Township Turkey");
addMarkerAtGeo("Moshav Ram On Israel");
addMarkerAtGeo("Bahcesaray Turkey");
addMarkerAtGeo("San Marcos District Peru");
addMarkerAtGeo("San Pedro De Huacarpana Peru");
addMarkerAtGeo("Sao Paulo Brazil");
addMarkerAtGeo("Cerete Colombia");
addMarkerAtGeo("Katlehong South Africa");
addMarkerAtGeo("Trinidad Colombia");
addMarkerAtGeo("Huancayo Peru");
addMarkerAtGeo("Kandy town Sri Lanka");
