addMarkerAtLatLng(48.856614,2.352222);
addMarkerAtLatLng(-21.124258,164.900448);
addMarkerAtLatLng(13.99,-88.758);
addMarkerAtLatLng(41.479312,2.319244);
addMarkerAtLatLng(13.85077,-88.90406);
addMarkerAtLatLng(14.09396,-88.889278);
addMarkerAtLatLng(13.647645,-88.910848);
addMarkerAtLatLng(12.9319444,-86.1952778);
addMarkerAtLatLng(13.37316,-86.09744);
addMarkerAtLatLng(54.536706,-6.70361);
addMarkerAtLatLng(43.523153,-1.485858);
addMarkerAtLatLng(47.976575,-122.206419);
addMarkerAtLatLng(42.231356,-8.712447);
addMarkerAtLatLng(35.871435,128.601445);
addMarkerAtLatLng(11.7016222556,-84.330581665);
addMarkerAtLatLng(42.567651,8.757222);
addMarkerAtLatLng(40.840097,14.251636);
addMarkerAtLatLng(13.84222,-89.09694);
addMarkerAtLatLng(13.7322222,-89.3741667);
addMarkerAtLatLng(25.728985,-80.237419);
addMarkerAtLatLng(13.808917,-89.228637);
addMarkerAtLatLng(13.447063,-88.556531);
addMarkerAtLatLng(54.57634,-5.917178);
addMarkerAtLatLng(13.842778,-89.4472222);
addMarkerAtLatLng(43.663739,7.14882);
addMarkerAtLatLng(-20.937888,165.333543);
addMarkerAtLatLng(52.585728,-2.129251);
addMarkerAtLatLng(48.703158,9.653999);
addMarkerAtLatLng(16.2411,-61.5331);
addMarkerAtLatLng(40.056318,0.065654);
addMarkerAtLatLng(43.492949,-1.474841);
addMarkerAtLatLng(13.89271,-88.043983);
addMarkerAtLatLng(54.347539,-6.656108);
addMarkerAtLatLng(13.9213889,-89.845);
addMarkerAtLatLng(50.732674,7.096299);
addMarkerAtLatLng(13.23464,-86.233589);
addMarkerAtLatLng(43.344167,-3.006389);
addMarkerAtLatLng(13.835,-89.2744444);
addMarkerAtLatLng(53.553813,9.991586);
addMarkerAtLatLng(12.9304838128,-87.0676383972);
addMarkerAtLatLng(15.587227,-87.891792);
addMarkerAtLatLng(35.776608,140.318781);
addMarkerAtLatLng(47.36865,8.539182);
addMarkerAtLatLng(53.410777,-2.977838);
addMarkerAtLatLng(43.370873,-8.395835);
addMarkerAtLatLng(13.733353,-89.216671);
addMarkerAtLatLng(43.416667,-2.933333);
addMarkerAtLatLng(13.602292,-88.928425);
addMarkerAtLatLng(12.93157,-85.224113);
addMarkerAtLatLng(13.1307067086,-85.9716835022);
addMarkerAtLatLng(51.6798,-3.1368);
addMarkerAtLatLng(43.375421,-8.208693);
addMarkerAtLatLng(42.880447,-8.546303);
addMarkerAtLatLng(13.561665,-88.490093);
addMarkerAtLatLng(13.6170447709,-86.2785286988);
addMarkerAtLatLng(54.706718,-7.592867);
addMarkerAtLatLng(13.9166667,-88.2333333);
addMarkerAtLatLng(51.500152,-0.126236);
addMarkerAtLatLng(51.522752,-0.720214);
addMarkerAtLatLng(54.323924,-5.703051);
addMarkerAtLatLng(13.99417,-89.55972);
addMarkerAtLatLng(43.20752,-2.887839);
addMarkerAtLatLng(13.4833333,-88.4666667);
addMarkerAtLatLng(54.12399,-6.338467);
addMarkerAtLatLng(54.482055,-8.088244);
addMarkerAtLatLng(55.120154,-3.355942);
addMarkerAtLatLng(37.338475,-121.885794);
addMarkerAtLatLng(43.143332,-2.962985);
addMarkerAtLatLng(13.5,-88.35);
addMarkerAtLatLng(52.599859,-2.082837);
addMarkerAtLatLng(37.746798,23.426758);
addMarkerAtLatLng(50.37038,-4.142653);
addMarkerAtLatLng(13.738762,-89.054916);
addMarkerAtLatLng(46.738943,11.63974);
addMarkerAtLatLng(35.685826,139.756684);
addMarkerAtLatLng(52.050812,-1.778433);
addMarkerAtLatLng(35.329197,25.138667);
addMarkerAtLatLng(43.385031,-5.702966);
addMarkerAtLatLng(46.669097,11.163979);
addMarkerAtLatLng(18.203831,-67.146469);
addMarkerAtLatLng(13.7666667,-88.2666667);
addMarkerAtLatLng(13.9491667,-89.7619444);
addMarkerAtLatLng(42.895218,-2.168798);
addMarkerAtLatLng(13.5,-88.8666667);
addMarkerAtLatLng(42.433619,-8.648053);
addMarkerAtLatLng(12.881334,-86.084815);
addMarkerAtLatLng(34.05349,-118.245319);
addMarkerAtLatLng(37.950902,23.641103);
addMarkerAtLatLng(13.85,-88.85);
addMarkerAtLatLng(54.823432,-7.468374);
addMarkerAtLatLng(48.139126,11.580186);
addMarkerAtLatLng(43.488387,-8.222509);
addMarkerAtLatLng(12.19185,-84.101286);
addMarkerAtLatLng(15.50167,-88.02774);
addMarkerAtLatLng(13.7682,-88.129139);
addMarkerAtLatLng(13.35664,-86.26401);
addMarkerAtLatLng(48.208174,16.373819);
addMarkerAtLatLng(13.5,-88.4833333);
addMarkerAtLatLng(43.213776,-3.13149);
addMarkerAtLatLng(36.144911,-5.353252);
addMarkerAtLatLng(13.697393,-88.007249);
addMarkerAtLatLng(42.016854,9.403982);
addMarkerAtLatLng(54.101529,-6.526442);
addMarkerAtLatLng(35.1982,-111.651304);
addMarkerAtLatLng(14.454176,-87.643076);
addMarkerAtLatLng(13.568414,-88.088474);
addMarkerAtLatLng(12.30556,-85.55227);
addMarkerAtLatLng(14.050632,-88.067052);
addMarkerAtLatLng(16.916667,-89.9);
addMarkerAtLatLng(41.355613,2.070432);
addMarkerAtLatLng(13.949826,-88.146348);
addMarkerAtLatLng(43.320812,-1.984447);
addMarkerAtLatLng(14.1166667,-88.9166667);
addMarkerAtLatLng(41.359583,2.099704);
addMarkerAtLatLng(13.91,-89.06972);
addMarkerAtLatLng(43.552847,7.017369);
addMarkerAtLatLng(13.701964,-89.147774);
addMarkerAtLatLng(42.465776,-2.449995);
addMarkerAtLatLng(54.594562,-6.931393);
addMarkerAtLatLng(38.628633,21.412317);
addMarkerAtLatLng(13.557072,-88.349433);
addMarkerAtLatLng(13.184112,-88.414384);
addMarkerAtLatLng(13.707793,-89.348779);
addMarkerAtLatLng(43.38377,-3.738101);
addMarkerAtLatLng(54.371988,-6.551326);
addMarkerAtLatLng(54.597269,-5.930109);
addMarkerAtLatLng(13.7166667,-88.1166667);
addMarkerAtLatLng(54.510893,-6.042726);
addMarkerAtLatLng(13.65,-89.4666667);
addMarkerAtLatLng(13.719546,-88.360633);
addMarkerAtLatLng(13.69288,-89.199161);
addMarkerAtLatLng(39.986068,-0.036024);
addMarkerAtLatLng(54.647865,-6.618718);
addMarkerAtLatLng(13.558889,-88.43);
addMarkerAtLatLng(43.307458,-2.946418);
addMarkerAtLatLng(43.280364,-2.171588);
addMarkerAtLatLng(13.607874,-89.095335);
addMarkerAtLatLng(43.215187,-2.415702);
addMarkerAtLatLng(26.334427,127.805583);
addMarkerAtLatLng(41.11366,-73.407654);
addMarkerAtLatLng(43.3282,-3.031509);
addMarkerAtLatLng(13.880321,-86.1678);
addMarkerAtLatLng(13.653775,-88.681393);
addMarkerAtLatLng(43.696036,7.265592);
addMarkerAtLatLng(43.256963,-2.923441);
addMarkerAtLatLng(15.9250939247,-90.9145393372);
addMarkerAtLatLng(14.62,-90.844167);
addMarkerAtLatLng(13.864829,-88.7494);
addMarkerAtLatLng(38.114633,15.650234);
addMarkerAtLatLng(14.983333,-91.85);
addMarkerAtLatLng(35.159545,126.852601);
addMarkerAtLatLng(11.695904,-84.446147);
addMarkerAtLatLng(41.11887,25.405528);
addMarkerAtLatLng(13.2666667,-88.3166667);
addMarkerAtLatLng(13.48833,-89.32222);
addMarkerAtLatLng(14.634863,-91.14318);
addMarkerAtLatLng(13.536835,-88.780584);
addMarkerAtLatLng(47.237829,6.024054);
addMarkerAtLatLng(33.580412,130.396361);
addMarkerAtLatLng(52.677727,-2.449284);
addMarkerAtLatLng(54.544258,-6.780061);
addMarkerAtLatLng(13.64121,-88.785423);
addMarkerAtLatLng(48.113475,-1.675708);
addMarkerAtLatLng(52.505803,13.331741);
addMarkerAtLatLng(35.77675,140.00079);
addMarkerAtLatLng(41.387917,2.169919);
addMarkerAtLatLng(52.370216,4.895168);
addMarkerAtLatLng(12.9248071502,-85.9729404449);
addMarkerAtLatLng(42.376366,-7.411907);
addMarkerAtLatLng(-22.2758,166.458);
addMarkerAtLatLng(36.054885,-112.122099);
addMarkerAtLatLng(46.947922,7.444608);
addMarkerAtLatLng(42.669927,-2.030906);
addMarkerAtLatLng(43.012087,-7.555851);
addMarkerAtLatLng(14.050872,-88.994625);
addMarkerAtLatLng(12.01048,-84.66631);
addMarkerAtLatLng(35.443708,139.638026);
addMarkerAtLatLng(13.988966,-88.983862);
addMarkerAtLatLng(41.919229,8.738635);
addMarkerAtLatLng(14.609856,-61.068731);
addMarkerAtLatLng(53.282216,-3.055877);
addMarkerAtLatLng(32.778155,-96.795404);
addMarkerAtLatLng(13.6769444,-89.2797222);
addMarkerAtLatLng(13.17318,-84.95545);
addMarkerAtLatLng(41.450137,2.247419);
addMarkerAtLatLng(42.846718,-2.671635);
addMarkerAtLatLng(43.224079,-2.718935);
addMarkerAtLatLng(15.116667,-90.166667);
addMarkerAtLatLng(13.495364,-88.979678);
addMarkerAtLatLng(51.388806,9.766828);
addMarkerAtLatLng(14.15695,-89.011475);
addMarkerAtLatLng(-35.308236,149.124224);
addMarkerAtLatLng(17.760674,-92.594903);
addMarkerAtLatLng(54.42071,-6.443767);
addMarkerAtLatLng(12.614081,-86.752249);
addMarkerAtLatLng(51.435146,6.762691);
addMarkerAtLatLng(13.94861,-87.06361);
addMarkerAtLatLng(40.501906,-3.254799);
addMarkerAtLatLng(46.198392,6.142296);
addMarkerAtLatLng(14.0833,-87.2167);
addMarkerAtLatLng(54.08629,-6.576966);
addMarkerAtLatLng(13.9769444,-89.7525);
addMarkerAtLatLng(14.63558,-89.441467);
addMarkerAtLatLng(37.742578,20.896502);
addMarkerAtLatLng(14.283333,-91.366667);
addMarkerAtLatLng(56.112825,-3.160727);
addMarkerAtLatLng(33.522526,-117.707553);
addMarkerAtLatLng(46.795303,11.935149);
addMarkerAtLatLng(13.544303,-86.165168);
addMarkerAtLatLng(40.674759,-111.280869);
addMarkerAtLatLng(13.564251,-86.02984);
addMarkerAtLatLng(54.18006,-6.33393);
addMarkerAtLatLng(43.296482,5.36978);
addMarkerAtLatLng(13.0620518116,-85.0320642642);
addMarkerAtLatLng(48.066152,-2.967056);
addMarkerAtLatLng(13.578556,-89.2652778);
addMarkerAtLatLng(13.79833,-89.17889);
addMarkerAtLatLng(13.09171,-86.00177);
addMarkerAtLatLng(13.6667,-88.208264);
addMarkerAtLatLng(10.946827,-83.735635);
addMarkerAtLatLng(14.179294,-89.04989);
addMarkerAtLatLng(13.27417,-88.05611);
addMarkerAtLatLng(11.999035,-84.779857);
addMarkerAtLatLng(40.639349,22.944616);
addMarkerAtLatLng(43.118217,-2.413358);
addMarkerAtLatLng(54.645861,-6.745149);
addMarkerAtLatLng(55.129345,-6.663439);
addMarkerAtLatLng(54.600305,-7.298402);
addMarkerAtLatLng(14.664657,-90.82171);
addMarkerAtLatLng(13.222778,-88.1386111);
addMarkerAtLatLng(52.482961,-1.893592);
addMarkerAtLatLng(15.766786,-86.833055);
addMarkerAtLatLng(54.99451,-7.319996);
addMarkerAtLatLng(13.49446,-88.530343);
addMarkerAtLatLng(-22.226847,166.557493);
addMarkerAtLatLng(42.817988,-1.644184);
addMarkerAtLatLng(46.639629,11.564815);
addMarkerAtLatLng(54.842824,-6.667731);
addMarkerAtLatLng(13.420304,-88.571307);
addMarkerAtLatLng(45.070562,7.686619);
addMarkerAtLatLng(51.216667,2.9);
addMarkerAtLatLng(46.600674,11.532986);
addMarkerAtLatLng(41.652943,-4.728381);
addMarkerAtLatLng(54.253718,-7.44106);
addMarkerAtLatLng(13.091683,-86.000314);
addMarkerAtLatLng(35.33045,139.902677);
addMarkerAtLatLng(53.191458,-2.895007);
addMarkerAtLatLng(38.986096,-3.927263);
addMarkerAtLatLng(13.586201,-88.750773);
addMarkerAtLatLng(35.179554,129.075642);
addMarkerAtLatLng(54.077313,-6.608787);
addMarkerAtLatLng(52.192035,-2.223532);
addMarkerAtLatLng(52.023062,8.533072);
addMarkerAtLatLng(13.212326,-86.110558);
addMarkerAtLatLng(13.874575,-88.627779);
addMarkerAtLatLng(50.111445,8.680615);
addMarkerAtLatLng(13.814197,-88.34682);
addMarkerAtLatLng(47.997542,-4.097899);
addMarkerAtLatLng(13.7811111,-89.1186111);
addMarkerAtLatLng(54.409928,-7.172562);
addMarkerAtLatLng(33.766725,-118.192399);
addMarkerAtLatLng(-20.452203,166.617329);
addMarkerAtLatLng(49.35027,8.137919);
addMarkerAtLatLng(14.191665,-89.1706);
addMarkerAtLatLng(52.202544,0.131237);
addMarkerAtLatLng(13.5,-88.9);
addMarkerAtLatLng(9.933333,-84.083333);
addMarkerAtLatLng(54.063074,-6.006978);
addMarkerAtLatLng(50.850335,4.351685);
addMarkerAtLatLng(14.624422,-90.53288);
addMarkerAtLatLng(18.39677,-66.046608);
addMarkerAtLatLng(51.697965,0.110231);
addMarkerAtLatLng(13.496103,-85.916342);
addMarkerAtLatLng(13.06248,-86.44336);
addMarkerAtLatLng(38.725299,-9.150036);
addMarkerAtLatLng(15.987447,-90.784191);
addMarkerAtLatLng(15.408333,-91.147222);
addMarkerAtLatLng(41.656285,-0.876533);
addMarkerAtLatLng(52.220338,6.895964);
addMarkerAtLatLng(13.7,-88.1);
addMarkerAtLatLng(8.994269,-79.518792);
addMarkerAtLatLng(43.054361,-2.333641);
addMarkerAtLatLng(40.01574,-105.279239);
addMarkerAtLatLng(51.603191,6.049197);
addMarkerAtLatLng(-34.928726,138.599945);
addMarkerAtLatLng(12.84265,-87.382867);
addMarkerAtLatLng(41.89052,12.494249);
addMarkerAtLatLng(54.258585,-5.84266);
addMarkerAtLatLng(37.5407,-77.433654);
addMarkerAtLatLng(51.481307,-3.180498);
addMarkerAtLatLng(14.56667,-91.33333);
addMarkerAtLatLng(43.222177,-2.885668);
addMarkerAtLatLng(36.621787,-4.500273);
addMarkerAtLatLng(45.738611,8.979852);
addMarkerAtLatLng(16.633333,-90.183333);
addMarkerAtLatLng(54.659062,-5.735389);
addMarkerAtLatLng(13.818333,-87.9713889);
addMarkerAtLatLng(13.2538889,-88.2477778);
addMarkerAtLatLng(18.495702,-72.473153);
addMarkerAtLatLng(12.318307702,-86.0182540118);
addMarkerAtLatLng(36.616984,-6.358202);
addMarkerAtLatLng(40.030502,-6.088251);
addMarkerAtLatLng(43.124228,5.928);
addMarkerAtLatLng(54.190675,-7.562948);
addMarkerAtLatLng(52.516667,13.4);
addMarkerAtLatLng(14.70208,-91.2506);
addMarkerAtLatLng(19.45,-70.7);
addMarkerAtLatLng(15.98881,-90.7817);
addMarkerAtLatLng(51.192442,5.994695);
addMarkerAtLatLng(54.411953,-6.745731);
addMarkerAtLatLng(13.619026,-88.930144);
addMarkerAtLatLng(25.749238,-80.262949);
addMarkerAtLatLng(55.676075,12.568316);
addMarkerAtLatLng(54.713382,-6.216761);
addMarkerAtLatLng(11.01844,-84.39811);
addMarkerAtLatLng(43.34872,-3.010091);
addMarkerAtLatLng(13.933732,-89.025836);
addMarkerAtLatLng(54.596939,-7.050618);
addMarkerAtLatLng(42.577204,-2.846297);
addMarkerAtLatLng(54.346531,-7.640404);
addMarkerAtLatLng(37.97918,23.716647);
addMarkerAtLatLng(13.466667,-88.183333);
addMarkerAtLatLng(37.566535,126.977969);
addMarkerAtLatLng(13.564954,-84.313618);
addMarkerAtLatLng(18.5391667,-72.335);
addMarkerAtLatLng(13.8333333,-88.7166667);
addMarkerAtLatLng(13.041707,-86.905374);
addMarkerAtLatLng(43.272167,-2.832167);
addMarkerAtLatLng(50.179683,8.508595);
addMarkerAtLatLng(13.52628,-84.89873);
addMarkerAtLatLng(49.941562,11.571023);
addMarkerAtLatLng(12.10629,-85.36452);
addMarkerAtLatLng(13.65917,-89.1675);
addMarkerAtLatLng(54.560124,-5.983657);
addMarkerAtLatLng(19.432608,-99.133207);
addMarkerAtLatLng(43.18418,-2.473289);
addMarkerAtLatLng(43.136978,-2.073914);
addMarkerAtLatLng(14.12458,-89.293171);
addMarkerAtLatLng(13.678837,-89.275187);
addMarkerAtLatLng(14.009286,-88.940189);
addMarkerAtLatLng(42.733795,-1.645333);
addMarkerAtLatLng(13.61177,-88.026466);
addMarkerAtLatLng(51.455313,-2.591902);
addMarkerAtLatLng(42.340009,-7.864641);
addMarkerAtLatLng(43.169068,-2.632655);
addMarkerAtLatLng(54.49051,-7.98751);
addMarkerAtLatLng(18.249015,-66.034034);
addMarkerAtLatLng(43.152273,-2.641978);
addMarkerAtLatLng(12.886513,-85.268628);
addMarkerAtLatLng(14.331414,-89.442393);
addMarkerAtLatLng(45.463681,9.188171);
addMarkerAtLatLng(40.416691,-3.700345);
addMarkerAtLatLng(13.805691,-88.145787);
addMarkerAtLatLng(42.697283,9.450881);
addMarkerAtLatLng(43.297222,-2.991667);
addMarkerAtLatLng(13.5333333,-88.3833333);
addMarkerAtLatLng(13.723925,-88.089839);
addMarkerAtLatLng(13.487179,-88.765032);
addMarkerAtLatLng(13.498952,-89.069988);
addMarkerAtLatLng(43.401586,-3.818161);
addMarkerAtLatLng(13.344322,-88.437463);
addMarkerAtLatLng(13.24111,-87.96);
addMarkerAtLatLng(14.091943,-88.747054);
addMarkerAtLatLng(44.106737,9.829219);
addMarkerAtLatLng(46.496714,11.358008);
addMarkerAtLatLng(41.118663,1.24533);
addMarkerAtLatLng(43.201044,-3.049893);
addMarkerAtLatLng(14.195953,-89.150357);
addMarkerAtLatLng(54.131402,-6.586387);
addMarkerAtLatLng(11.727473,-86.21585);
addMarkerAtLatLng(43.299442,-1.859099);
addMarkerAtLatLng(8.821923,-82.972024);
addMarkerAtLatLng(53.480713,-2.234377);
addMarkerAtLatLng(13.346404,-86.371534);
addMarkerAtLatLng(12.879977959,-85.4120254517);
addMarkerAtLatLng(51.213924,6.780691);
addMarkerAtLatLng(14.180378,-88.892274);
addMarkerAtLatLng(19.700593,-101.186421);
addMarkerAtLatLng(13.68194,-89.8175);
addMarkerAtLatLng(18.46617,-66.106654);
addMarkerAtLatLng(55.030363,-7.215877);
addMarkerAtGeo("Huanuco Peru");
addMarkerAtGeo("Huayranga Peru");
addMarkerAtGeo("Buga Colombia");
addMarkerAtGeo("San Agustin Colombia");
addMarkerAtGeo("Chittagong Bangladesh");
addMarkerAtGeo("Peinsa Myanmar");
addMarkerAtGeo("Nyanga South Africa");
addMarkerAtGeo("Bania India");
addMarkerAtGeo("Chaca Peru");
addMarkerAtGeo("Planadas Colombia");
addMarkerAtGeo("Pitalito Colombia");
addMarkerAtGeo("Providencia Chile");
addMarkerAtGeo("Parachinar District Pakistan");
addMarkerAtGeo("Antonio Philippines");
addMarkerAtGeo("Njoeng Jacobkondre Suriname");
addMarkerAtGeo("Canasgordas Colombia");
addMarkerAtGeo("Gambita Colombia");
addMarkerAtGeo("Srinagar India");
addMarkerAtGeo("Orani Philippines");
addMarkerAtGeo("Cerro de Pasco Peru");
addMarkerAtGeo("Manipur India");
addMarkerAtGeo("Huarancayocc Peru");
addMarkerAtGeo("Bucaramanga Colombia");
addMarkerAtGeo("Siyabalanduwa Sri Lanka");
addMarkerAtGeo("Uraliya Sri Lanka");
addMarkerAtGeo("Unknown Sri Lanka");
addMarkerAtGeo("Ropar India");
addMarkerAtGeo("Colbun Chile");
addMarkerAtGeo("Mullaitivu Sri Lanka");
addMarkerAtGeo("Diepmeadow South Africa");
addMarkerAtGeo("El Portillo El Salvador");
addMarkerAtGeo("Galle Sri Lanka");
addMarkerAtGeo("Quiskapata Peru");
addMarkerAtGeo("Malanwala India");
addMarkerAtGeo("Djibouti * Djibouti");
addMarkerAtGeo("Cilco Peru");
addMarkerAtGeo("Ambala City India");
addMarkerAtGeo("Potchefstroom South Africa");
addMarkerAtGeo("Mendoza Argentina");
addMarkerAtGeo("Kurana Sri Lanka");
addMarkerAtGeo("Traiguen Chile");
addMarkerAtGeo("County Tyrone Northern Ireland");
addMarkerAtGeo("Wewalketiya Sri Lanka");
addMarkerAtGeo("Albina Suriname");
addMarkerAtGeo("Hambantota District Sri Lanka");
addMarkerAtGeo("El Alcazar Colombia");
addMarkerAtGeo("Tarra Colombia");
addMarkerAtGeo("La Puya Colombia");
addMarkerAtGeo("Gilbari India");
addMarkerAtGeo("Dapitan Philippines");
addMarkerAtGeo("Bacoor Philippines");
addMarkerAtGeo("Montclair South Africa");
addMarkerAtGeo("Mukungoli Uganda");
addMarkerAtGeo("Charsadda Pakistan");
addMarkerAtGeo("Mansan Village Myanmar");
addMarkerAtGeo("Kwanobuhle South Africa");
addMarkerAtGeo("Salazar de las Palmas Colombia");
addMarkerAtGeo("Tehran Iran");
addMarkerAtGeo("Fulchhari Bangladesh");
addMarkerAtGeo("Kagiso Township South Africa");
addMarkerAtGeo("Yacacancha Peru");
addMarkerAtGeo("Iligan Philippines");
addMarkerAtGeo("South Lebanon Lebanon");
addMarkerAtGeo("Harike India");
addMarkerAtGeo("Brahmanbaria Bangladesh");
addMarkerAtGeo("Patiala District India");
addMarkerAtGeo("Prieto Diaz Philippines");
addMarkerAtGeo("Chincha Peru");
addMarkerAtGeo("Iscaya Peru");
addMarkerAtGeo("Vadala Kalan India");
addMarkerAtGeo("Karnagalla District Sri Lanka");
addMarkerAtGeo("Faridkot District India");
addMarkerAtGeo("Corozal Colombia");
addMarkerAtGeo("Chalita Bankur India");
addMarkerAtGeo("Maduto Mozambique");
addMarkerAtGeo("Samal Philippines");
addMarkerAtGeo("Alwatte Sri Lanka");
addMarkerAtGeo("Gaza West Bank and Gaza Strip");
addMarkerAtGeo("Pretoria South Africa");
addMarkerAtGeo("Jullundur India");
addMarkerAtGeo("Egodawatta -Mmaliduwa Sri Lanka");
addMarkerAtGeo("Junin Dept Peru");
addMarkerAtGeo("Denipitiya Sri Lanka");
addMarkerAtGeo("Injiniyagala Sri Lanka");
addMarkerAtGeo("El Medrano Venezuela");
addMarkerAtGeo("Arauca Dept Colombia");
addMarkerAtGeo("Santander dept Colombia");
addMarkerAtGeo("Sofala Province Mozambique");
addMarkerAtGeo("Kollupitiya Sri Lanka");
addMarkerAtGeo("Bar Ashit Lebanon");
addMarkerAtGeo("Beles Valley Ethiopia");
addMarkerAtGeo("Coquichayocc Peru");
addMarkerAtGeo("Karisari India");
addMarkerAtGeo("Heendeniya Pattiyagoda Sri Lanka");
addMarkerAtGeo("Thal Pakistan");
addMarkerAtGeo("Oiyrat Arba Israel");
addMarkerAtGeo("Chipata Colombia");
addMarkerAtGeo("Sitio Camp Philippines");
addMarkerAtGeo("Kurseong India");
addMarkerAtGeo("Cartagena Colombia");
addMarkerAtGeo("Huatasani Peru");
addMarkerAtGeo("Newcastle South Africa");
addMarkerAtGeo("Toopan Wala Pakistan");
addMarkerAtGeo("Tripoci Lebanon");
addMarkerAtGeo("Rashaya Lebanon");
addMarkerAtGeo("Curumani Colombia");
addMarkerAtGeo("Minga Colombia");
addMarkerAtGeo("Kegalle Sri Lanka");
addMarkerAtGeo("Remedios Colombia");
addMarkerAtGeo("Meta Dept Colombia");
addMarkerAtGeo("Sandton South Africa");
addMarkerAtGeo("Balbagan Town Philippines");
addMarkerAtGeo("Cajamarca Peru");
addMarkerAtGeo("San Agustin Philippines");
addMarkerAtGeo("Medina Colombia");
addMarkerAtGeo("El Cocuy Colombia");
addMarkerAtGeo("Uludere Turkey");
addMarkerAtGeo("Nike India");
addMarkerAtGeo("Kheerawali Village India");
addMarkerAtGeo("Santa Clara del Mar Argentina");
addMarkerAtGeo("Kandy District Sri Lanka");
addMarkerAtGeo("San Miguel Town Philippines");
addMarkerAtGeo("Tagun Town Philippines");
addMarkerAtGeo("Los Pompeyos Nicaragua");
addMarkerAtGeo("Thathian India");
addMarkerAtGeo("Petah Tikvah Israel");
addMarkerAtGeo("San Jose de los Molines Peru");
addMarkerAtGeo("Condormilla Pajo Peru");
addMarkerAtGeo("Arboletes Colombia");
addMarkerAtGeo("Ayacuclo Dept Peru");
addMarkerAtGeo("Jabalya West Bank and Gaza Strip");
addMarkerAtGeo("Leiktho Myanmar");
addMarkerAtGeo("Unknown Peru");
addMarkerAtGeo("Loikon Uganda");
addMarkerAtGeo("Cocuy Colombia");
addMarkerAtGeo("Jaito India");
addMarkerAtGeo("Orencik Turkey");
addMarkerAtGeo("Fort Bonifacio Makati Philippines");
addMarkerAtGeo("El Filo Colombia");
addMarkerAtGeo("Shukkaba Sudan");
addMarkerAtGeo("Kumarpara Bangladesh");
addMarkerAtGeo("Pakil Philippines");
addMarkerAtGeo("San Julian Philippines");
addMarkerAtGeo("Mediomagdalena Colombia");
addMarkerAtGeo("Cauca dept Colombia");
addMarkerAtGeo("Dickwella Sri Lanka");
addMarkerAtGeo("Gaborne Botswana");
addMarkerAtGeo("Arboledas Colombia");
addMarkerAtGeo("Pannipitiya Sri Lanka");
addMarkerAtGeo("Jagraon India");
addMarkerAtGeo("Roodepoort South Africa");
addMarkerAtGeo("Huachocolpa Peru");
addMarkerAtGeo("Savaino Peru");
addMarkerAtGeo("Kadian India");
addMarkerAtGeo("Carhuanca Peru");
addMarkerAtGeo("Rooerwal India");
addMarkerAtGeo("Deriwal India");
addMarkerAtGeo("Santiago de Chuco Prov Peru");
addMarkerAtGeo("Arauca Intendency Colombia");
addMarkerAtGeo("Chaquira Colombia");
addMarkerAtGeo("Pasuquin Philippines");
addMarkerAtGeo("Puente Negro El Salvador");
addMarkerAtGeo("Ugie South Africa");
addMarkerAtGeo("Gamay Philippines");
addMarkerAtGeo("Chosica Peru");
addMarkerAtGeo("Barangay Cagdavo Philippines");
addMarkerAtGeo("Meethapur India");
addMarkerAtGeo("Vina del Mar Chile");
addMarkerAtGeo("Manakulam Sri Lanka");
addMarkerAtGeo("Trenance Zimbabwe");
addMarkerAtGeo("Sanpinit Philippines");
addMarkerAtGeo("El Mancotal Nicaragua");
addMarkerAtGeo("Kfar Kila Lebanon");
addMarkerAtGeo("Bundala India");
addMarkerAtGeo("Kotla India");
addMarkerAtGeo("Pandori India");
addMarkerAtGeo("Bekaa Valley Lebanon");
addMarkerAtGeo("Bandargama Sri Lanka");
addMarkerAtGeo("Mitchells Plain South Africa");
addMarkerAtGeo("Sanagun Colombia");
addMarkerAtGeo("Atahuatun Peru");
addMarkerAtGeo("Nawngmu village Myanmar");
addMarkerAtGeo("Mullaitivu District Sri Lanka");
addMarkerAtGeo("Rancagua Chile");
addMarkerAtGeo("Cheemapat India");
addMarkerAtGeo("Churcampa Peru");
addMarkerAtGeo("Ludhiana India");
addMarkerAtGeo("Davao Philippines");
addMarkerAtGeo("Ghadiara India");
addMarkerAtGeo("Ferozepore area India");
addMarkerAtGeo("Patamaca Suriname");
addMarkerAtGeo("El Romeral Chile");
addMarkerAtGeo("Huamachuco Peru");
addMarkerAtGeo("Beirut Lebanon");
addMarkerAtGeo("Soweto South Africa");
addMarkerAtGeo("Kadugannawa Sri Lanka");
addMarkerAtGeo("Nueva Vizcaya Prov. Philippines");
addMarkerAtGeo("Kurunegala District Sri Lanka");
addMarkerAtGeo("Anco Peru");
addMarkerAtGeo("Pehwa India");
addMarkerAtGeo("Kathley India");
addMarkerAtGeo("Barranquilia Colombia");
addMarkerAtGeo("White City South Africa");
addMarkerAtGeo("Ramospampa Peru");
addMarkerAtGeo("Ai-Dallafah Lebanon");
addMarkerAtGeo("Sotora Colombia");
addMarkerAtGeo("Natukaikollai Sri Lanka");
addMarkerAtGeo("Quezon City Philippines");
addMarkerAtGeo("Tunukkai - Lalavi Sri Lanka");
addMarkerAtGeo("Limmasol Cyprus");
addMarkerAtGeo("Velvettiturai Sri Lanka");
addMarkerAtGeo("Alberton South Africa");
addMarkerAtGeo("Loma Grande Nicaragua");
addMarkerAtGeo("Sadanga Philippines");
addMarkerAtGeo("Timuwal India");
addMarkerAtGeo("Rangoon Myanmar");
addMarkerAtGeo("Sotha India");
addMarkerAtGeo("Bambalapitiya Sri Lanka");
addMarkerAtGeo("Patia Colombia");
addMarkerAtGeo("San Jose del Nuz Colombia");
addMarkerAtGeo("Hoshiapur India");
addMarkerAtGeo("Jerusalem Israel");
addMarkerAtGeo("East London South Africa");
addMarkerAtGeo("Batticaloa Sri Lanka");
addMarkerAtGeo("San Martin Dept Peru");
addMarkerAtGeo("Huayllay Peru");
addMarkerAtGeo("Panali Nicaragua");
addMarkerAtGeo("El Amaro Nicaragua");
addMarkerAtGeo("Sitio Canjolo Philippines");
addMarkerAtGeo("Chigorodo Colombia");
addMarkerAtGeo("Samar Island Philippines");
addMarkerAtGeo("Dhaliwal India");
addMarkerAtGeo("Ferozepur Dist. India");
addMarkerAtGeo("Putumaya Intendency Colombia");
addMarkerAtGeo("Barangay Kabatan Philippines");
addMarkerAtGeo("Lunugamvehera Sri Lanka");
addMarkerAtGeo("Turbo Colombia");
addMarkerAtGeo("Caicedonia Colombia");
addMarkerAtGeo("Negros Oriental Prov. Philippines");
addMarkerAtGeo("Barrancabermeja Colombia");
addMarkerAtGeo("Convencion Colombia");
addMarkerAtGeo("Saulsville South Africa");
addMarkerAtGeo("Jalandhar India");
addMarkerAtGeo("Titococha Peru");
addMarkerAtGeo("Gokkuwal India");
addMarkerAtGeo("Jhugian India");
addMarkerAtGeo("Quilpue Chile");
addMarkerAtGeo("Malakal Sudan");
addMarkerAtGeo("Barranquilla Colombia");
addMarkerAtGeo("Singamadi India");
addMarkerAtGeo("Pitogo Philippines");
addMarkerAtGeo("Madulsina Sri Lanka");
addMarkerAtGeo("Southern Thailand Thailand");
addMarkerAtGeo("Sergovia Colombia");
addMarkerAtGeo("Paten Chile");
addMarkerAtGeo("Yanacanca Peru");
addMarkerAtGeo("Huancapi Peru");
addMarkerAtGeo("Belh Majra India");
addMarkerAtGeo("Sevenfontein South Africa");
addMarkerAtGeo("Guadalupe Nuevo Philippines");
addMarkerAtGeo("Ayacucho City Peru");
addMarkerAtGeo("Mehadpur India");
addMarkerAtGeo("Santa Fe Argentina");
addMarkerAtGeo("Valdivia Colombia");
addMarkerAtGeo("Mangala Oya Sri Lanka");
addMarkerAtGeo("Jullundur Dist. India");
addMarkerAtGeo("Medellin Colombia");
addMarkerAtGeo("Kruger National Park South Africa");
addMarkerAtGeo("Nueva Ecija Prov Philippines");
addMarkerAtGeo("Beita West Bank and Gaza Strip");
addMarkerAtGeo("Cerro Blanco Colombia");
addMarkerAtGeo("Baini Gillan India");
addMarkerAtGeo("Walvis Bay Namibia");
addMarkerAtGeo("Nigel South Africa");
addMarkerAtGeo("Necocli Colombia");
addMarkerAtGeo("Tricomalee India");
addMarkerAtGeo("Olana Colombia");
addMarkerAtGeo("Supe Pativilca Peru");
addMarkerAtGeo("Nueva Colon Colombia");
addMarkerAtGeo("Pinetown South Africa");
addMarkerAtGeo("Lagos Nigeria");
addMarkerAtGeo("Mullaittivu Sri Lanka");
addMarkerAtGeo("Clermont Township South Africa");
addMarkerAtGeo("Amtitsar District India");
addMarkerAtGeo("Lupayan Philippines");
addMarkerAtGeo("Kalmunai Sri Lanka");
addMarkerAtGeo("Lugela Mozambique");
addMarkerAtGeo("Wellawaya Sri Lanka");
addMarkerAtGeo("Virka India");
addMarkerAtGeo("Bacolod Philippines");
addMarkerAtGeo("Pangota India");
addMarkerAtGeo("Dharmapuram Sri Lanka");
addMarkerAtGeo("Concepcion Peru");
addMarkerAtGeo("El Pito El Salvador");
addMarkerAtGeo("Mamaduwa Sri Lanka");
addMarkerAtGeo("Mar Ilayas Camp Lebanon");
addMarkerAtGeo("Sanabamba Peru");
addMarkerAtGeo("San Gerardo Peru");
addMarkerAtGeo("Amarkot India");
addMarkerAtGeo("Alexandria South Africa");
addMarkerAtGeo("Caracas Venezuela");
addMarkerAtGeo("Moneragala District Sri Lanka");
addMarkerAtGeo("Isabela Province Philippines");
addMarkerAtGeo("Saravena Colombia");
addMarkerAtGeo("Rania India");
addMarkerAtGeo("Kir Khawr Sudan");
addMarkerAtGeo("Capetown South Africa");
addMarkerAtGeo("Maruwai India");
addMarkerAtGeo("Silla De Oro El Salvador");
addMarkerAtGeo("Woodstock South Africa");
addMarkerAtGeo("Guman India");
addMarkerAtGeo("Alldays South Africa");
addMarkerAtGeo("Mardin Province Turkey");
addMarkerAtGeo("Ponkunivita Sri Lanka");
addMarkerAtGeo("Islamabad Pakistan");
addMarkerAtGeo("Jhanger India");
addMarkerAtGeo("La Ye Colombia");
addMarkerAtGeo("Huaraz Peru");
addMarkerAtGeo("Sierra Nevada Colombia");
addMarkerAtGeo("Limassol Cyprus");
addMarkerAtGeo("Kotawila Sri Lanka");
addMarkerAtGeo("Thondamanaru Sri Lanka");
addMarkerAtGeo("Dakar Senegal");
addMarkerAtGeo("Maimana Afghanistan");
addMarkerAtGeo("Montanas de Wamblan Nicaragua");
addMarkerAtGeo("Las Juntas Ecuador");
addMarkerAtGeo("Gurdaspur District India");
addMarkerAtGeo("Bandarban District Bangladesh");
addMarkerAtGeo("Pamankade Sri Lanka");
addMarkerAtGeo("Tumahole South Africa");
addMarkerAtGeo("Yakkala Sri Lanka");
addMarkerAtGeo("Kegalla Sri Lanka");
addMarkerAtGeo("Laguna Caren Chile");
addMarkerAtGeo("Razhuilca Peru");
addMarkerAtGeo("Kapurthala District India");
addMarkerAtGeo("Stellenbosch South Africa");
addMarkerAtGeo("Shtawrah Lebanon");
addMarkerAtGeo("Jammu India");
addMarkerAtGeo("Vina Del Mar Chile");
addMarkerAtGeo("San Luis El Salvador");
addMarkerAtGeo("Point Pedro Sri Lanka");
addMarkerAtGeo("Davao del Sur Dept Philippines");
addMarkerAtGeo("Rajumajra India");
addMarkerAtGeo("King Williamstown South Africa");
addMarkerAtGeo("Fort Beaufort South Africa");
addMarkerAtGeo("Balla India");
addMarkerAtGeo("Chimabagh India");
addMarkerAtGeo("Matale District Sri Lanka");
addMarkerAtGeo("Jounieh Lebanon");
addMarkerAtGeo("Emdeni South Africa");
addMarkerAtGeo("Serunewa Sri Lanka");
addMarkerAtGeo("Cotopuquio Peru");
addMarkerAtGeo("Putumayo Dept Colombia");
addMarkerAtGeo("Balangoda Sri Lanka");
addMarkerAtGeo("Mantaro Peru");
addMarkerAtGeo("Bohol Province Philippines");
addMarkerAtGeo("Tricomalee Sri Lanka");
addMarkerAtGeo("San Juan de Jarpa Peru");
addMarkerAtGeo("Kandy Town Sri Lanka");
addMarkerAtGeo("Kumi Uganda");
addMarkerAtGeo("La Plata Argentina");
addMarkerAtGeo("Chillan Chile");
addMarkerAtGeo("Bulcan Province Philippines");
addMarkerAtGeo("Yayladere Turkey");
addMarkerAtGeo("Xelvitz Guatemala");
addMarkerAtGeo("Bombo Uganda");
addMarkerAtGeo("Suaza Colombia");
addMarkerAtGeo("San Agustin de Cajes Peru");
addMarkerAtGeo("El Castillo Colombia");
addMarkerAtGeo("Vellai Sri Lanka");
addMarkerAtGeo("Matale Sri Lanka");
addMarkerAtGeo("Chogbasta India");
addMarkerAtGeo("Guayaquil Ecuador");
addMarkerAtGeo("Kishan Pura Village India");
addMarkerAtGeo("Teorama Colombia");
addMarkerAtGeo("Negros island Philippines");
addMarkerAtGeo("Maukpilin Myanmar");
addMarkerAtGeo("Malabon Philippines");
addMarkerAtGeo("Puno Peru");
addMarkerAtGeo("Maseru Lesotho");
addMarkerAtGeo("Mullaitvu District Sri Lanka");
addMarkerAtGeo("Boo India");
addMarkerAtGeo("Kada Viohan India");
addMarkerAtGeo("Siirt Province Turkey");
addMarkerAtGeo("Gilo West Bank and Gaza Strip");
addMarkerAtGeo("Loboyaru Peru");
addMarkerAtGeo("Quirino Philippines");
addMarkerAtGeo("Lucena Philippines");
addMarkerAtGeo("Ayacucho Peru");
addMarkerAtGeo("Barangay Supidik Philippines");
addMarkerAtGeo("Babui India");
addMarkerAtGeo("Hucrachuco Peru");
addMarkerAtGeo("Biryas Lebanon");
addMarkerAtGeo("Hoshiarpur District India");
addMarkerAtGeo("Barangay De Bagan Philippines");
addMarkerAtGeo("Cali Peru");
addMarkerAtGeo("Walathapitiya Sri Lanka");
addMarkerAtGeo("Sangrala India");
addMarkerAtGeo("Inanda South Africa");
addMarkerAtGeo("Bugaramanga Colombia");
addMarkerAtGeo("Rio Negro Colombia");
addMarkerAtGeo("Pore Colombia");
addMarkerAtGeo("Soweto Township South Africa");
addMarkerAtGeo("Sagama Sri Lanka");
addMarkerAtGeo("Santa Clara Colombia");
addMarkerAtGeo("Sabana de Torres Colombia");
addMarkerAtGeo("Bogota Colombia");
addMarkerAtGeo("Calcauso Peru");
addMarkerAtGeo("Mingora Pakistan");
addMarkerAtGeo("Kachchikade Sri Lanka");
addMarkerAtGeo("Luanda Angola");
addMarkerAtGeo("La Tipa Colombia");
addMarkerAtGeo("Sidon Lebanon");
addMarkerAtGeo("Malupara Bangladesh");
addMarkerAtGeo("Nowgong India");
addMarkerAtGeo("Gompo Town South Africa");
addMarkerAtGeo("San Bernardo Chile");
addMarkerAtGeo("Batavia South Africa");
addMarkerAtGeo("Barangay Bunga Philippines");
addMarkerAtGeo("San Antonio Del Pescado Colombia");
addMarkerAtGeo("Udhonaugal India");
addMarkerAtGeo("Ambalangoda Sri Lanka");
addMarkerAtGeo("Makati Philippines");
addMarkerAtGeo("Valtoha Village India");
addMarkerAtGeo("Ratoka Village India");
addMarkerAtGeo("Sangrur District India");
addMarkerAtGeo("Pottuvil Sri Lanka");
addMarkerAtGeo("Camarines Philippines");
addMarkerAtGeo("Palo Philippines");
addMarkerAtGeo("Mauban Town Philippines");
addMarkerAtGeo("Ouzal Lebanon");
addMarkerAtGeo("Huluganga Sri Lanka");
addMarkerAtGeo("Silvino Lobos Philippines");
addMarkerAtGeo("Mongphan Myanmar");
addMarkerAtGeo("Moroka South Africa");
addMarkerAtGeo("Matara District Sri Lanka");
addMarkerAtGeo("Talwandi Suba India");
addMarkerAtGeo("Araur Junction Israel");
addMarkerAtGeo("Bataan Philippines");
addMarkerAtGeo("Kyaikto Township Myanmar");
addMarkerAtGeo("El Bagre Colombia");
addMarkerAtGeo("Santa Teresa El Salvador");
addMarkerAtGeo("Batapola Sri Lanka");
addMarkerAtGeo("Darjeeling India");
addMarkerAtGeo("Haryana India");
addMarkerAtGeo("Baguio City Philippines");
addMarkerAtGeo("Guaviare Intendency Colombia");
addMarkerAtGeo("Sonda India");
addMarkerAtGeo("Gaborone South Africa");
addMarkerAtGeo("Jericho West Bank and Gaza Strip");
addMarkerAtGeo("Jfugo Region Philippines");
addMarkerAtGeo("Sanaa North Yemen");
addMarkerAtGeo("Near Subic Bay Philippines");
addMarkerAtGeo("Tocto Peru");
addMarkerAtGeo("Huambo Angola");
addMarkerAtGeo("Amritsar District India");
addMarkerAtGeo("Phagwara Town India");
addMarkerAtGeo("Ocana Colombia");
addMarkerAtGeo("Arequipa Peru");
addMarkerAtGeo("Buhuyan India");
addMarkerAtGeo("Pallanchacra Peru");
addMarkerAtGeo("Krugersdorp South Africa");
addMarkerAtGeo("Tripoli Lebanon");
addMarkerAtGeo("Amditsar India");
addMarkerAtGeo("Atal India");
addMarkerAtGeo("Charcari Peru");
addMarkerAtGeo("Rum Sudan");
addMarkerAtGeo("Billowan India");
addMarkerAtGeo("Tena Ecuador");
addMarkerAtGeo("Norzagaray Town Philippines");
addMarkerAtGeo("Catahuasi Peru");
addMarkerAtGeo("Brokoponda Suriname");
addMarkerAtGeo("Tambo Peru");
addMarkerAtGeo("Argelia Colombia");
addMarkerAtGeo("Shan State Myanmar");
addMarkerAtGeo("Baghdad Iraq");
addMarkerAtGeo("Pacaycasa Peru");
addMarkerAtGeo("Burao Somalia");
addMarkerAtGeo("Satnala Village India");
addMarkerAtGeo("Migalawa Sri Lanka");
addMarkerAtGeo("Kozluic Turkey");
addMarkerAtGeo("Pallca Peru");
addMarkerAtGeo("Huenches Peru");
addMarkerAtGeo("Progreso Peru");
addMarkerAtGeo("Vavuniya Sector Sri Lanka");
addMarkerAtGeo("Monpos Colombia");
addMarkerAtGeo("Angeles City Philippines");
addMarkerAtGeo("Mpumalanga South Africa");
addMarkerAtGeo("San Martin Colombia");
addMarkerAtGeo("Florencia Colombia");
addMarkerAtGeo("San Vicente Colombia");
addMarkerAtGeo("Chakundal India");
addMarkerAtGeo("Galewela Sri Lanka");
addMarkerAtGeo("Lohara India");
addMarkerAtGeo("Khalijian India");
addMarkerAtGeo("Garajantilla Bangladesh");
addMarkerAtGeo("Huanzala Peru");
addMarkerAtGeo("Kundasale Sri Lanka");
addMarkerAtGeo("Tembisa South Africa");
addMarkerAtGeo("Ahluwal India");
addMarkerAtGeo("Barisal Bangladesh");
addMarkerAtGeo("Los Ouenes Chile");
addMarkerAtGeo("Norte de Santander Dept. Colombia");
addMarkerAtGeo("Sakira Village India");
addMarkerAtGeo("Puerto Narino Colombia");
addMarkerAtGeo("Sitio Villegas Philippines");
addMarkerAtGeo("Valachenai Sri Lanka");
addMarkerAtGeo("Djibouti Djibouti");
addMarkerAtGeo("Karachi Pakistan");
addMarkerAtGeo("Puquina Peru");
addMarkerAtGeo("Parjeeling India");
addMarkerAtGeo("Beersheba Israel");
addMarkerAtGeo("San Juan de Mira Flores Peru");
addMarkerAtGeo("Pangasinan Philippines");
addMarkerAtGeo("Kachumbala Uganda");
addMarkerAtGeo("Wattville South Africa");
addMarkerAtGeo("Pungwe River Mozambique");
addMarkerAtGeo("Puerto Lleras Colombia");
addMarkerAtGeo("Batticaloa Area South Africa");
addMarkerAtGeo("Mallaiyakadu Sri Lanka");
addMarkerAtGeo("Jandiala India");
addMarkerAtGeo("Armitsar India");
addMarkerAtGeo("Deegavapiya Sri Lanka");
addMarkerAtGeo("El Patia Colombia");
addMarkerAtGeo("Armenia Colombia");
addMarkerAtGeo("Behmenin Turkey");
addMarkerAtGeo("Paramaribo Suriname");
addMarkerAtGeo("Kikarawala River Nicaragua");
addMarkerAtGeo("Vavuniya District Sri Lanka");
addMarkerAtGeo("San Nicolas Peru");
addMarkerAtGeo("Kuwait City Kuwait");
addMarkerAtGeo("Sirimanga la Pura Sri Lanka");
addMarkerAtGeo("Nangarhar Province Afghanistan");
addMarkerAtGeo("Bulara India");
addMarkerAtGeo("Haquira Peru");
addMarkerAtGeo("Oras Philippines");
addMarkerAtGeo("Horowpathana Sri Lanka");
addMarkerAtGeo("Loma de Gonzales Colombia");
addMarkerAtGeo("Mallakam Sri Lanka");
addMarkerAtGeo("Arapai Uganda");
addMarkerAtGeo("Rampurapull India");
addMarkerAtGeo("San Roque Philippines");
addMarkerAtGeo("Kalmuni Sri Lanka");
addMarkerAtGeo("Kokstad South Africa");
addMarkerAtGeo("Vistahermosa Colombia");
addMarkerAtGeo("Boksburg South Africa");
addMarkerAtGeo("Muchhal India");
addMarkerAtGeo("Kumulamuna Sri Lanka");
addMarkerAtGeo("Panichankerni Sri Lanka");
addMarkerAtGeo("Trefles Mauritania");
addMarkerAtGeo("Hakmana Sri Lanka");
addMarkerAtGeo("Bukidnon Philippines");
addMarkerAtGeo("Delhi India");
addMarkerAtGeo("Yagizoymak Turkey");
addMarkerAtGeo("Chittagon Hill area Bangladesh");
addMarkerAtGeo("Mountain Province Philippines");
addMarkerAtGeo("Pilimetalawa Sri Lanka");
addMarkerAtGeo("Chansadda Pakistan");
addMarkerAtGeo("Monkey Bridge Sri Lanka");
addMarkerAtGeo("Bakhtapur India");
addMarkerAtGeo("El Rubicon Colombia");
addMarkerAtGeo("Saint Mery Basti India");
addMarkerAtGeo("Libagon Philippines");
addMarkerAtGeo("La Mejor Esquina Colombia");
addMarkerAtGeo("Deri Jsmail Khan Pakistan");
addMarkerAtGeo("Deepsinghwalla India");
addMarkerAtGeo("Kohali India");
addMarkerAtGeo("Tocache Peru");
addMarkerAtGeo("Talpe Sri Lanka");
addMarkerAtGeo("Algecira Colombia");
addMarkerAtGeo("Kongala Sri Lanka");
addMarkerAtGeo("Santa Ana Philippines");
addMarkerAtGeo("Anuradhapura Sri Lanka");
addMarkerAtGeo("no city or area shown Namibia");
addMarkerAtGeo("Cucuta Colombia");
addMarkerAtGeo("Lachocc Peru");
addMarkerAtGeo("Jaffni Sri Lanka");
addMarkerAtGeo("Tarlac Province Philippines");
addMarkerAtGeo("Cesar Dept Colombia");
addMarkerAtGeo("Kiupusama Nicaragua");
addMarkerAtGeo("Durgapur India");
addMarkerAtGeo("Ticrapo Peru");
addMarkerAtGeo("Siasi Island Philippines");
addMarkerAtGeo("Navatkuli Sri Lanka");
addMarkerAtGeo("Eravur Sri Lanka");
addMarkerAtGeo("Ghaziyeh Lebanon");
addMarkerAtGeo("Asocasi Peru");
addMarkerAtGeo("Buridnon Province Philippines");
addMarkerAtGeo("Hura Israel");
addMarkerAtGeo("Ba Jala India");
addMarkerAtGeo("Amritsar India");
addMarkerAtGeo("Caldas Dept Colombia");
addMarkerAtGeo("San Luis de Palenque Colombia");
addMarkerAtGeo("Viterbo Colombia");
addMarkerAtGeo("Tierra Alta Colombia");
addMarkerAtGeo("Unknown Lebanon");
addMarkerAtGeo("Durbaj South Africa");
addMarkerAtGeo("Davao Oriental Province Philippines");
addMarkerAtGeo("San Jose de Quero Peru");
addMarkerAtGeo("Pallai Sri Lanka");
addMarkerAtGeo("Unknown Colombia");
addMarkerAtGeo("Abra de Ilog Philippines");
addMarkerAtGeo("Baggozu Turkey");
addMarkerAtGeo("La Cascajara Colombia");
addMarkerAtGeo("Toor Village India");
addMarkerAtGeo("Bahawalpur Pakistan");
addMarkerAtGeo("Leon Town Philippines");
addMarkerAtGeo("Nahariyya Israel");
addMarkerAtGeo("Katutura Namibia");
addMarkerAtGeo("Mathewal India");
addMarkerAtGeo("Supia Colombia");
addMarkerAtGeo("Wadduwa Sri Lanka");
addMarkerAtGeo("Antioquia Dept Colombia");
addMarkerAtGeo("Palaman Philippines");
addMarkerAtGeo("Pozozo Peru");
addMarkerAtGeo("La Oroya Peru");
addMarkerAtGeo("Manikchhari Bangladesh");
addMarkerAtGeo("Balcon Peru");
addMarkerAtGeo("Sirnak Turkey");
addMarkerAtGeo("Kemah Turkey");
addMarkerAtGeo("Magpet Philippines");
addMarkerAtGeo("Patti India");
addMarkerAtGeo("Trincomalee Sri Lanka");
addMarkerAtGeo("Navotas Philippines");
addMarkerAtGeo("Brookspoint Philippines");
addMarkerAtGeo("Hebron West Bank and Gaza Strip");
addMarkerAtGeo("Bhuli Karimpur India");
addMarkerAtGeo("Escondito River Nicaragua");
addMarkerAtGeo("El Ciro Nicaragua");
addMarkerAtGeo("Mannar Sri Lanka");
addMarkerAtGeo("Zipaquira Colombia");
addMarkerAtGeo("Los Jobos El Salvador");
addMarkerAtGeo("Bonteheijwel South Africa");
addMarkerAtGeo("Barranca Colombia");
addMarkerAtGeo("Mollebamba Peru");
addMarkerAtGeo("Gandara Sri Lanka");
addMarkerAtGeo("Zaragoza Colombia");
addMarkerAtGeo("San Antonio Chile");
addMarkerAtGeo("Nalbari India");
addMarkerAtGeo("Patiala India");
addMarkerAtGeo("Lichtenburg South Africa");
addMarkerAtGeo("Thepaichurara India");
addMarkerAtGeo("Marquesado Argentina");
addMarkerAtGeo("Standerton South Africa");
addMarkerAtGeo("No City Listed Philippines");
addMarkerAtGeo("Pullumalai Sri Lanka");
addMarkerAtGeo("Rutian India");
addMarkerAtGeo("Negro Island Philippines");
addMarkerAtGeo("Hillbrow South Africa");
addMarkerAtGeo("Pundol India");
addMarkerAtGeo("Omanthai Sri Lanka");
addMarkerAtGeo("Bengal India");
addMarkerAtGeo("Burglieh Lebanon");
addMarkerAtGeo("Pacomarca Peru");
addMarkerAtGeo("Bataan Province Philippines");
addMarkerAtGeo("Kyaikkaw Myanmar");
addMarkerAtGeo("Manica Philippines");
addMarkerAtGeo("Marawi Philippines");
addMarkerAtGeo("Koch Goma Uganda");
addMarkerAtGeo("Bagalod Philippines");
addMarkerAtGeo("Zamboanga del Norte Province Philippines");
addMarkerAtGeo("Jahangir Kalan India");
addMarkerAtGeo("Dabburiya Israel");
addMarkerAtGeo("Saiza Colombia");
addMarkerAtGeo("Lamlai India");
addMarkerAtGeo("Yala Thailand");
addMarkerAtGeo("Larnaca Cyprus");
addMarkerAtGeo("Punjab State India");
addMarkerAtGeo("Prutoria South Africa");
addMarkerAtGeo("Ghariala India");
addMarkerAtGeo("Rangapani Bangladesh");
addMarkerAtGeo("Matara Sri Lanka");
addMarkerAtGeo("Paranque Philippines");
addMarkerAtGeo("Palugaturai Sri Lanka");
addMarkerAtGeo("Uraba Colombia");
addMarkerAtGeo("Bataramulla Sri Lanka");
addMarkerAtGeo("Cauca Dept Colombia");
addMarkerAtGeo("Namsam Myanmar");
addMarkerAtGeo("Lusaka Zambia");
addMarkerAtGeo("Takhtuchak India");
addMarkerAtGeo("Situcancha Peru");
addMarkerAtGeo("Rawalpindi Pakistan");
addMarkerAtGeo("El Denon Colombia");
addMarkerAtGeo("Aucayacu Peru");
addMarkerAtGeo("Quipama Colombia");
addMarkerAtGeo("Manila Philippines");
addMarkerAtGeo("Paraiso Colombia");
addMarkerAtGeo("Guatepuri Colombia");
addMarkerAtGeo("Tel Aviv Israel");
addMarkerAtGeo("Quetta Pakistan");
addMarkerAtGeo("La Pinalera Colombia");
addMarkerAtGeo("Shantipara India");
addMarkerAtGeo("Pichari Peru");
addMarkerAtGeo("Santa Cruz Philippines");
addMarkerAtGeo("Khalata Lebanon");
addMarkerAtGeo("Intramuros Philippines");
addMarkerAtGeo("Girulla Sri Lanka");
addMarkerAtGeo("Mahakongaskade Sri Lanka");
addMarkerAtGeo("Tyre Lebanon");
addMarkerAtGeo("Redhill South Africa");
addMarkerAtGeo("Kilinochchi Sri Lanka");
addMarkerAtGeo("Cheemakhuddi India");
addMarkerAtGeo("Sidhuwadona India");
addMarkerAtGeo("Butuan Philippines");
addMarkerAtGeo("Barrancabermeta Colombia");
addMarkerAtGeo("Queenstown South Africa");
addMarkerAtGeo("Kayah State Myanmar");
addMarkerAtGeo("Imbali Township South Africa");
addMarkerAtGeo("Cebu City Philippines");
addMarkerAtGeo("Guguletu South Africa");
addMarkerAtGeo("Nuwars Eliya Sri Lanka");
addMarkerAtGeo("Badnikurd India");
addMarkerAtGeo("Tingo Maria Peru");
addMarkerAtGeo("Vanuniua Sri Lanka");
addMarkerAtGeo("Horowpatana Sri Lanka");
addMarkerAtGeo("New Delhi India");
addMarkerAtGeo("Beriut Lebanon");
addMarkerAtGeo("Bangoi Philippines");
addMarkerAtGeo("Cano Colorado Venezuela");
addMarkerAtGeo("Mand India");
addMarkerAtGeo("Bocas De Vilan Nicaragua");
addMarkerAtGeo("Pietersburg South Africa");
addMarkerAtGeo("Boca de Grita Venezuela");
addMarkerAtGeo("Jabalpur India");
addMarkerAtGeo("Macachacra Peru");
addMarkerAtGeo("Santa Cruz Peru");
addMarkerAtGeo("San Luis Philippines");
addMarkerAtGeo("Cordoba Argentina");
addMarkerAtGeo("Machuria Village India");
addMarkerAtGeo("Pamplona Colombia");
addMarkerAtGeo("Near Soroti Uganda");
addMarkerAtGeo("Hargeisa Somalia");
addMarkerAtGeo("Uige Angola");
addMarkerAtGeo("Udhakay India");
addMarkerAtGeo("La Esmeralda Colombia");
addMarkerAtGeo("Bhatinda India");
addMarkerAtGeo("Pachchenur Sri Lanka");
addMarkerAtGeo("Tachira State Venezuela");
addMarkerAtGeo("Taxila Pakistan");
addMarkerAtGeo("Polonnaruwa Sri Lanka");
addMarkerAtGeo("Matinda India");
addMarkerAtGeo("Bhatinda District India");
addMarkerAtGeo("Bafasende Congo (Kinshasa)");
addMarkerAtGeo("Aranhuay Peru");
addMarkerAtGeo("Kabul Afghanistan");
addMarkerAtGeo("Cebu Island Philippines");
addMarkerAtGeo("Haifa Israel");
addMarkerAtGeo("Sagada Town Philippines");
addMarkerAtGeo("Alutgama Sri Lanka");
addMarkerAtGeo("Omas Peru");
addMarkerAtGeo("Myawadi Myanmar");
addMarkerAtGeo("Chiclayo Peru");
addMarkerAtGeo("El Mango Colombia");
addMarkerAtGeo("Akaraipattu Sri Lanka");
addMarkerAtGeo("Kamalawala India");
addMarkerAtGeo("Mandalay Myanmar");
addMarkerAtGeo("Janchijasa Peru");
addMarkerAtGeo("Maroor Village India");
addMarkerAtGeo("Kadawatha Sri Lanka");
addMarkerAtGeo("Arauca Colombia");
addMarkerAtGeo("Chitamla Village India");
addMarkerAtGeo("Pandorigolan India");
addMarkerAtGeo("Kalimpong India");
addMarkerAtGeo("Kwathema South Africa");
addMarkerAtGeo("Quebrada Honda Peru");
addMarkerAtGeo("Monaragala Sri Lanka");
addMarkerAtGeo("Katugampola Sri Lanka");
addMarkerAtGeo("San Pedro de Pilas Peru");
addMarkerAtGeo("Marcos Town Philippines");
addMarkerAtGeo("Cesar Province Colombia");
addMarkerAtGeo("Nedunkerni Sri Lanka");
addMarkerAtGeo("El Bordo Colombia");
addMarkerAtGeo("Umm Fahm Israel");
addMarkerAtGeo("Benoni South Africa");
addMarkerAtGeo("Cheddikulam Sri Lanka");
addMarkerAtGeo("Hashiapur District India");
addMarkerAtGeo("Allpa-Orccuna Peru");
addMarkerAtGeo("Concepcion Philippines");
addMarkerAtGeo("Chigordo Colombia");
addMarkerAtGeo("San Jorge Philippines");
addMarkerAtGeo("Sacharaccay Peru");
addMarkerAtGeo("Mojawal India");
addMarkerAtGeo("Khuzestan Province Iran");
addMarkerAtGeo("Otanche Colombia");
addMarkerAtGeo("Thopur Sri Lanka");
addMarkerAtGeo("Puerto Aisen Chile");
addMarkerAtGeo("El Carmen Colombia");
addMarkerAtGeo("Gurjarpura India");
addMarkerAtGeo("Osorno Chile");
addMarkerAtGeo("Gigante Colombia");
addMarkerAtGeo("Chiriri Colombia");
addMarkerAtGeo("Nabuntoran Philippines");
addMarkerAtGeo("Dayr Al-Balah West Bank and Gaza Strip");
addMarkerAtGeo("Farajok Sudan");
addMarkerAtGeo("Randfontein South Africa");
addMarkerAtGeo("Bukidnon Prov. Philippines");
addMarkerAtGeo("Curico Chile");
addMarkerAtGeo("Dhaka Bangladesh");
addMarkerAtGeo("Udadamana Sri Lanka");
addMarkerAtGeo("Sinbo Myanmar");
addMarkerAtGeo("Gross-Gerall West Germany (FRG)");
addMarkerAtGeo("Dada India");
addMarkerAtGeo("Mainay Peru");
addMarkerAtGeo("Sunhpora India");
addMarkerAtGeo("Milan Colombia");
addMarkerAtGeo("Paujil Colombia");
addMarkerAtGeo("Unknown Northern Ireland");
addMarkerAtGeo("Rocklands South Africa");
addMarkerAtGeo("Sambag Philippines");
addMarkerAtGeo("Cordoba Dept Colombia");
addMarkerAtGeo("Vavuniya Sri Lanka");
addMarkerAtGeo("Rincon Hondo Colombia");
addMarkerAtGeo("Chandigarh India");
addMarkerAtGeo("Balachor India");
addMarkerAtGeo("Tibnin Lebanon");
addMarkerAtGeo("Mismas Occidental Prov. Philippines");
addMarkerAtGeo("Ayacucho dept Peru");
addMarkerAtGeo("Barangay Banag Philippines");
addMarkerAtGeo("San Juan de Salinas Peru");
addMarkerAtGeo("Dhaini Basa Singh Village India");
addMarkerAtGeo("Alvarado Colombia");
addMarkerAtGeo("Hammarasdale South Africa");
addMarkerAtGeo("Montanita Colombia");
addMarkerAtGeo("Chala Peru");
addMarkerAtGeo("Atteridgeville South Africa");
addMarkerAtGeo("Gaborone Botswana");
addMarkerAtGeo("Unknown South Africa");
addMarkerAtGeo("Asagical Diran area Turkey");
addMarkerAtGeo("Huancavelica Peru");
addMarkerAtGeo("Mandur Sri Lanka");
addMarkerAtGeo("Vennamulam Sri Lanka");
addMarkerAtGeo("Santander de Quilichao Colombia");
addMarkerAtGeo("Varapetiya Sri Lanka");
addMarkerAtGeo("Cerro De Pasco Peru");
addMarkerAtGeo("Tanayalon Philippines");
addMarkerAtGeo("Acocasi Peru");
addMarkerAtGeo("Urchiza Peru");
addMarkerAtGeo("Taskoy Turkey");
addMarkerAtGeo("Kamburupitiya Sri Lanka");
addMarkerAtGeo("Amman Jordan");
addMarkerAtGeo("El Pilar Nicaragua");
addMarkerAtGeo("Quinchihuil Peru");
addMarkerAtGeo("unknown South Africa");
addMarkerAtGeo("Khajoura India");
addMarkerAtGeo("Anuradhapura State Sri Lanka");
addMarkerAtGeo("Banvia Colombia");
addMarkerAtGeo("Chittagong Hills Bangladesh");
addMarkerAtGeo("Toraya Peru");
addMarkerAtGeo("Coronel Chile");
addMarkerAtGeo("Nathuchak India");
addMarkerAtGeo("Santa Sofia Colombia");
addMarkerAtGeo("Dhuri Town India");
addMarkerAtGeo("Goodwood South Africa");
addMarkerAtGeo("Mangalaoya Sri Lanka");
addMarkerAtGeo("Jbeil Lebanon");
addMarkerAtGeo("Puerto Rico Colombia");
addMarkerAtGeo("Valle las Lomas Nicaragua");
addMarkerAtGeo("La Paz Bolivia");
addMarkerAtGeo("Colcahamba Peru");
addMarkerAtGeo("Candaleria Philippines");
addMarkerAtGeo("Ratnapura Sri Lanka");
addMarkerAtGeo("Paarl South Africa");
addMarkerAtGeo("Punniyaya India");
addMarkerAtGeo("Uson Town Philippines");
addMarkerAtGeo("Bucarmanga Colombia");
addMarkerAtGeo("Mannar District Sri Lanka");
addMarkerAtGeo("Barangay Ginagunan Ibaba Philippines");
addMarkerAtGeo("Coquimbo Chile");
addMarkerAtGeo("Urbanayoc Peru");
addMarkerAtGeo("San Benito Colombia");
addMarkerAtGeo("Caracoli Colombia");
addMarkerAtGeo("Mandaluyong Philippines");
addMarkerAtGeo("Andajes Peru");
addMarkerAtGeo("Hambamtota Sri Lanka");
addMarkerAtGeo("Trinxomalee Sri Lanka");
addMarkerAtGeo("Al-Minyah Lebanon");
addMarkerAtGeo("Gurdaspur City India");
addMarkerAtGeo("Sinhapura Sri Lanka");
addMarkerAtGeo("Saliyapura Sri Lanka");
addMarkerAtGeo("Chinchao Peru");
addMarkerAtGeo("Kalachara India");
addMarkerAtGeo("Santiago Chile");
addMarkerAtGeo("Valaichznai Sri Lanka");
addMarkerAtGeo("Panao Peru");
addMarkerAtGeo("Kalinga Apayo Prov. Philippines");
addMarkerAtGeo("El Doce Colombia");
addMarkerAtGeo("Dubricheda Village India");
addMarkerAtGeo("Matalom Philippines");
addMarkerAtGeo("Pampa de la Quinua Peru");
addMarkerAtGeo("Cotabato Philippines");
addMarkerAtGeo("Santa Rosa de Chapajilla Peru");
addMarkerAtGeo("Arauquita Colombia");
addMarkerAtGeo("Mdantsane South Africa");
addMarkerAtGeo("Joao Pessoa Brazil");
addMarkerAtGeo("Qalqilya West Bank and Gaza Strip");
addMarkerAtGeo("Corinto Colombia");
addMarkerAtGeo("Jubail Saudi Arabia");
addMarkerAtGeo("Ngora Uganda");
addMarkerAtGeo("Urmartanda India");
addMarkerAtGeo("Akbarpura India");
addMarkerAtGeo("Huila Dept Colombia");
addMarkerAtGeo("Kuchchuvelly Sri Lanka");
addMarkerAtGeo("Sittaru Sri Lanka");
addMarkerAtGeo("Rio Mantaro Valley Peru");
addMarkerAtGeo("Johannesburgh South Africa");
addMarkerAtGeo("Trincomalee City Sri Lanka");
addMarkerAtGeo("Quinua Peru");
addMarkerAtGeo("Jaffna Sri Lanka");
addMarkerAtGeo("Bangkok Thailand");
addMarkerAtGeo("Kilis Turkey");
addMarkerAtGeo("Lima* Peru");
addMarkerAtGeo("Rureasal India");
addMarkerAtGeo("San Miguel Argentina");
addMarkerAtGeo("Uchiza Peru");
addMarkerAtGeo("Aito Huallaga Peru");
addMarkerAtGeo("Chandigrarh India");
addMarkerAtGeo("Urugale Sri Lanka");
addMarkerAtGeo("Crucero Peru");
addMarkerAtGeo("Pandacan Philippines");
addMarkerAtGeo("Istanbul Turkey");
addMarkerAtGeo("San Mateo Colombia");
addMarkerAtGeo("Kurukshetra India");
addMarkerAtGeo("Kaduwela Sri Lanka");
addMarkerAtGeo("Sawhaj Egypt");
addMarkerAtGeo("Kilinochchi District Sri Lanka");
addMarkerAtGeo("Nechi Colombia");
addMarkerAtGeo("Sitio Basaggamay Philippines");
addMarkerAtGeo("Fortuna Nicaragua");
addMarkerAtGeo("Manwal India");
addMarkerAtGeo("Cairo Egypt");
addMarkerAtGeo("El Tomate Colombia");
addMarkerAtGeo("Nutan Bazar India");
addMarkerAtGeo("Maltoha India");
addMarkerAtGeo("Natal Province South Africa");
addMarkerAtGeo("Comillatilla Bangladesh");
addMarkerAtGeo("Maliduwa Sri Lanka");
addMarkerAtGeo("Unknown Guadeloupe");
addMarkerAtGeo("Gurdaspur India");
addMarkerAtGeo("Cerro Chorratosa Peru");
addMarkerAtGeo("Ludhiana District India");
addMarkerAtGeo("Matugama Sri Lanka");
addMarkerAtGeo("Barangay Hulog Philippines");
addMarkerAtGeo("Rattota Sri Lanka");
addMarkerAtGeo("Batticaloa India");
addMarkerAtGeo("Indole Sri Lanka");
addMarkerAtGeo("Ratmalgahanewa Sri Lanka");
addMarkerAtGeo("Las Burras El Salvador");
addMarkerAtGeo("Aguachica Colombia");
addMarkerAtGeo("Malimbada Sri Lanka");
addMarkerAtGeo("Davao city Philippines");
addMarkerAtGeo("Mithapur India");
addMarkerAtGeo("Seepukulam Sri Lanka");
addMarkerAtGeo("Nero-Soto Iraq");
addMarkerAtGeo("Huahuabuquio Peru");
addMarkerAtGeo("Bacolod City Philippines");
addMarkerAtGeo("Kadawatte Sri Lanka");
addMarkerAtGeo("Sincelejo Colombia");
addMarkerAtGeo("Urmur Danda India");
addMarkerAtGeo("Malla India");
addMarkerAtGeo("Ban Yarom Malaysia");
addMarkerAtGeo("Nacala Mozambique");
addMarkerAtGeo("Rio Sucio Colombia");
addMarkerAtGeo("Beruwela Sri Lanka");
addMarkerAtGeo("Sandakan Malaysia");
addMarkerAtGeo("Sapang Bato Village Philippines");
addMarkerAtGeo("Rasulpur India");
addMarkerAtGeo("Trujillo Peru");
addMarkerAtGeo("Parasedes Philippines");
addMarkerAtGeo("Anizales Nicaragua");
addMarkerAtGeo("Sigma Philippines");
addMarkerAtGeo("Karadwala India");
addMarkerAtGeo("Ropar District India");
addMarkerAtGeo("Cajiro Colombia");
addMarkerAtGeo("Zamboanga city Philippines");
addMarkerAtGeo("Khadur Saheb India");
addMarkerAtGeo("Phera Ren India");
addMarkerAtGeo("Villavicencio Colombia");
addMarkerAtGeo("Rama Mandi India");
addMarkerAtGeo("Sarhali Khord India");
addMarkerAtGeo("West Soweto South Africa");
addMarkerAtGeo("Huachipa Peru");
addMarkerAtGeo("Silay Philippines");
addMarkerAtGeo("Satipo Peru");
addMarkerAtGeo("Khodr Lebanon");
addMarkerAtGeo("Estrada Norte Chile");
addMarkerAtGeo("Puerto Limon Colombia");
addMarkerAtGeo("Rionegro Colombia");
addMarkerAtGeo("Carepa Colombia");
addMarkerAtGeo("El Bireh West Bank and Gaza Strip");
addMarkerAtGeo("Arunagoda Kapiliwala Sri Lanka");
addMarkerAtGeo("Linares Chile");
addMarkerAtGeo("Nakaon India");
addMarkerAtGeo("Buenos Aires Province Argentina");
addMarkerAtGeo("Mamelodi South Africa");
addMarkerAtGeo("Segovia Colombia");
addMarkerAtGeo("Laguna Philippines");
addMarkerAtGeo("Parow South Africa");
addMarkerAtGeo("Sierre Nevada Colombia");
addMarkerAtGeo("Port Elizabeth South Africa");
addMarkerAtGeo("Wynberg South Africa");
addMarkerAtGeo("Baisi Munipara India");
addMarkerAtGeo("Risaralda Colombia");
addMarkerAtGeo("Welimade Sri Lanka");
addMarkerAtGeo("Caramoan Philippines");
addMarkerAtGeo("Anuradhapura District Sri Lanka");
addMarkerAtGeo("Paranthan Sri Lanka");
addMarkerAtGeo("La Sierra Colombia");
addMarkerAtGeo("Casanare Dept Colombia");
addMarkerAtGeo("Roxas Philippines");
addMarkerAtGeo("Lima Dept Peru");
addMarkerAtGeo("Tamenglong India");
addMarkerAtGeo("Moga India");
addMarkerAtGeo("Skandapuram Sri Lanka");
addMarkerAtGeo("Chandgarh India");
addMarkerAtGeo("Maguindanao Province Philippines");
addMarkerAtGeo("Murunkan Sri Lanka");
addMarkerAtGeo("Mabalacat Philippines");
addMarkerAtGeo("Corihuarihuairana Peru");
addMarkerAtGeo("Hambantota Sri Lanka");
addMarkerAtGeo("Hambanota District Sri Lanka");
addMarkerAtGeo("Mirich Gogra Mahal India");
addMarkerAtGeo("Sarai Amanatkhan India");
addMarkerAtGeo("Chaticsa Peru");
addMarkerAtGeo("Dharmapura Sri Lanka");
addMarkerAtGeo("Chaguani Colombia");
addMarkerAtGeo("Bingol Turkey");
addMarkerAtGeo("Singbuli India");
addMarkerAtGeo("Cano Ballonero Venezuela");
addMarkerAtGeo("Andes Colombia");
addMarkerAtGeo("Agusan Del Norte Area Philippines");
addMarkerAtGeo("Villanveva Colombia");
addMarkerAtGeo("San Miguel Philippines");
addMarkerAtGeo("Sukhia Pokhri India");
addMarkerAtGeo("El Callao Peru");
addMarkerAtGeo("Rurthakalam India");
addMarkerAtGeo("Village Shahpur India");
addMarkerAtGeo("Tunceli Province Turkey");
addMarkerAtGeo("Paracelis Philippines");
addMarkerAtGeo("Laudium South Africa");
addMarkerAtGeo("Kwa-Altile South Africa");
addMarkerAtGeo("Lambrama Peru");
addMarkerAtGeo("Val Paraiso Chile");
addMarkerAtGeo("Pereira Colombia");
addMarkerAtGeo("Valdivia Chile");
addMarkerAtGeo("Carchuanca Peru");
addMarkerAtGeo("Bikki India");
addMarkerAtGeo("Huayanay Peru");
addMarkerAtGeo("Comas Peru");
addMarkerAtGeo("Arayat Philippines");
addMarkerAtGeo("Manchantuduwai Sri Lanka");
addMarkerAtGeo("Kuala Lumpur Malaysia");
addMarkerAtGeo("Vavuniva Area Sri Lanka");
addMarkerAtGeo("Jaffna Area Sri Lanka");
addMarkerAtGeo("Adamkulam Sri Lanka");
addMarkerAtGeo("Sanchez Mira Philippines");
addMarkerAtGeo("Oru Colombia");
addMarkerAtGeo("Ingiriya Sri Lanka");
addMarkerAtGeo("Caqueta Dept Colombia");
addMarkerAtGeo("Chittankudy Sri Lanka");
addMarkerAtGeo("Umtata South Africa");
addMarkerAtGeo("Katunayake Sri Lanka");
addMarkerAtGeo("Chitaga Colombia");
addMarkerAtGeo("Alazwa Sri Lanka");
addMarkerAtGeo("Yatalgoda Sri Lanka");
addMarkerAtGeo("Mitu Colombia");
addMarkerAtGeo("Ticlio Peru");
addMarkerAtGeo("Unknown El Salvador");
addMarkerAtGeo("Bandarawela Sri Lanka");
addMarkerAtGeo("Phiri South Africa");
addMarkerAtGeo("Maharashtra India");
addMarkerAtGeo("Dabeiba Colombia");
addMarkerAtGeo("Harinathpara Bangladesh");
addMarkerAtGeo("Germiston South Africa");
addMarkerAtGeo("Walpola Sri Lanka");
addMarkerAtGeo("Cangallo Province Peru");
addMarkerAtGeo("Welimade District Sri Lanka");
addMarkerAtGeo("Kaithal India");
addMarkerAtGeo("Rasalpura India");
addMarkerAtGeo("Kanpur India");
addMarkerAtGeo("Ncambedlane South Africa");
addMarkerAtGeo("Ghagharvana India");
addMarkerAtGeo("San Remigio Philippines");
addMarkerAtGeo("El Diviso Colombia");
addMarkerAtGeo("Badulla Sri Lanka");
addMarkerAtGeo("ICA Peru");
addMarkerAtGeo("Pailita Colombia");
addMarkerAtGeo("Chitembo Angola");
addMarkerAtGeo("Satrah Kalan India");
addMarkerAtGeo("Santa Elena Peru");
addMarkerAtGeo("Kampala Uganda");
addMarkerAtGeo("Kuriwala Village India");
addMarkerAtGeo("Penda India");
addMarkerAtGeo("Kumaripara Bangladesh");
addMarkerAtGeo("Pisco Peru");
addMarkerAtGeo("Monarangala Sri Lanka");
addMarkerAtGeo("Molle Bamba Peru");
addMarkerAtGeo("Andacollo Chile");
addMarkerAtGeo("Cabijo Colombia");
addMarkerAtGeo("Cape Town South Africa");
addMarkerAtGeo("Bruj Kharon India");
addMarkerAtGeo("Puerto Asis Colombia");
addMarkerAtGeo("Ibague Colombia");
addMarkerAtGeo("Tinde India");
addMarkerAtGeo("Dhaurewal India");
addMarkerAtGeo("Angunukolapalessa Sri Lanka");
addMarkerAtGeo("Thokoza South Africa");
addMarkerAtGeo("San Marcos Colombia");
addMarkerAtGeo("Tawac Philippines");
addMarkerAtGeo("Soroti Uganda");
addMarkerAtGeo("Nueva Vizcaya Philippines");
addMarkerAtGeo("Lira Uganda");
addMarkerAtGeo("Pailitas Colombia");
addMarkerAtGeo("Astania Peru");
addMarkerAtGeo("Ambo Peru");
addMarkerAtGeo("Tarn Taran India");
addMarkerAtGeo("Cadiz City Philippines");
addMarkerAtGeo("Ratmalana Sri Lanka");
addMarkerAtGeo("Acosvinchos Peru");
addMarkerAtGeo("Kawkareik Myanmar");
addMarkerAtGeo("Transkei South Africa");
addMarkerAtGeo("Cabantuan City Philippines");
addMarkerAtGeo("Miranda Colombia");
addMarkerAtGeo("Gurdasdur India");
addMarkerAtGeo("Dallin India");
addMarkerAtGeo("Marawila Sri Lanka");
addMarkerAtGeo("Trincolmalee area Sri Lanka");
addMarkerAtGeo("Malinboda Sri Lanka");
addMarkerAtGeo("Lezd Spain");
addMarkerAtGeo("Mount Fletcher South Africa");
addMarkerAtGeo("Cerro Runa Peru");
addMarkerAtGeo("Manochahal India");
addMarkerAtGeo("Loma de Gonzalez Colombia");
addMarkerAtGeo("Talalameque Colombia");
addMarkerAtGeo("Chittangong Hill Tracts Bangladesh");
addMarkerAtGeo("Noharkaya Village India");
addMarkerAtGeo("Sirajganji District Bangladesh");
addMarkerAtGeo("Sakoha India");
addMarkerAtGeo("Vega Colombia");
addMarkerAtGeo("Lahore Pakistan");
addMarkerAtGeo("Bir Elias Lebanon");
addMarkerAtGeo("Caceres Colombia");
addMarkerAtGeo("Imphal India");
addMarkerAtGeo("Guasdualito Venezuela");
addMarkerAtGeo("Wemalkatiya Sri Lanka");
addMarkerAtGeo("Amritsar City India");
addMarkerAtGeo("Caguas Peru");
addMarkerAtGeo("Iyolwa Uganda");
addMarkerAtGeo("Alto Sinu Area Colombia");
addMarkerAtGeo("Chimbote Peru");
addMarkerAtGeo("Sarugaskanda Sri Lanka");
addMarkerAtGeo("Kandy Sri Lanka");
addMarkerAtGeo("San Pedro y Arbolete Colombia");
addMarkerAtGeo("Buenos Aires Argentina");
addMarkerAtGeo("Armango Peru");
addMarkerAtGeo("Jullundur City India");
addMarkerAtGeo("Central Andes Peru");
addMarkerAtGeo("Tunia Colombia");
addMarkerAtGeo("Makoo India");
addMarkerAtGeo("Arioa Chile");
addMarkerAtGeo("Versalles Colombia");
addMarkerAtGeo("Muruthamulai Sri Lanka");
addMarkerAtGeo("Nicosia Cyprus");
addMarkerAtGeo("Al-Manara Israel");
addMarkerAtGeo("Loma Linda El Salvador");
addMarkerAtGeo("Urugodawatte Sri Lanka");
addMarkerAtGeo("Silla de Oro El Salvador");
addMarkerAtGeo("Davao Del Norte Province Philippines");
addMarkerAtGeo("Rajpura Town India");
addMarkerAtGeo("Bophuthatswana South Africa");
addMarkerAtGeo("Cerritos Colombia");
addMarkerAtGeo("Julcamarca Peru");
addMarkerAtGeo("Surt Province Turkey");
addMarkerAtGeo("Sogamoso Colombia");
addMarkerAtGeo("Talcahuano Chile");
addMarkerAtGeo("Zanjones Nicaragua");
addMarkerAtGeo("Ain Al Hilweh Lebanon");
addMarkerAtGeo("Kalimpong Town India");
addMarkerAtGeo("Gujarpur Dist. India");
addMarkerAtGeo("Al-Biqa Lebanon");
addMarkerAtGeo("Bignona Senegal");
addMarkerAtGeo("Amparo Sri Lanka");
addMarkerAtGeo("Rishon Leziyyon Israel");
addMarkerAtGeo("Lima Peru");
addMarkerAtGeo("Kondavil Sri Lanka");
addMarkerAtGeo("Windhoek Namibia");
addMarkerAtGeo("Attock Pakistan");
addMarkerAtGeo("Patti Town India");
addMarkerAtGeo("Actonville South Africa");
addMarkerAtGeo("Sammanturai Sri Lanka");
addMarkerAtGeo("Cordoba Colombia");
addMarkerAtGeo("Sirhind India");
addMarkerAtGeo("Mudki India");
addMarkerAtGeo("Tikkapur India");
addMarkerAtGeo("Matalum Philippines");
addMarkerAtGeo("Gokulpar India");
addMarkerAtGeo("Dhulewal India");
addMarkerAtGeo("Merida Venezuela");
addMarkerAtGeo("Strand South Africa");
addMarkerAtGeo("Urubokka Sri Lanka");
addMarkerAtGeo("Not Indicated Sri Lanka");
addMarkerAtGeo("Tulkarem West Bank and Gaza Strip");
addMarkerAtGeo("Nanshuimpuquio Peru");
addMarkerAtGeo("Rawal Pindi Pakistan");
addMarkerAtGeo("Rasai - Naqurah Lebanon");
addMarkerAtGeo("Uitenhage South Africa");
addMarkerAtGeo("Johannesburg South Africa");
addMarkerAtGeo("San Alberto Colombia");
addMarkerAtGeo("Barngay Tupol Philippines");
addMarkerAtGeo("Lanao Philippines");
addMarkerAtGeo("Concepcion Chile");
addMarkerAtGeo("Valparaiso Chile");
addMarkerAtGeo("Kondachichi Sri Lanka");
addMarkerAtGeo("Bholi India");
addMarkerAtGeo("Sonepat India");
addMarkerAtGeo("Phaguri India");
addMarkerAtGeo("Kallar Sri Lanka");
addMarkerAtGeo("Ponerihouen New Caledonia");
addMarkerAtGeo("Caucasia Colombia");
addMarkerAtGeo("Sainamarthu Spain");
addMarkerAtGeo("Chinquite Peru");
addMarkerAtGeo("Kotsukia India");
addMarkerAtGeo("Manuar District Sri Lanka");
addMarkerAtGeo("Ajnala India");
addMarkerAtGeo("BRAKPAN South Africa");
addMarkerAtGeo("Springs South Africa");
addMarkerAtGeo("Sea Point South Africa");
addMarkerAtGeo("Tucuman Argentina");
addMarkerAtGeo("Ruanda Angola");
addMarkerAtGeo("Arayanga Peru");
addMarkerAtGeo("Cuzco Peru");
addMarkerAtGeo("Runahuajusta Peru");
addMarkerAtGeo("Chabal India");
addMarkerAtGeo("Pesalai Sri Lanka");
addMarkerAtGeo("Somerset West South Africa");
addMarkerAtGeo("Bunao Philippines");
addMarkerAtGeo("Temuco Chile");
addMarkerAtGeo("Matucana Peru");
addMarkerAtGeo("Morawaka Sri Lanka");
addMarkerAtGeo("Jalpaiguri District India");
addMarkerAtGeo("Davao City Philippines");
addMarkerAtGeo("Morawewa Sri Lanka");
addMarkerAtGeo("Nablus West Bank and Gaza Strip");
addMarkerAtGeo("Pattiamuttu Sri Lanka");
addMarkerAtGeo("Srihargobindpur India");
addMarkerAtGeo("Cali Colombia");
addMarkerAtGeo("Amalfi Colombia");
addMarkerAtGeo("Gaitania Colombia");
addMarkerAtGeo("Mongotapoe Suriname");
addMarkerAtGeo("Sabzimandi Pakistan");
addMarkerAtGeo("Puerto Lopez Colombia");
addMarkerAtGeo("Kefar Sava Israel");
addMarkerAtGeo("Burqa Israel");
addMarkerAtGeo("Valachchenai Sri Lanka");
addMarkerAtGeo("Alexandra South Africa");
addMarkerAtGeo("Valle Del Mantaro Peru");
addMarkerAtGeo("San Francisco del Rayo Colombia");
addMarkerAtGeo("Urubokke Sri Lanka");
addMarkerAtGeo("Pichinaqui Peru");
addMarkerAtGeo("Rohini Valley India");
addMarkerAtGeo("Oshakati Namibia");
addMarkerAtGeo("Apkumbuka Sri Lanka");
addMarkerAtGeo("Cantagallo Colombia");
addMarkerAtGeo("Todapur India");
addMarkerAtGeo("Sadda Pakistan");
addMarkerAtGeo("Cachira Colombia");
addMarkerAtGeo("Walapane Sri Lanka");
addMarkerAtGeo("Gurdaspur district India");
addMarkerAtGeo("Santa Marta Colombia");
addMarkerAtGeo("Puerto Esperanza Colombia");
addMarkerAtGeo("Loma Abajo Colombia");
addMarkerAtGeo("Maisanpur India");
addMarkerAtGeo("Los Bancos Venezuela");
addMarkerAtGeo("Minuwangoda Sri Lanka");
addMarkerAtGeo("Panchkula India");
addMarkerAtGeo("Hammarsdale South Africa");
addMarkerAtGeo("Moraketiya Sri Lanka");
addMarkerAtGeo("Garcia Rovira Colombia");
addMarkerAtGeo("Malanje Angola");
addMarkerAtGeo("Jalalabad Afghanistan");
addMarkerAtGeo("Santander Dept Colombia");
addMarkerAtGeo("Barpeta Road India");
addMarkerAtGeo("Maguindanao Philippines");
addMarkerAtGeo("Caldcau City Philippines");
addMarkerAtGeo("Lahugala Sri Lanka");
addMarkerAtGeo("Pathankot India");
addMarkerAtGeo("Apartado Colombia");
addMarkerAtGeo("Galmitiyawa Sri Lanka");
addMarkerAtGeo("Bhagana India");
addMarkerAtGeo("Saisa Colombia");
addMarkerAtGeo("Tarakli Turkey");
addMarkerAtGeo("Batroun Lebanon");
addMarkerAtGeo("Navawarian India");
addMarkerAtGeo("Ankara Turkey");
addMarkerAtGeo("Gaginangal India");
addMarkerAtGeo("Kardipovian Sri Lanka");
addMarkerAtGeo("Tibu Colombia");
addMarkerAtGeo("San Marlos Guatemala");
addMarkerAtGeo("Sucre Colombia");
addMarkerAtGeo("Tanjeli India");
addMarkerAtGeo("Abu Bushut Iraq");
addMarkerAtGeo("Pozo Azul Colombia");
addMarkerAtGeo("Peque Colombia");
addMarkerAtGeo("Negros Island Philippines");
addMarkerAtGeo("Chica Colombia");
addMarkerAtGeo("Arauca Dept. Colombia");
addMarkerAtGeo("Bethlehem West Bank and Gaza Strip");
addMarkerAtGeo("Yarai Peru");
addMarkerAtGeo("Morales Colombia");
addMarkerAtGeo("Tigre Province Ethiopia");
addMarkerAtGeo("Columbo Sri Lanka");
addMarkerAtGeo("Aracata Peru");
addMarkerAtGeo("Oddusudan Sri Lanka");
addMarkerAtGeo("Canete Peru");
addMarkerAtGeo("Vilcashuaman Peru");
addMarkerAtGeo("Mejor Esquina Colombia");
addMarkerAtGeo("Diepkloof South Africa");
addMarkerAtGeo("Mesetas Colombia");
addMarkerAtGeo("Wele Zambia");
addMarkerAtGeo("Pattaya Thailand");
addMarkerAtGeo("Mehma India");
addMarkerAtGeo("Gompotown South Africa");
addMarkerAtGeo("Tinsukhia India");
addMarkerAtGeo("Ludhiana City India");
addMarkerAtGeo("El Basurero El Salvador");
addMarkerAtGeo("Angunokolapallassa Sri Lanka");
addMarkerAtGeo("Tarlac Philippines");
addMarkerAtGeo("Cerro Azul Colombia");
addMarkerAtGeo("Khartoum Sudan");
addMarkerAtGeo("La Granja Colombia");
addMarkerAtGeo("Navasar India");
addMarkerAtGeo("Ratmapura District Sri Lanka");
addMarkerAtGeo("Mankulam Sri Lanka");
addMarkerAtGeo("Bhamo Myanmar");
addMarkerAtGeo("Thiriyaye Sri Lanka");
addMarkerAtGeo("Mocoa Colombia");
addMarkerAtGeo("Derakalan India");
addMarkerAtGeo("Talca Chile");
addMarkerAtGeo("Atimonan Philippines");
addMarkerAtGeo("La Union Colombia");
addMarkerAtGeo("Rivera Colombia");
addMarkerAtGeo("Zamboanga City Philippines");
addMarkerAtGeo("Biddya West Bank and Gaza Strip");
addMarkerAtGeo("Batticaloa District Sri Lanka");
addMarkerAtGeo("Gintota Sri Lanka");
addMarkerAtGeo("Currulao Colombia");
addMarkerAtGeo("Calapuja District Peru");
addMarkerAtGeo("Cerrito Colombia");
addMarkerAtGeo("Cerro Yana Orto Peru");
addMarkerAtGeo("Cagayan Philippines");
addMarkerAtGeo("Wallewatte Sri Lanka");
addMarkerAtGeo("Gurdspur India");
addMarkerAtGeo("San Vicente de Chucuri Colombia");
addMarkerAtGeo("Belacazar Colombia");
addMarkerAtGeo("Iloilo Philippines");
addMarkerAtGeo("Jodhan Nagri India");
addMarkerAtGeo("Pessene Mozambique");
addMarkerAtGeo("Mongpu India");
addMarkerAtGeo("Direlki Turkey");
addMarkerAtGeo("Suncho Peru");
addMarkerAtGeo("Mahangipara Bangladesh");
addMarkerAtGeo("San Pablo Colombia");
addMarkerAtGeo("Jessore area Bangladesh");
addMarkerAtGeo("Maputo Mozambique");
addMarkerAtGeo("Loma de Sabaneta Colombia");
addMarkerAtGeo("Peshawar Pakistan");
addMarkerAtGeo("Nawath Kadu Sri Lanka");
addMarkerAtGeo("Pelaya Colombia");
addMarkerAtGeo("Monteria Colombia");
addMarkerAtGeo("Livingston Zambia");
addMarkerAtGeo("Dalli India");
addMarkerAtGeo("Albay Philippines");
addMarkerAtGeo("Inchope Mozambique");
addMarkerAtGeo("Tupe Peru");
addMarkerAtGeo("Ramgarh India");
addMarkerAtGeo("Asacasi Peru");
addMarkerAtGeo("Ferrenafe Peru");
addMarkerAtGeo("Moratuwa Sri Lanka");
addMarkerAtGeo("Swakopmund Namibia");
addMarkerAtGeo("Gampola Sri Lanka");
addMarkerAtGeo("Quito Ecuador");
addMarkerAtGeo("Jerico Colombia");
addMarkerAtGeo("Karmuwal India");
addMarkerAtGeo("unknown Colombia");
addMarkerAtGeo("Lamot Town Philippines");
addMarkerAtGeo("Witbank South Africa");
addMarkerAtGeo("gurdaspur district India");
addMarkerAtGeo("Huanta Peru");
addMarkerAtGeo("Porac Town Philippines");
addMarkerAtGeo("Tame Colombia");
addMarkerAtGeo("Puerto Libertador Colombia");
addMarkerAtGeo("Barranca Peru");
addMarkerAtGeo("Near Santiago de Chuco Peru");
addMarkerAtGeo("Vegalarga Colombia");
addMarkerAtGeo("Bisho South Africa");
addMarkerAtGeo("San Joaquin Chile");
addMarkerAtGeo("Izmir Turkey");
addMarkerAtGeo("Ortabag Turkey");
addMarkerAtGeo("Okahandja Namibia");
addMarkerAtGeo("Nittikaikulam Sri Lanka");
addMarkerAtGeo("Sunderchak India");
addMarkerAtGeo("Apartao Colombia");
addMarkerAtGeo("Barranco Peru");
addMarkerAtGeo("La Serena Chile");
addMarkerAtGeo("Durban South Africa");
addMarkerAtGeo("Cotabambas Peru");
addMarkerAtGeo("Mastita Lebanon");
addMarkerAtGeo("Carcasi Colombia");
addMarkerAtGeo("Sanata Marta Colombia");
addMarkerAtGeo("La Herradura Peru");
addMarkerAtGeo("Liumbale Angola");
addMarkerAtGeo("Cerro Condorillo Peru");
addMarkerAtGeo("Lapaz Bolivia");
addMarkerAtGeo("Granada Colombia");
addMarkerAtGeo("Panadura Sri Lanka");
addMarkerAtGeo("San Antonio de Quiccha Peru");
addMarkerAtGeo("Pietermaritzburg South Africa");
addMarkerAtGeo("Kwatema South Africa");
addMarkerAtGeo("Marjayoun Lebanon");
addMarkerAtGeo("La Belleza Colombia");
addMarkerAtGeo("Phagawara India");
addMarkerAtGeo("Muttur Sri Lanka");
addMarkerAtGeo("Lenasia South Africa");
addMarkerAtGeo("Queuna Peru");
addMarkerAtGeo("Campoalegre Colombia");
addMarkerAtGeo("Simiti Colombia");
addMarkerAtGeo("Olongapo Philippines");
addMarkerAtGeo("Galagedera Sri Lanka");
addMarkerAtGeo("Magamana Sri Lanka");
addMarkerAtGeo("Murukandy Sri Lanka");
addMarkerAtGeo("Doradal Colombia");
addMarkerAtGeo("Weli-Oya Village Sri Lanka");
addMarkerAtGeo("Juntas de Uramita Colombia");
addMarkerAtGeo("Bel Vista Mozambique");
addMarkerAtGeo("Bridgewater South Africa");
addMarkerAtGeo("Lota Chile");
addMarkerAtGeo("Pozorrubio Philippines");
addMarkerAtGeo("Tunceli Prov. Turkey");
addMarkerAtGeo("Sansara India");
addMarkerAtGeo("Lenawa Sri Lanka");
addMarkerAtGeo("Narathiwat Province Thailand");
addMarkerAtGeo("Colombo Sri Lanka");
addMarkerAtGeo("Taraza Colombia");
addMarkerAtGeo("Sundargarh India");
addMarkerAtGeo("San Jacinto Peru");
addMarkerAtGeo("San Rafael Colombia");
addMarkerAtGeo("Portoviejo Ecuador");
addMarkerAtGeo("Tanquipuquio Peru");
addMarkerAtGeo("Ovetta Pakistan");
addMarkerAtGeo("Batala India");
addMarkerAtGeo("Tindela Philippines");
addMarkerAtGeo("Maluana Mozambique");
addMarkerAtGeo("Mariangola Colombia");
addMarkerAtGeo("Bugallon Town Philippines");
addMarkerAtGeo("Paramonga Peru");
addMarkerAtGeo("Puerto Wilches Colombia");
addMarkerAtGeo("Tayabamba Peru");
addMarkerAtGeo("Cienaga de Oro Colombia");
addMarkerAtGeo("Calapuja Peru");
addMarkerAtGeo("Amparai District Sri Lanka");
addMarkerAtGeo("Canaletes Colombia");
addMarkerAtGeo("Panipat India");
addMarkerAtGeo("Guican Colombia");
addMarkerAtGeo("Goyllarisquizga Peru");
addMarkerAtGeo("Valparaiso Colombia");
addMarkerAtGeo("Sao Paulo Brazil");
addMarkerAtGeo("Lalru India");
addMarkerAtGeo("Zambales Philippines");
addMarkerAtGeo("Huancayo Peru");
addMarkerAtGeo("Abra Philippines");
addMarkerAtGeo("Katlehong South Africa");
addMarkerAtGeo("Risaraldo dept Colombia");
